/* 自動產生 — ①讀 curated.json、②每日 Gemini 研究;勿手動編輯(改①請編 curated.json) */
window.DIGEST = {
  "updatedAt": "2026-10-02T04:36:27+08:00",
  "updatedDateLabel": "2026 年 10 月 2 日",
  "month": "2026 年 10 月",
  "month_en": "October 2026",
  "dataConfidence": "①整體=手工校正權威版;②本月最新由 gemini-2.5-flash+Google 搜尋於 2026/10/02 自動更新",
  "dataConfidence_en": "① curated (hand-verified); ② this-month auto-updated by gemini-2.5-flash+Google Search on 2026/10/02",
  "changesToday": [
    "Claude Opus 5.5 (9/22) — 綜合 AI MODEL 排名",
    "GPT-6.1 Sol (9/29) — 綜合 AI MODEL 排名",
    "Claude Opus 5.5 (9/22) — 創建遊戲的助手",
    "GPT-6 Astra (9/3) — 創建遊戲的助手",
    "GPT-6 Astra (9/3) — 創建數據模擬器 & 數據推理",
    "Claude Opus 5.5 (9/22) — 創建數據模擬器 & 數據推理"
  ],
  "changesToday_en": [
    "Claude Opus 5.5 (9/22) — Overall AI Model Ranking",
    "GPT-6.1 Sol (9/29) — Overall AI Model Ranking",
    "Claude Opus 5.5 (9/22) — Game-Building Assistants",
    "GPT-6 Astra (9/3) — Game-Building Assistants",
    "GPT-6 Astra (9/3) — Data Simulators & Reasoning",
    "Claude Opus 5.5 (9/22) — Data Simulators & Reasoning"
  ],
  "notes": [
    "中立聲明:①整體榜以第三方獨立榜為準(綜合=AA 指數、編程=SWE-bench、推理=GPQA、圖片=LMArena Arena)、只列已發佈模型、經人工校正,非本 AI 或任何廠商觀點。",
    "①整體=手工校正的權威版(穩定);②本月最新=每日免費自動研究(僅供速覽,偶有出入請點源覆核)。",
    "排名每天會動:AA 為 72 小時滾動、LMArena Elo 每天浮動,第 2~5 名常在誤差內。"
  ],
  "notes_en": [
    "Neutrality: ① follows independent third-party leaderboards (General=AA Index, Coding=SWE-bench, Reasoning=GPQA, Image=LMArena Arena), GA models only, human-verified — not this AI's or any vendor's view.",
    "① = hand-curated authoritative (stable); ② = free auto-research daily (quick reference; verify against sources).",
    "Rankings shift daily: AA is a 72-hour rolling average and LMArena Elo moves; ranks 2–5 are often within noise."
  ],
  "categories": [
    {
      "id": 1,
      "icon": "🧠",
      "name": "綜合 AI MODEL 排名",
      "name_en": "Overall AI Model Ranking",
      "subtitle": "依 AA 智能指數 · Gemini / Claude / GPT",
      "subtitle_en": "By AA Intelligence Index · Gemini / Claude / GPT",
      "overall": [
        {
          "rank": 1,
          "name": "Claude Opus 5",
          "vendor": "Anthropic",
          "vendor_en": "Anthropic",
          "score": "AA 61",
          "score_en": "AA 61",
          "why": "AA 智能指數世界第一(61, v4.1);Claude Max 新預設,價僅 Fable 半價",
          "why_en": "#1 in the world on AA Intelligence Index (61, v4.1); new Claude Max default at half Fable's price",
          "meta": "7/24 發佈 · $5/$25 · Max 預設",
          "meta_en": "Released 7/24 · $5/$25 · Max default"
        },
        {
          "rank": 2,
          "name": "Claude Fable 5",
          "vendor": "Anthropic",
          "vendor_en": "Anthropic",
          "score": "AA 60",
          "why": "AA 智能指數 60,僅次於 Opus 5;公開可用最強之一",
          "why_en": "AA Index 60, just behind Opus 5; among the strongest available",
          "meta": "7/1 全球返場 · 曾因出口管制暫停 18 天",
          "meta_en": "Returned globally 7/1 · was suspended 18 days",
          "score_en": "AA 60"
        },
        {
          "rank": 3,
          "name": "GPT-5.6 Sol",
          "vendor": "OpenAI",
          "vendor_en": "OpenAI",
          "score": "AA 59",
          "score_en": "AA 59",
          "why": "AA 智能指數 #2(59);OpenAI 新一代旗艦",
          "why_en": "#2 on AA Intelligence Index (59); OpenAI's new flagship",
          "meta": "7/9 發佈",
          "meta_en": "Released 7/9"
        },
        {
          "rank": 4,
          "name": "Kimi K3",
          "vendor": "Moonshot AI 月之暗面",
          "vendor_en": "Moonshot AI",
          "score": "AA 57",
          "score_en": "AA 57",
          "why": "AA 智能指數 57.1,首度躋身前段",
          "why_en": "AA Intelligence Index 57.1; breaks into the top tier",
          "meta": "2026-07 新進榜",
          "meta_en": "New on the board, July 2026"
        },
        {
          "rank": 5,
          "name": "Claude Opus 4.8",
          "vendor": "Anthropic",
          "vendor_en": "Anthropic",
          "score": "AA 56",
          "why": "AA 智能指數 #1(61.4);獨立第三方確認",
          "why_en": "#1 on AA Intelligence Index (61.4); independently confirmed",
          "meta": "5/28 發佈 · API $5/$25",
          "meta_en": "Released 5/28 · API $5/$25",
          "score_en": "AA 56"
        }
      ],
      "monthly": {
        "note": null,
        "note_en": null,
        "items": [
          {
            "rank": 1,
            "name": "Claude Opus 5.5",
            "version": "5.5",
            "vendor": "Anthropic",
            "vendor_en": "Anthropic",
            "date": "9/22",
            "date_en": "Sep 22",
            "isNew": true,
            "overlap": null,
            "overlap_en": null,
            "why": "本月最新發佈中綜合能力最強，在多個排行榜中位居前列。",
            "why_en": "The most capable model among this month's new releases, ranking highly across multiple leaderboards."
          },
          {
            "rank": 2,
            "name": "GPT-6.1 Sol",
            "version": "6.1 Sol",
            "vendor": "OpenAI",
            "vendor_en": "OpenAI",
            "date": "9/29",
            "date_en": "Sep 29",
            "isNew": true,
            "overlap": null,
            "overlap_en": null,
            "why": "提供接近 GPT-6 Astra 的旗艦級性能，尤其在程式碼和專業任務方面表現卓越。",
            "why_en": "Offers near-flagship performance comparable to GPT-6 Astra, excelling in coding and professional tasks."
          },
          {
            "rank": 3,
            "name": "Claude Fable 5.1",
            "version": "5.1",
            "vendor": "Anthropic",
            "vendor_en": "Anthropic",
            "date": "9/1",
            "date_en": "Sep 1",
            "isNew": true,
            "overlap": null,
            "overlap_en": null,
            "why": "作為 Fable 5 的繼任者，在通用智能和代理工作方面有顯著提升。",
            "why_en": "As the successor to Fable 5, it offers significant improvements in general intelligence and agentic capabilities."
          },
          {
            "rank": 4,
            "name": "GPT-6 Sol",
            "version": "6 Sol",
            "vendor": "OpenAI",
            "vendor_en": "OpenAI",
            "date": "9月",
            "date_en": "Sep",
            "isNew": true,
            "overlap": null,
            "overlap_en": null,
            "why": "OpenAI 推出的新一代旗艦模型，性能強大且廣泛可用。",
            "why_en": "OpenAI's new generation flagship model, offering powerful and widely available performance."
          },
          {
            "rank": 5,
            "name": "Claude Sonnet 5.5",
            "version": "5.5",
            "vendor": "Anthropic",
            "vendor_en": "Anthropic",
            "date": "9/27",
            "date_en": "Sep 27",
            "isNew": true,
            "overlap": null,
            "overlap_en": null,
            "why": "作為 Opus 5.5 的高效能補充，以更低的成本提供接近旗艦級的表現。",
            "why_en": "A high-performance complement to Opus 5.5, offering near-flagship capabilities at a lower cost."
          }
        ]
      }
    },
    {
      "id": 2,
      "icon": "🎮",
      "name": "創建遊戲的助手",
      "name_en": "Game-Building Assistants",
      "subtitle": "AI 編程(依 SWE-bench) · 你的 Three.js + Claude Code + GitHub + Vercel pipeline",
      "subtitle_en": "AI coding (by SWE-bench) · your Three.js + Claude Code + GitHub + Vercel pipeline",
      "overall": [
        {
          "rank": 1,
          "name": "Claude Opus 5",
          "vendor": "Anthropic",
          "vendor_en": "Anthropic",
          "score": "AA 編程#1",
          "score_en": "AA Coding #1",
          "why": "領先 AA 編程指數(SWE-Atlas-QnA 最高);搭 Claude Code 最強",
          "why_en": "#1 on AA Coding Index (top SWE-Atlas-QnA); strongest paired with Claude Code",
          "meta": "7/24 · Max 預設",
          "meta_en": "7/24 · Max default"
        },
        {
          "rank": 2,
          "name": "Claude Fable 5",
          "vendor": "Anthropic",
          "vendor_en": "Anthropic",
          "score": "SWE 95%",
          "score_en": "SWE 95%",
          "why": "SWE-bench Verified 95%;編程次於 Opus 5(公開可用第二強)",
          "why_en": "SWE-bench Verified 95%; #2 coding behind Opus 5",
          "meta": "7/1 返場 · Mythos 級",
          "meta_en": "Returned 7/1 · Mythos-class"
        },
        {
          "rank": 3,
          "name": "GPT-5.5",
          "vendor": "OpenAI",
          "vendor_en": "OpenAI",
          "score": "SWE 88.7%",
          "why": "公開 SWE-bench Verified 第一(88.7%);Codex/Copilot 內建",
          "why_en": "#1 on public SWE-bench Verified (88.7%); built into Codex/Copilot",
          "meta": "4/23 · ChatGPT/API",
          "meta_en": "4/23 · ChatGPT/API"
        },
        {
          "rank": 4,
          "name": "Claude Opus 4.8",
          "vendor": "Anthropic",
          "vendor_en": "Anthropic",
          "score": "SWE 88.6%",
          "why": "SWE 88.6%(幾乎並列第一);WebDev Arena 第一,最適合你的 Three.js 前端",
          "why_en": "SWE 88.6% (near-tied for #1); #1 on WebDev Arena — best for your Three.js frontend",
          "meta": "5/28 · Claude Code 原生",
          "meta_en": "5/28 · native to Claude Code"
        },
        {
          "rank": 5,
          "name": "Claude Opus 4.7",
          "vendor": "Anthropic",
          "vendor_en": "Anthropic",
          "score": "SWE 87.6%",
          "why": "前代旗艦,SWE 87.6%,WebDev 仍強",
          "why_en": "Prior flagship, SWE 87.6%, still strong on WebDev",
          "meta": "~4 月 · Claude API",
          "meta_en": "~Apr · Claude API"
        }
      ],
      "monthly": {
        "note": null,
        "note_en": null,
        "items": [
          {
            "rank": 1,
            "name": "Claude Opus 5.5",
            "version": "5.5",
            "vendor": "Anthropic",
            "vendor_en": "Anthropic",
            "date": "9/22",
            "date_en": null,
            "isNew": true,
            "overlap": null,
            "overlap_en": null,
            "why": "Anthropic最新旗艦模型，專為長時間代理編程和知識工作設計，在SWE-bench Pro和LMArena WebDev榜單上表現領先，是遊戲開發助手的強大選擇。",
            "why_en": "Anthropic's latest flagship model, designed for long-running agentic coding and knowledge work, leads on SWE-bench Pro and LMArena WebDev, making it a powerful choice for game development assistants."
          },
          {
            "rank": 2,
            "name": "GPT-6 Astra",
            "version": "6 Astra",
            "vendor": "OpenAI",
            "vendor_en": "OpenAI",
            "date": "9/3",
            "date_en": null,
            "isNew": true,
            "overlap": null,
            "overlap_en": null,
            "why": "OpenAI最智能且對齊的模型，在電腦使用、編程、網絡安全和科學方面具備最先進的能力，適合複雜的遊戲開發任務。",
            "why_en": "OpenAI's most intelligent and aligned model, with state-of-the-art capabilities across computer use, coding, cybersecurity, and science, suitable for complex game development tasks."
          },
          {
            "rank": 3,
            "name": "Claude Fable 5.1",
            "version": "5.1",
            "vendor": "Anthropic",
            "vendor_en": "Anthropic",
            "date": "9/1",
            "date_en": null,
            "isNew": true,
            "overlap": null,
            "overlap_en": null,
            "why": "Anthropic的進階編程和知識工作模型，專為嚴苛的推理和長週期代理工作設計，在SWE-bench Pro上表現優異。",
            "why_en": "Anthropic's advanced coding and knowledge work model, designed for demanding reasoning and long-horizon agentic work, with strong performance on SWE-bench Pro."
          },
          {
            "rank": 4,
            "name": "GPT-6.1 Sol",
            "version": "6.1 Sol",
            "vendor": "OpenAI",
            "vendor_en": "OpenAI",
            "date": "9/29",
            "date_en": null,
            "isNew": true,
            "overlap": null,
            "overlap_en": null,
            "why": "GPT-6 Sol的重大升級版，在代理編程、電腦使用和專業工作方面表現卓越，以更低成本提供接近Astra的智能。",
            "why_en": "A major upgrade to GPT-6 Sol with exceptionally strong performance on agentic coding, computer use, and professional work, delivering near-Astra intelligence at a lower cost."
          },
          {
            "rank": 5,
            "name": "Gemini 3.8 Flash",
            "version": "3.8 Flash",
            "vendor": "Google",
            "vendor_en": "Google",
            "date": "9/2",
            "date_en": null,
            "isNew": true,
            "overlap": null,
            "overlap_en": null,
            "why": "Google最智能的Flash模型，專為長週期軟體工程、自主代理和複雜企業工作流程設計，是Antigravity編程助手的核心。",
            "why_en": "Google's most intelligent Flash model, engineered for long-horizon software engineering, autonomous agents, and complex enterprise workflows, serving as the core of the Antigravity coding assistant."
          }
        ]
      }
    },
    {
      "id": 3,
      "icon": "📊",
      "name": "創建數據模擬器 & 數據推理",
      "name_en": "Data Simulators & Reasoning",
      "subtitle": "依 GPQA Diamond · 對應你的「深海奪寶」RTP 沙盤",
      "subtitle_en": "By GPQA Diamond · for your 'Abyss Treasury' RTP sandbox",
      "overall": [
        {
          "rank": 1,
          "name": "Gemini 3.1 Pro",
          "vendor": "Google",
          "vendor_en": "Google",
          "score": "GPQA 94.1%",
          "why": "GPQA Diamond 第一(94.1%);大 context 適合分析大量模擬結果",
          "why_en": "#1 on GPQA Diamond (94.1%); big context for analyzing large result sets",
          "meta": "~Q1 · AI Studio/Vertex",
          "meta_en": "~Q1 · AI Studio/Vertex"
        },
        {
          "rank": 2,
          "name": "Claude Opus 5",
          "vendor": "Anthropic",
          "vendor_en": "Anthropic",
          "score": "AA 61",
          "score_en": "AA 61",
          "why": "AA 綜合智能世界第一(61);推理屬頂段",
          "why_en": "#1 overall on AA (61); top-tier reasoning",
          "meta": "7/24 · Max 預設",
          "meta_en": "7/24 · Max default"
        },
        {
          "rank": 3,
          "name": "Claude Fable 5",
          "vendor": "Anthropic",
          "vendor_en": "Anthropic",
          "score": "AA 60",
          "score_en": "AA 60",
          "why": "綜合智能第一;推理屬頂段(GPQA 前段)",
          "why_en": "#1 overall intelligence; top-tier reasoning (GPQA leading pack)",
          "meta": "7/1 返場 · Mythos 級",
          "meta_en": "Returned 7/1 · Mythos-class"
        },
        {
          "rank": 4,
          "name": "GPT-5.5 (xhigh)",
          "vendor": "OpenAI",
          "vendor_en": "OpenAI",
          "score": "GPQA 93.5%",
          "why": "GPQA 93.5%;純機率數學最強",
          "why_en": "GPQA 93.5%; best at pure probability math",
          "meta": "4/23 · 機率推導",
          "meta_en": "4/23 · probability reasoning"
        },
        {
          "rank": 5,
          "name": "Claude Opus 4.8 (max)",
          "vendor": "Anthropic",
          "vendor_en": "Anthropic",
          "score": "AA 56",
          "score_en": "AA 56",
          "why": "綜合智能 AA #1;最會寫+跑模擬程式碼(GPQA 屬飽和帶,差距極小)",
          "why_en": "#1 on AA overall; best at writing+running simulation code (GPQA saturated, tiny gaps)",
          "meta": "5/28 · 寫/跑模擬",
          "meta_en": "5/28 · build/run simulations"
        }
      ],
      "monthly": {
        "note": null,
        "note_en": null,
        "items": [
          {
            "rank": 1,
            "name": "GPT-6 Astra",
            "version": "GPT-6 Astra",
            "vendor": "OpenAI",
            "vendor_en": "OpenAI",
            "date": "9/3",
            "date_en": null,
            "isNew": true,
            "overlap": null,
            "overlap_en": null,
            "why": "作為新一代旗艦模型，在LiveBench Reasoning和ARC-AGI-2等推理基準測試中表現卓越，是數據推理和複雜模擬的強大基礎。",
            "why_en": "As a new generation flagship model, it demonstrates excellent performance in reasoning benchmarks like LiveBench Reasoning and ARC-AGI-2, serving as a powerful foundation for data reasoning and complex simulations."
          },
          {
            "rank": 2,
            "name": "Claude Opus 5.5",
            "version": "Opus 5.5",
            "vendor": "Anthropic",
            "vendor_en": "Anthropic",
            "date": "9/22",
            "date_en": null,
            "isNew": true,
            "overlap": null,
            "overlap_en": null,
            "why": "專為長時間運行的代理編碼和知識工作設計，具有100萬上下文窗口和自適應思考能力，非常適合複雜數據分析和代理模擬任務。",
            "why_en": "Designed for long-running agentic coding and knowledge work, featuring a 1 million token context window and adaptive thinking, making it ideal for complex data analysis and agentic simulation tasks."
          },
          {
            "rank": 3,
            "name": "Claude Fable 5.1",
            "version": "Fable 5.1",
            "vendor": "Anthropic",
            "vendor_en": "Anthropic",
            "date": "9/1",
            "date_en": null,
            "isNew": true,
            "overlap": "整體 #3",
            "overlap_en": "Overall #3",
            "why": "作為Fable 5的更新版本，是Anthropic用於要求嚴格的推理和長期代理工作的最新模型，在事實準確性方面表現出色。",
            "why_en": "An updated version of Fable 5, it is Anthropic's latest model for demanding reasoning and long-horizon agentic work, excelling in factual accuracy."
          },
          {
            "rank": 4,
            "name": "Claude Sonnet 5.5",
            "version": "Sonnet 5.5",
            "vendor": "Anthropic",
            "vendor_en": "Anthropic",
            "date": "9/28",
            "date_en": null,
            "isNew": true,
            "overlap": null,
            "overlap_en": null,
            "why": "提供強大的推理和編碼能力，並且可在claude.ai上免費使用，使其成為數據推理任務的高度可訪問選項。",
            "why_en": "Offers strong reasoning and coding capabilities, and is available for free on claude.ai, making it a highly accessible option for data reasoning tasks."
          },
          {
            "rank": 5,
            "name": "TypeSafe AI Jev",
            "version": "Jev",
            "vendor": "TypeSafe AI",
            "vendor_en": "TypeSafe AI",
            "date": "10/1",
            "date_en": null,
            "isNew": true,
            "overlap": null,
            "overlap_en": null,
            "why": "本月最新發佈，是一個專注於決策的模型，直接返回類型化的機率而非文本，非常適合數據模擬和機率建模。",
            "why_en": "Newly released this month, it is a decision-only model that returns typed probabilities instead of text, making it highly suitable for data simulation and probability modeling."
          }
        ]
      }
    },
    {
      "id": 4,
      "icon": "🖼️",
      "name": "創建圖片美術",
      "name_en": "Image & Art Generation",
      "subtitle": "文生圖質量 · 依 LMArena 文生圖 Arena",
      "subtitle_en": "Text-to-image quality · by LMArena T2I Arena",
      "overall": [
        {
          "rank": 1,
          "name": "GPT Image 2",
          "vendor": "OpenAI",
          "vendor_en": "OpenAI",
          "score": "Arena #1",
          "why": "LMArena 文生圖 Arena 第一,分數大幅領先",
          "why_en": "#1 on LMArena text-to-image Arena by a wide margin",
          "meta": "OpenAI 現役旗艦圖像",
          "meta_en": "OpenAI current flagship image model"
        },
        {
          "rank": 2,
          "name": "Muse Image",
          "vendor": "Meta",
          "vendor_en": "Meta",
          "score": "Arena #2",
          "why": "Meta 官方稱 Arena #2(文生圖+編修);人像/場景強",
          "why_en": "Meta claims #2 on Arena (t2i + editing); strong portraits/scenes",
          "meta": "7/8 發佈 · Meta Superintelligence Labs",
          "meta_en": "Launched 7/8 · Meta Superintelligence Labs"
        },
        {
          "rank": 3,
          "name": "Reve 2.0",
          "vendor": "Reve AI",
          "vendor_en": "Reve AI",
          "score": "Arena #3",
          "why": "版面優先、4K 高解析;獨立 Reve AI(Palo Alto)",
          "why_en": "Layout-first 4K; from indie Reve AI (Palo Alto)",
          "meta": "6/3 發佈",
          "meta_en": "Released 6/3"
        },
        {
          "rank": 4,
          "name": "Gemini 3.1 Flash Image",
          "vendor": "Google",
          "vendor_en": "Google",
          "score": "Arena #4",
          "why": "Google 快速高質圖像(Nano-Banana 後繼)",
          "why_en": "Google fast high-quality image (Nano-Banana successor)",
          "meta": "preview",
          "meta_en": "preview"
        },
        {
          "rank": 5,
          "name": "MAI-Image 2.5",
          "vendor": "Microsoft",
          "vendor_en": "Microsoft",
          "score": "Arena #5",
          "why": "微軟 MAI 自研圖像模型",
          "why_en": "Microsoft's in-house MAI image model",
          "meta": "preview · 5/26 入榜",
          "meta_en": "preview · on leaderboard since 5/26"
        }
      ],
      "monthly": {
        "note": "本月(2026 年 10 月)僅有 1 個新發佈項目,其餘以近期(2026 年 9 月至 8 月)發佈補足。",
        "note_en": "Only 1 new release in October 2026; the remaining items are filled with recent releases (September to August 2026).",
        "items": [
          {
            "rank": 1,
            "name": "ChatGPT Images 2.5",
            "version": "Flare / Sunburst",
            "vendor": "OpenAI",
            "vendor_en": "OpenAI",
            "date": "9/8",
            "date_en": null,
            "isNew": false,
            "overlap": "整體 #1",
            "overlap_en": "Overall #1",
            "why": "OpenAI 旗艦圖片生成模型的重大更新,提供更快的生成速度、更自然的圖像品質及精準編輯功能。",
            "why_en": "A significant update to OpenAI's flagship image generation model, offering faster generation, more natural image quality, and precise editing features."
          },
          {
            "rank": 2,
            "name": "Google Pics",
            "version": "GA Release",
            "vendor": "Google",
            "vendor_en": "Google",
            "date": "9/1",
            "date_en": null,
            "isNew": false,
            "overlap": "整體 #4",
            "overlap_en": "Overall #4",
            "why": "Google Workspace 中全新的 AI 圖片生成與精準編輯工具,深度整合工作流程並支援物件級別編輯。",
            "why_en": "A new AI image generation and precise editing tool within Google Workspace, deeply integrated into workflows and supporting object-level editing."
          },
          {
            "rank": 3,
            "name": "MixVio AI Unified Creative Workspace",
            "version": "GA Release",
            "vendor": "MixVio AI",
            "vendor_en": "MixVio AI",
            "date": "10/1",
            "date_en": null,
            "isNew": true,
            "overlap": null,
            "overlap_en": null,
            "why": "一個全新的統一創意工作空間,將圖片、影片和音訊生成與編輯無縫整合,提升多模態內容創作效率。",
            "why_en": "A new unified creative workspace that seamlessly integrates image, video, and audio generation and editing, enhancing multimodal content creation efficiency."
          },
          {
            "rank": 4,
            "name": "Grok Image Generation",
            "version": "Aurora",
            "vendor": "SpaceXAI",
            "vendor_en": "SpaceXAI",
            "date": "8/21",
            "date_en": null,
            "isNew": false,
            "overlap": null,
            "overlap_en": null,
            "why": "SpaceXAI 推出的全新自動迴歸圖片生成模型,擴展了 Grok 在 X 平台上的多模態能力。",
            "why_en": "A new autoregressive image generation model launched by SpaceXAI, expanding Grok's multimodal capabilities on the X platform."
          },
          {
            "rank": 5,
            "name": "Qwen-Image 3.0",
            "version": "GA Release",
            "vendor": "Alibaba",
            "vendor_en": "Alibaba",
            "date": "8/5",
            "date_en": null,
            "isNew": false,
            "overlap": null,
            "overlap_en": null,
            "why": "阿里巴巴的旗艦圖片模型,以強大的文字渲染能力和多語言支援為特色,適用於複雜的排版和海報設計。",
            "why_en": "Alibaba's flagship image model, featuring strong text rendering capabilities and multilingual support, suitable for complex typography and poster design."
          }
        ]
      }
    },
    {
      "id": 5,
      "icon": "🎬",
      "name": "創建遊戲影片",
      "name_en": "Game / Stylized Video",
      "subtitle": "風格化 / 動畫向 Video",
      "subtitle_en": "Stylized / animated video",
      "overall": [
        {
          "rank": 1,
          "name": "Kling 3.0 / 3.0 Omni",
          "vendor": "快手 Kuaishou",
          "vendor_en": "Kuaishou",
          "score": "運鏡標竿",
          "score_en": "motion benchmark",
          "why": "電影級運鏡,東亞/動漫風訓練深,多角色對嘴",
          "why_en": "Cinematic motion; deep East-Asian/anime training; multi-character lip-sync",
          "meta": "2/4 · 付費 ~$0.10/s",
          "meta_en": "2/4 · paid ~$0.10/s"
        },
        {
          "rank": 2,
          "name": "Dreamina Seedance 2.0",
          "vendor": "ByteDance",
          "vendor_en": "ByteDance",
          "score": "多鏡頭敘事",
          "score_en": "multi-shot story",
          "why": "多鏡頭風格化敘事,動漫 I2V 強,原生音訊",
          "why_en": "Multi-shot stylized storytelling, strong anime I2V, native audio",
          "meta": "2/12 · CapCut/fal",
          "meta_en": "2/12 · CapCut/fal"
        },
        {
          "rank": 3,
          "name": "HappyHorse-1.0",
          "vendor": "Alibaba",
          "vendor_en": "Alibaba",
          "score": "50+ 風格",
          "score_en": "50+ styles",
          "why": "盲測 Arena 第一,50+ 風格,音訊同步",
          "why_en": "#1 in blind-test Arena, 50+ styles, audio sync",
          "meta": "4/27 · fal API",
          "meta_en": "4/27 · fal API"
        },
        {
          "rank": 4,
          "name": "PixVerse V6",
          "vendor": "PixVerse",
          "vendor_en": "PixVerse",
          "score": "動漫專精",
          "score_en": "anime-tuned",
          "why": "專為動漫/遊戲風格打造,20+ 運鏡控制",
          "why_en": "Built for anime/game styles, 20+ camera controls",
          "meta": "3/30 · 免費增值+API",
          "meta_en": "3/30 · freemium + API"
        },
        {
          "rank": 5,
          "name": "Pika 2.x",
          "vendor": "Pika",
          "vendor_en": "Pika",
          "score": "社群快剪",
          "score_en": "fast social",
          "why": "Pikaffects/Pikaswaps,快速社群/動漫短片",
          "why_en": "Pikaffects/Pikaswaps; quick social/anime clips",
          "meta": "2025–26 · 免費增值",
          "meta_en": "2025–26 · freemium"
        }
      ],
      "monthly": {
        "note": "本月(2026 年 10 月)無足夠的正式發佈項目，故列表以最近 30-60 天內發佈的項目補足。/Insufficient officially released items for October 2026, so the list is supplemented with items released within the last 30-60 days.",
        "note_en": null,
        "items": [
          {
            "rank": 1,
            "name": "Bandicam AI Studio",
            "version": null,
            "vendor": "Bandicam Company",
            "vendor_en": "Bandicam Company",
            "date": "9/29",
            "date_en": null,
            "isNew": true,
            "overlap": null,
            "overlap_en": null,
            "why": "於本月下旬正式發佈,提供一站式 AI 影片生成功能,其『AI 導演』可將簡單文字概念轉化為多場景影片。/Officially launched late this month, offering an all-in-one AI video generation platform with an 'AI Director' to transform simple text ideas into multi-scene videos.",
            "why_en": "Officially launched late this month, offering an all-in-one AI video generation platform with an 'AI Director' to transform simple text ideas into multi-scene videos."
          },
          {
            "rank": 2,
            "name": "Dreamina Seedance",
            "version": "2.5",
            "vendor": "字節跳動 (ByteDance)",
            "vendor_en": "ByteDance",
            "date": "7/31 (全球推廣於 9 月)",
            "date_en": "July 31 (global rollout in Sep)",
            "isNew": false,
            "overlap": null,
            "overlap_en": null,
            "why": "雖於 7 月底發佈,但其全球推廣與功能更新在 9 月持續進行,提供長達 30 秒的影片生成、多模態參考及更精準的編輯控制。/Although released in late July, its global rollout and feature updates continued in September, offering up to 30-second video generation, multimodal references, and more precise editing controls.",
            "why_en": "Although released in late July, its global rollout and feature updates continued in September, offering up to 30-second video generation, multimodal references, and more precise editing controls."
          }
        ]
      }
    },
    {
      "id": 6,
      "icon": "🎥",
      "name": "創建真人影片",
      "name_en": "Live-Action Video",
      "subtitle": "寫實 / 真人向 Video",
      "subtitle_en": "Realistic / live-action video",
      "overall": [
        {
          "rank": 1,
          "name": "Kling 3.0 Pro (1080p)",
          "vendor": "快手 Kuaishou",
          "vendor_en": "Kuaishou",
          "score": "原生 4K",
          "score_en": "native 4K",
          "why": "原生 4K,對白/寫實強",
          "why_en": "Native 4K; strong dialogue/realism",
          "meta": "2 月 · 付費",
          "meta_en": "Feb · paid"
        },
        {
          "rank": 2,
          "name": "Dreamina Seedance 2.0 (720p)",
          "vendor": "ByteDance",
          "vendor_en": "ByteDance",
          "score": "含音訊·敘事強",
          "score_en": "Audio + strong narrative",
          "why": "Arena 榜首級(T2V & I2V),寫實 + 同步音訊",
          "why_en": "Top of Arena (T2V & I2V); realism + synced audio",
          "meta": "2/12 · CapCut/fal",
          "meta_en": "2/12 · CapCut/fal"
        },
        {
          "rank": 3,
          "name": "Google Veo 3.1 (+Fast)",
          "vendor": "Google",
          "vendor_en": "Google",
          "score": "提示遵從佳",
          "score_en": "best adherence",
          "why": "提示遵從最佳,原生音訊,4K,最穩",
          "why_en": "Best prompt adherence, native audio, 4K; most reliable",
          "meta": "~1 月 · Flow/Gemini",
          "meta_en": "~Jan · Flow/Gemini"
        },
        {
          "rank": 4,
          "name": "HappyHorse-1.0",
          "vendor": "Alibaba",
          "vendor_en": "Alibaba",
          "score": "盲測前段",
          "score_en": "Top blind-test tier",
          "why": "無音訊 Arena #1,1080p 寫實,低 WER 對嘴",
          "why_en": "#1 no-audio Arena; 1080p realism, low-WER lip-sync",
          "meta": "4/27 · fal API",
          "meta_en": "4/27 · fal API"
        },
        {
          "rank": 5,
          "name": "Runway Gen-4.5",
          "vendor": "Runway",
          "vendor_en": "Runway",
          "score": "專業運鏡",
          "score_en": "Pro control",
          "why": "專業製片首選:運鏡、結構化提示、可控性與後製銜接強",
          "why_en": "Pro film choice: camera moves, structured prompting, editability",
          "meta": "2026 · 專業工作流首選",
          "meta_en": "2026 · go-to pro workflow"
        }
      ],
      "monthly": {
        "note": "本月(2026 年 10 月)僅有 1 個新發佈項目,其餘 4 個為近 30-60 天內發佈的最新版本。",
        "note_en": "Only 1 new release in October 2026; the remaining 4 are the latest versions released within the last 30-60 days.",
        "items": [
          {
            "rank": 1,
            "name": "Kling 4.0",
            "version": "4.0",
            "vendor": "快手",
            "vendor_en": "Kuaishou",
            "date": "10/2026",
            "date_en": "Oct 2026",
            "isNew": true,
            "overlap": null,
            "overlap_en": null,
            "why": "本月正式發佈的最新一代模型,專注於提升寫實度、控制力和專業級影片品質,改進了視覺真實感、攝影機控制、唇形同步和敘事能力。",
            "why_en": "The newest generation model officially released this month, focusing on enhanced realism, control, and professional-grade video quality, with improvements in visual fidelity, camera control, lip sync, and narrative capabilities."
          },
          {
            "rank": 2,
            "name": "Gemini Omni Flash",
            "version": "Omni 1.1 Flash",
            "vendor": "Google",
            "vendor_en": "Google",
            "date": "8/2026",
            "date_en": "Aug 2026",
            "isNew": false,
            "overlap": null,
            "overlap_en": null,
            "why": "於 2026 年 8 月正式發佈,是盲測排行榜上的新品質領導者,能生成高達 4K 解析度並帶有同步音訊的影片。",
            "why_en": "Generally available in August 2026, it is a new quality leader on blind-vote leaderboards for text-to-video with audio, generating up to 4K video with synchronized audio."
          },
          {
            "rank": 3,
            "name": "Alibaba Wan 3.0",
            "version": "3.0",
            "vendor": "阿里巴巴",
            "vendor_en": "Alibaba",
            "date": "8/2026",
            "date_en": "Aug 2026",
            "isNew": false,
            "overlap": null,
            "overlap_en": null,
            "why": "於 2026 年 8 月正式發佈,以具競爭力的價格提供帶音訊的長影片片段,在音訊排行榜上名列前茅。",
            "why_en": "Generally available in August 2026, it offers long clips with sound at a competitive price, ranking high on audio leaderboards."
          },
          {
            "rank": 4,
            "name": "Seedance 2.5",
            "version": "2.5",
            "vendor": "字節跳動",
            "vendor_en": "ByteDance",
            "date": "7/31/2026",
            "date_en": "Jul 31, 2026",
            "isNew": false,
            "overlap": null,
            "overlap_en": null,
            "why": "於 2026 年 7 月 31 日發佈,是實現高擬真 4K 影片製作的重大升級,支援更長的時長、參考驅動控制和免重拍編輯。",
            "why_en": "Released on July 31, 2026, it is a major upgrade towards high-fidelity 4K video production, supporting longer duration, reference-driven control, and reshoot-free editing."
          },
          {
            "rank": 5,
            "name": "MiniMax H3",
            "version": "H3 (Hailuo 3.0)",
            "vendor": "MiniMax",
            "vendor_en": "MiniMax",
            "date": "7/31/2026",
            "date_en": "Jul 31, 2026",
            "isNew": false,
            "overlap": null,
            "overlap_en": null,
            "why": "於 2026 年 7 月 31 日發佈,能單次生成帶同步音訊的原生 2K 影片,時長可達 15 秒,並具備全方位參考控制。",
            "why_en": "Released on July 31, 2026, it generates native 2K video with synchronized audio in a single pass, up to 15 seconds, with omni-reference control."
          }
        ]
      }
    },
    {
      "id": 7,
      "icon": "🧊",
      "name": "創建遊戲模組",
      "name_en": "3D Asset Generation",
      "subtitle": "3D 模型生成 · 例如 Meshy",
      "subtitle_en": "3D model generation · e.g. Meshy",
      "overall": [
        {
          "rank": 1,
          "name": "Meshy-6",
          "vendor": "Meshy",
          "vendor_en": "Meshy",
          "score": "盲測勝出",
          "score_en": "won blind test",
          "why": "最均衡全流程(text/img→3D、PBR、低面數、匯出);盲測勝 Tripo",
          "why_en": "Most balanced full pipeline (text/img→3D, PBR, low-poly, export); beat Tripo in blind tests",
          "meta": "1/18 · 免費增值 ~$20/mo",
          "meta_en": "1/18 · freemium ~$20/mo"
        },
        {
          "rank": 2,
          "name": "Tripo P1.0 (+H3.1)",
          "vendor": "Tripo AI",
          "vendor_en": "Tripo AI",
          "score": "~2 秒出模",
          "score_en": "~2s mesh",
          "why": "原生 3D 擴散,~2 秒出引擎可用網格",
          "why_en": "Native 3D diffusion; engine-ready meshes in ~2s",
          "meta": "3/9 GDC · ~$12/mo",
          "meta_en": "3/9 GDC · ~$12/mo"
        },
        {
          "rank": 3,
          "name": "Rodin Gen-2",
          "vendor": "Hyper3D",
          "vendor_en": "Hyper3D",
          "score": "寫實最高",
          "score_en": "top realism",
          "why": "表面寫實度最高,四邊面 + 3D 修補",
          "why_en": "Highest surface realism; quad mesh + 3D inpainting",
          "meta": "2/9 · ~$30/mo",
          "meta_en": "2/9 · ~$30/mo"
        },
        {
          "rank": 4,
          "name": "Hunyuan3D 3.0",
          "vendor": "騰訊 Tencent",
          "vendor_en": "Tencent",
          "score": "開源自架",
          "score_en": "open-source",
          "why": "免費/可自架,開源線,1536³ 解析度",
          "why_en": "Free/self-hostable, open-source line, 1536³ resolution",
          "meta": "2025/9 · 免費自架",
          "meta_en": "2025/9 · free self-host"
        },
        {
          "rank": 5,
          "name": "TRELLIS 2",
          "vendor": "Microsoft(開源)",
          "vendor_en": "Microsoft (open-source)",
          "score": "開源材質佳",
          "score_en": "open texture",
          "why": "開源材質品質最佳(Gaussian-splat)",
          "why_en": "Best open-source texture quality (Gaussian-splat)",
          "meta": "2025–26 · 開源免費",
          "meta_en": "2025–26 · open-source, free"
        }
      ],
      "monthly": {
        "note": "本月(2026 年 10 月)未發現正式發佈的新模型，故列表由近期 (2026 年 8-9 月) 的正式發佈補足。",
        "note_en": "No new GA models were found for this month (October 2026), so the list is supplemented with recent GA releases from August-September 2026.",
        "items": [
          {
            "rank": 1,
            "name": "Tripo",
            "version": "P2.0",
            "vendor": "Tripo AI",
            "vendor_en": "Tripo AI",
            "date": "9/22",
            "date_en": null,
            "isNew": false,
            "overlap": "整體 #2",
            "overlap_en": "Overall #2",
            "why": "業界首創原生四邊形網格生成，大幅提升遊戲資產的生產就緒性。",
            "why_en": "Industry-first native quad mesh generation, significantly enhancing production readiness for game assets."
          },
          {
            "rank": 2,
            "name": "Meshy",
            "version": "7.1",
            "vendor": "Meshy AI",
            "vendor_en": "Meshy AI",
            "date": "9/10",
            "date_en": null,
            "isNew": false,
            "overlap": "整體 #1",
            "overlap_en": "Overall #1",
            "why": "推出 Ultra 4K 模式，將圖像轉 3D 的幾何解析度提升至 4096³。",
            "why_en": "Introduced Ultra 4K mode, boosting image-to-3D geometry resolution to 4096³."
          },
          {
            "rank": 3,
            "name": "3D AI Studio",
            "version": "Platform Update",
            "vendor": "3D AI Studio",
            "vendor_en": "3D AI Studio",
            "date": "9/15",
            "date_en": null,
            "isNew": false,
            "overlap": null,
            "overlap_en": null,
            "why": "作為整合多個領先 AI 模型的一站式平台，提供完整的遊戲資產生成管線。",
            "why_en": "As a one-stop platform integrating multiple leading AI models, it offers a complete pipeline for game asset generation."
          },
          {
            "rank": 4,
            "name": "AssetForge AI",
            "version": "1.0",
            "vendor": "itch.io",
            "vendor_en": "itch.io",
            "date": "8/5",
            "date_en": null,
            "isNew": false,
            "overlap": null,
            "overlap_en": null,
            "why": "全新發佈的獨立 AI 工具，專注於生成高品質的遊戲內容，包括角色、武器等。",
            "why_en": "Newly released standalone AI tool focused on generating high-quality game content, including characters and weapons."
          },
          {
            "rank": 5,
            "name": "SelfCAD AI Assistant",
            "version": "N/A (Feature update)",
            "vendor": "SelfCAD",
            "vendor_en": "SelfCAD",
            "date": "8/25",
            "date_en": null,
            "isNew": false,
            "overlap": null,
            "overlap_en": null,
            "why": "新增 AI 助理功能，支援自然語言描述生成 3D 模型，提升設計效率。",
            "why_en": "Added AI Assistant feature, supporting natural language description for 3D model generation, enhancing design efficiency."
          }
        ]
      }
    },
    {
      "id": 8,
      "icon": "🦴",
      "name": "遊戲模組 Rigging",
      "name_en": "Game Asset Rigging",
      "subtitle": "綁骨 / 可動 · 例如 Anything World",
      "subtitle_en": "Rigging / animation-ready · e.g. Anything World",
      "overall": [
        {
          "rank": 1,
          "name": "Meshy-6 Auto-Rig + Animate",
          "vendor": "Meshy",
          "vendor_en": "Meshy",
          "score": "<30s·500+動作",
          "score_en": "<30s · 500+ anims",
          "why": "一站式,<30 秒自動綁人形/四足,500+ 預設動作",
          "why_en": "One-stop; auto-rigs humanoids/quadrupeds in <30s, 500+ preset animations",
          "meta": "2025–26 · ~$20/mo",
          "meta_en": "2025–26 · ~$20/mo"
        },
        {
          "rank": 2,
          "name": "Autodesk Flow Studio AI Rigging",
          "vendor": "Autodesk",
          "vendor_en": "Autodesk",
          "score": "免費綁骨",
          "score_en": "free rigging",
          "why": "AI 自動關節 + AI 動捕,匯出 Maya/Blender/UE",
          "why_en": "AI auto-joints + AI mocap; export to Maya/Blender/UE",
          "meta": "4/28 · 全層免費預覽",
          "meta_en": "4/28 · free preview, all tiers"
        },
        {
          "rank": 3,
          "name": "Tripo Auto-Rigging (Uni-Rig)",
          "vendor": "Tripo AI",
          "vendor_en": "Tripo AI",
          "score": "骨架+動畫",
          "score_en": "rig + anim",
          "why": "自動骨架 + 權重 + 自動動畫,風格化佳",
          "why_en": "Auto-skeleton + weights + auto-animation; great for stylized",
          "meta": "2025–26 · ~$12/mo",
          "meta_en": "2025–26 · ~$12/mo"
        },
        {
          "rank": 4,
          "name": "Cascadeur 2026.1",
          "vendor": "Nekki",
          "vendor_en": "Nekki",
          "score": "AI 物理動作",
          "score_en": "AI physics",
          "why": "AI AutoPosing/Physics + AI Root Motion,UE Live Link",
          "why_en": "AI AutoPosing/Physics + AI Root Motion; UE Live Link",
          "meta": "4/9 · 免費層+訂閱",
          "meta_en": "4/9 · free tier + subscription"
        },
        {
          "rank": 5,
          "name": "Anything World — Animate Anything",
          "vendor": "Anything World",
          "vendor_en": "Anything World",
          "score": "任意網格",
          "score_en": "any mesh",
          "why": "任意靜態網格 AI 綁定(尤其動物/生物)",
          "why_en": "AI-rig any static mesh (esp. animals/creatures)",
          "meta": "Live · 免費起步+API",
          "meta_en": "Live · free start + API"
        }
      ],
      "monthly": {
        "note": "本月(2026 年 10 月)無足夠新發佈,故以近期(近 30-60 天)發佈補足。Anything World - Animate Anything 因本月無直接新發佈,但其核心自動綁骨與動畫功能在 2026 年持續受到關注與正面評價,故列入近期榜單。",
        "note_en": "Insufficient new releases in October 2026, so the list is supplemented with recent releases (last 30-60 days). Anything World - Animate Anything is included in the recent list because, while there are no direct new releases this month, its core auto-rigging and animation features continue to receive attention and positive reviews in 2026.",
        "items": [
          {
            "rank": 1,
            "name": "Tripo P2.0 (含改進綁骨功能)",
            "version": "P2.0",
            "vendor": "Tripo AI",
            "vendor_en": "Tripo AI",
            "date": "9/21",
            "date_en": "Sep 21",
            "isNew": true,
            "overlap": "整體 #3",
            "overlap_en": "Overall #3",
            "why": "正式發佈的 3D 原生基礎模型,透過原生四邊形網格生成,顯著提升了角色綁骨與動畫的生產管線效率。",
            "why_en": "Officially released 3D-native foundation model that significantly enhances character rigging and animation pipeline efficiency through native quad topology generation."
          },
          {
            "rank": 2,
            "name": "Meshy 7 (增強自動綁骨與動畫)",
            "version": "7",
            "vendor": "Meshy",
            "vendor_en": "Meshy",
            "date": "8/10",
            "date_en": "Aug 10",
            "isNew": true,
            "overlap": "整體 #1",
            "overlap_en": "Overall #1",
            "why": "Meshy 7 於 8 月發佈,並在 9 月持續受到討論,其自動綁骨功能新增四足動物支援,並擴充至超過 600 種動畫預設。",
            "why_en": "Meshy 7 was released in August and continued to be discussed in September, with its auto-rigging feature adding quadruped support and expanding to over 600 animation presets."
          },
          {
            "rank": 3,
            "name": "Autodesk Flow Studio AI Rigging",
            "version": "N/A",
            "vendor": "Autodesk",
            "vendor_en": "Autodesk",
            "date": "9/28",
            "date_en": "Sep 28",
            "isNew": true,
            "overlap": "整體 #2",
            "overlap_en": "Overall #2",
            "why": "Autodesk Flow Studio 持續更新並在 9 月的定價指南中強調其 AI 自動綁骨功能,可快速將 3D 模型轉化為可動畫角色。",
            "why_en": "Autodesk Flow Studio continues to update and highlighted its AI auto-rigging capabilities in its September pricing guide, enabling quick transformation of 3D models into animatable characters."
          },
          {
            "rank": 4,
            "name": "Cascadeur 2026.2",
            "version": "2026.2",
            "vendor": "Nekki",
            "vendor_en": "Nekki",
            "date": "8/6",
            "date_en": "Aug 6",
            "isNew": true,
            "overlap": "整體 #4",
            "overlap_en": "Overall #4",
            "why": "此版本增強了 AI 中間幀生成、動作生成及四足動物的自動擺姿功能,提升了物理基礎動畫的效率與品質。",
            "why_en": "This version enhances AI inbetweening, motion generation, and AutoPosing for quadrupeds, improving the efficiency and quality of physics-based animation."
          },
          {
            "rank": 5,
            "name": "Anything World — Animate Anything",
            "version": "N/A",
            "vendor": "Anything World",
            "vendor_en": "Anything World",
            "date": "2026",
            "date_en": "2026",
            "isNew": false,
            "overlap": "整體 #5",
            "overlap_en": "Overall #5",
            "why": "其核心 AI 自動綁骨與動畫平台在 2026 年持續受到業界關注與正面評價,提供快速將靜態模型轉化為可動畫角色的能力。",
            "why_en": "Its core AI auto-rigging and animation platform continues to receive industry attention and positive reviews in 2026, offering the ability to quickly transform static models into animatable characters."
          }
        ]
      }
    },
    {
      "id": 9,
      "icon": "🔊",
      "name": "創建聲音特效",
      "name_en": "Sound Effects & Audio",
      "subtitle": "SFX / 語音 / 音樂 · 例如 ElevenLabs",
      "subtitle_en": "SFX / voice / music · e.g. ElevenLabs",
      "overall": [
        {
          "rank": 1,
          "name": "ElevenLabs SFX v2 + v3 voice",
          "vendor": "ElevenLabs",
          "vendor_en": "ElevenLabs",
          "score": "SFX 龍頭",
          "score_en": "SFX leader",
          "why": "遊戲音訊最全:文字轉 SFX(30s、可無縫循環)+ 頂級語音",
          "why_en": "Most complete game-audio stack: text-to-SFX (30s, seamless loops) + top-tier voice",
          "meta": "SFX 2025/9 · v3 2 月",
          "meta_en": "SFX 2025/9 · v3 Feb"
        },
        {
          "rank": 2,
          "name": "Suno v5",
          "vendor": "Suno",
          "vendor_en": "Suno",
          "score": "音樂 ELO 1293",
          "score_en": "Music ELO 1293",
          "why": "音樂盲測第一(ELO 1293);全曲+人聲質量標竿",
          "why_en": "#1 in music blind tests (ELO 1293); full-song + vocal benchmark",
          "meta": "3/27 · 訂閱制",
          "meta_en": "3/27 · subscription"
        },
        {
          "rank": 3,
          "name": "ElevenLabs Music v2",
          "vendor": "ElevenLabs",
          "vendor_en": "ElevenLabs",
          "score": "商用授權",
          "score_en": "licensed",
          "why": "商用授權清晰,可在曲中嵌 SFX、中途換曲風",
          "why_en": "Clear commercial licensing; embed SFX in tracks, mid-track genre switch",
          "meta": "5/26 · 降價 40–50%",
          "meta_en": "5/26 · 40–50% cheaper"
        },
        {
          "rank": 4,
          "name": "Stable Audio 3",
          "vendor": "Stability AI",
          "vendor_en": "Stability AI",
          "score": "開源·SFX",
          "score_en": "open-source SFX",
          "why": "開源,音樂 + SFX/foley 統一,適合自架 pipeline",
          "why_en": "Open-source; unified music + SFX/foley; great for self-hosted pipelines",
          "meta": "5/20 · 開源權重",
          "meta_en": "5/20 · open weights"
        },
        {
          "rank": 5,
          "name": "Lyria 3 Pro",
          "vendor": "Google DeepMind",
          "vendor_en": "Google DeepMind",
          "score": "3 分鐘長曲",
          "score_en": "3-min tracks",
          "why": "最長 3 分鐘結構化曲目,SynthID 浮水印",
          "why_en": "Up to 3-min structured tracks; SynthID watermark",
          "meta": "3/25 · Gemini/Vertex",
          "meta_en": "3/25 · Gemini/Vertex"
        }
      ],
      "monthly": {
        "note": null,
        "note_en": null,
        "items": [
          {
            "rank": 1,
            "name": "Suno v6",
            "version": "v6 (包含 v6-wild, v6-mini)",
            "vendor": "Suno",
            "vendor_en": "Suno",
            "date": "9/9",
            "date_en": "Sep 9",
            "isNew": true,
            "overlap": "整體 #2",
            "overlap_en": "Overall #2",
            "why": "提供更快、更具表現力、更高品質的音樂生成，並與音樂產業合作。",
            "why_en": "Offers faster, more expressive, higher-quality music generation with industry partnerships."
          },
          {
            "rank": 2,
            "name": "Eleven v4",
            "version": "v4 / v4 Turbo (Text-to-Speech)",
            "vendor": "ElevenLabs",
            "vendor_en": "ElevenLabs",
            "date": "9/28",
            "date_en": "Sep 28",
            "isNew": true,
            "overlap": "整體 #1",
            "overlap_en": "Overall #1",
            "why": "帶來更具情感、多語言的語音合成，並提升即時效能和語音複製能力。",
            "why_en": "Delivers more emotive, multilingual text-to-speech with enhanced real-time performance and voice cloning."
          },
          {
            "rank": 3,
            "name": "Gemini 3.8 Live",
            "version": "3.8 Live (Speech-to-Speech)",
            "vendor": "Google",
            "vendor_en": "Google",
            "date": "9/24",
            "date_en": "Sep 24",
            "isNew": true,
            "overlap": null,
            "overlap_en": null,
            "why": "專為語音代理設計，提供即時推理、流暢對話及視覺語義理解能力。",
            "why_en": "Designed for voice agents, offering real-time reasoning, fluid dialogue, and visual grounding capabilities."
          },
          {
            "rank": 4,
            "name": "Gemini 3.8 Flash TTS",
            "version": "3.8 Flash TTS",
            "vendor": "Google",
            "vendor_en": "Google",
            "date": "9月",
            "date_en": "Sep",
            "isNew": true,
            "overlap": null,
            "overlap_en": null,
            "why": "支援超過 130 種語言的語音合成模型，提供高效能和廣泛應用。",
            "why_en": "A text-to-speech model supporting over 130 languages, offering high performance and broad applicability."
          },
          {
            "rank": 5,
            "name": "MixVio AI Unified Creative Workspace",
            "version": "N/A (平台)",
            "vendor": "MixVio AI",
            "vendor_en": "MixVio AI",
            "date": "10/2",
            "date_en": "Oct 2",
            "isNew": true,
            "overlap": null,
            "overlap_en": null,
            "why": "整合視訊、圖像和音訊生成，簡化多模態內容創作流程，支援原生同步音訊。",
            "why_en": "Integrates video, image, and audio generation, streamlining multimodal content creation workflows with native synchronized audio."
          }
        ]
      }
    },
    {
      "id": 10,
      "icon": "🧩",
      "name": "AI 工具組合 Combo",
      "name_en": "AI Tool Combos",
      "subtitle": "依社群熱度 Top10 · 例如 Claude + Obsidian",
      "subtitle_en": "By popularity, Top 10 · e.g. Claude + Obsidian",
      "overall": [
        {
          "rank": 1,
          "name": "Cursor + Claude Code + GitHub Copilot",
          "vendor": "Anysphere + Anthropic + OpenAI/GitHub",
          "vendor_en": "Anysphere + Anthropic + OpenAI/GitHub",
          "score": "巨量採用",
          "score_en": "huge adoption",
          "why": "主流「出貨」編程組合:IDE agent + 終端 agent 並用;1.8M Copilot 開發者、~半數財星500用 Cursor",
          "why_en": "The dominant 'ship software' coding stack; 1.8M Copilot devs, ~half of Fortune 500 on Cursor",
          "meta": "媒體高曝光",
          "meta_en": "heavy media coverage"
        },
        {
          "rank": 2,
          "name": "Claude Code + GitHub + Vercel",
          "vendor": "Anthropic + GitHub + Vercel",
          "vendor_en": "Anthropic + GitHub + Vercel",
          "score": "廣傳·官方",
          "score_en": "viral · official",
          "why": "prompt→push→自動部署上線;官方 Vercel 外掛(你正在用的)",
          "why_en": "prompt→push→auto-deploy live; official Vercel plugin (the one you use)",
          "meta": "YouTube/媒體廣傳",
          "meta_en": "widely shared"
        },
        {
          "rank": 3,
          "name": "n8n + LLM (OpenAI/Claude) + MCP",
          "vendor": "n8n",
          "vendor_en": "n8n",
          "score": "GitHub 191k★",
          "score_en": "GitHub 191k★",
          "why": "可自架的視覺化 AI agent/工作流自動化;191k stars、$2.5B 估值",
          "why_en": "Self-hosted visual AI-agent/workflow automation; 191k stars, $2.5B valuation",
          "meta": "230k+ users",
          "meta_en": "230k+ users"
        },
        {
          "rank": 4,
          "name": "ComfyUI + Flux / Suno / ElevenLabs",
          "vendor": "ComfyUI + community",
          "vendor_en": "ComfyUI + community",
          "score": "GitHub ~110k★",
          "score_en": "GitHub ~110k★",
          "why": "節點式創作流水線:圖→影→語音/音樂同一畫布;ElevenLabs 官方節點",
          "why_en": "Node-graph creative pipeline: image→video→voice/music; official ElevenLabs node",
          "meta": "~106k+ stars",
          "meta_en": "~106k+ stars"
        },
        {
          "rank": 5,
          "name": "ChatGPT / Claude + Notion",
          "vendor": "OpenAI/Anthropic + Notion",
          "vendor_en": "OpenAI/Anthropic + Notion",
          "score": "高討論",
          "score_en": "highly discussed",
          "why": "LLM 在你的團隊 wiki/筆記上推理;最常被搜的生產力配對",
          "why_en": "LLM reasoning over your team wiki/notes; most-searched productivity pairing",
          "meta": "Reddit/媒體高討論",
          "meta_en": "Reddit/media buzz"
        },
        {
          "rank": 6,
          "name": "Microsoft Copilot (Agent 365) + Claude + GPT",
          "vendor": "Microsoft + Anthropic + OpenAI",
          "vendor_en": "Microsoft + Anthropic + OpenAI",
          "score": "企業高曝光",
          "score_en": "enterprise buzz",
          "why": "企業多模型調度:「GPT 起草、Claude 審查」",
          "why_en": "Enterprise multi-model orchestration: 'GPT drafts, Claude reviews'",
          "meta": "Agent 365 GA 5/1",
          "meta_en": "Agent 365 GA May 1"
        },
        {
          "rank": 7,
          "name": "Claude + Obsidian",
          "vendor": "Anthropic + Obsidian",
          "vendor_en": "Anthropic + Obsidian",
          "score": "YouTube 廣傳",
          "score_en": "viral on YouTube",
          "why": "AI 第二大腦:Claude 讀寫你的本地筆記(你同事推的那個)",
          "why_en": "AI second brain: Claude reads/builds on your local notes (your colleague's pick)",
          "meta": "XDA/多篇教學",
          "meta_en": "XDA + many guides"
        },
        {
          "rank": 8,
          "name": "Perplexity + NotebookLM + Claude",
          "vendor": "Perplexity + Google + Anthropic",
          "vendor_en": "Perplexity + Google + Anthropic",
          "score": "研究熱門",
          "score_en": "popular research",
          "why": "研究組合:有來源的網搜 → 來源紮根 → 深入推理",
          "why_en": "Research stack: cited web search → source grounding → deep reasoning",
          "meta": "媒體高討論",
          "meta_en": "heavy coverage"
        },
        {
          "rank": 9,
          "name": "Midjourney + Runway/Veo + ElevenLabs + Suno + Descript",
          "vendor": "多家 multi-vendor",
          "vendor_en": "multi-vendor",
          "score": "製片廣傳",
          "score_en": "popular for video",
          "why": "端到端 AI 影片:腳本→分鏡→畫面→配音→配樂→剪輯",
          "why_en": "End-to-end AI video: script→storyboard→footage→VO→music→edit",
          "meta": "標準製片流程",
          "meta_en": "standard production stack"
        },
        {
          "rank": 10,
          "name": "Raycast AI + Claude / Perplexity / NotebookLM",
          "vendor": "Raycast + 多家",
          "vendor_en": "Raycast + multi-vendor",
          "score": "中討論",
          "score_en": "modest buzz",
          "why": "Mac 啟動器當各 AI 工具的黏合層(剪貼簿、片語、MCP)",
          "why_en": "Mac launcher as the glue across AI tools (clipboard, snippets, MCP)",
          "meta": "Substack 報導",
          "meta_en": "Substack feature"
        }
      ],
      "monthly": {
        "note": null,
        "note_en": null,
        "items": [
          {
            "rank": 1,
            "name": "Microsoft Copilot Agent 365 Enterprise Suite",
            "version": "GA (enhanced Claude Fable 5 & GPT-5.5 Turbo integration)",
            "vendor": "微軟",
            "vendor_en": "Microsoft",
            "date": "9/25",
            "date_en": null,
            "isNew": true,
            "overlap": "整體 #6",
            "overlap_en": "Overall #6",
            "why": "企業級Copilot正式發佈,深度整合Claude Fable 5與GPT-5.5 Turbo,實現多代理協同工作。",
            "why_en": "Enterprise-grade Copilot officially released, deeply integrating Claude Fable 5 and GPT-5.5 Turbo for multi-agent collaborative workflows."
          },
          {
            "rank": 2,
            "name": "n8n Enterprise Connectors",
            "version": "GA (Claude Fable 5 & Gemini 3.5 Flash)",
            "vendor": "n8n",
            "vendor_en": "n8n",
            "date": "9/20",
            "date_en": null,
            "isNew": true,
            "overlap": "整體 #3",
            "overlap_en": "Overall #3",
            "why": "n8n發佈企業級連接器,支援Claude Fable 5與Gemini 3.5 Flash,大幅擴展自動化AI工作流能力。",
            "why_en": "n8n released enterprise connectors supporting Claude Fable 5 and Gemini 3.5 Flash, significantly expanding AI automation workflow capabilities."
          },
          {
            "rank": 3,
            "name": "ComfyUI Integration Hub",
            "version": "v1.0 GA (Flux 2.0, Suno v4, ElevenLabs Pro)",
            "vendor": "ComfyUI",
            "vendor_en": "ComfyUI",
            "date": "9/18",
            "date_en": null,
            "isNew": true,
            "overlap": "整體 #4",
            "overlap_en": "Overall #4",
            "why": "ComfyUI推出官方整合中心,簡化Flux 2.0、Suno v4、ElevenLabs Pro等生成式AI模型的串接。",
            "why_en": "ComfyUI launched its official Integration Hub, simplifying connections to generative AI models like Flux 2.0, Suno v4, and ElevenLabs Pro."
          },
          {
            "rank": 4,
            "name": "Raycast AI Pro",
            "version": "GA (Advanced LLM Routing & Custom Agent Builder)",
            "vendor": "Raycast",
            "vendor_en": "Raycast",
            "date": "9/15",
            "date_en": null,
            "isNew": true,
            "overlap": "整體 #10",
            "overlap_en": "Overall #10",
            "why": "Raycast AI Pro正式發佈,提供進階LLM路由和自訂代理建構器,強化多模型協作。",
            "why_en": "Raycast AI Pro officially launched, offering advanced LLM routing and a custom agent builder for enhanced multi-model collaboration."
          },
          {
            "rank": 5,
            "name": "Cursor IDE",
            "version": "v0.20 GA (Deep Claude Fable 5 integration)",
            "vendor": "Cursor",
            "vendor_en": "Cursor",
            "date": "9/12",
            "date_en": null,
            "isNew": true,
            "overlap": "整體 #1",
            "overlap_en": "Overall #1",
            "why": "Cursor IDE v0.20正式發佈,與Claude Fable 5深度整合,提供無與倫比的AI輔助開發體驗。",
            "why_en": "Cursor IDE v0.20 officially released, with deep integration with Claude Fable 5 for unparalleled AI-assisted development."
          },
          {
            "rank": 6,
            "name": "Vercel AI SDK",
            "version": "3.0 GA (Enhanced Multi-Model Deployment)",
            "vendor": "Vercel",
            "vendor_en": "Vercel",
            "date": "9/10",
            "date_en": null,
            "isNew": true,
            "overlap": "整體 #2",
            "overlap_en": "Overall #2",
            "why": "Vercel AI SDK 3.0正式發佈,簡化多LLM應用程式在無伺服器功能上的部署。",
            "why_en": "Vercel AI SDK 3.0 officially launched, simplifying multi-LLM application deployment on serverless functions."
          },
          {
            "rank": 7,
            "name": "Obsidian Canvas AI Agent Plugin",
            "version": "v1.0 GA (Claude Sonnet 5 integration)",
            "vendor": "Obsidian",
            "vendor_en": "Obsidian",
            "date": "9/8",
            "date_en": null,
            "isNew": true,
            "overlap": "整體 #7",
            "overlap_en": "Overall #7",
            "why": "Obsidian Canvas AI代理外掛正式發佈,利用Claude Sonnet 5進行智慧知識合成。",
            "why_en": "Obsidian Canvas AI Agent Plugin officially released, leveraging Claude Sonnet 5 for intelligent knowledge synthesis."
          },
          {
            "rank": 8,
            "name": "Perplexity AI Enterprise",
            "version": "GA (NotebookLM API Integration)",
            "vendor": "Perplexity AI",
            "vendor_en": "Perplexity AI",
            "date": "9/5",
            "date_en": null,
            "isNew": true,
            "overlap": "整體 #8",
            "overlap_en": "Overall #8",
            "why": "Perplexity AI企業版正式發佈,提供與NotebookLM API的整合,實現安全私密的文檔分析。",
            "why_en": "Perplexity AI Enterprise officially launched, offering integration with NotebookLM API for secure, private document analysis."
          },
          {
            "rank": 9,
            "name": "Midjourney",
            "version": "v7 GA (Native RunwayML Gen-3 & ElevenLabs Voice AI integration)",
            "vendor": "Midjourney",
            "vendor_en": "Midjourney",
            "date": "9/3",
            "date_en": null,
            "isNew": true,
            "overlap": "整體 #9",
            "overlap_en": "Overall #9",
            "why": "Midjourney v7正式發佈,內建RunwayML Gen-3和ElevenLabs Voice AI整合,強化多模態創作。",
            "why_en": "Midjourney v7 officially released, featuring native RunwayML Gen-3 and ElevenLabs Voice AI integrations for enhanced multimodal creation."
          },
          {
            "rank": 10,
            "name": "ChatGPT Enterprise Custom GPTs for Notion",
            "version": "GA (Official Notion Integration)",
            "vendor": "OpenAI",
            "vendor_en": "OpenAI",
            "date": "9/1",
            "date_en": null,
            "isNew": true,
            "overlap": "整體 #5",
            "overlap_en": "Overall #5",
            "why": "ChatGPT企業版推出針對Notion的官方Custom GPTs,簡化團隊工作流程與內容創作。",
            "why_en": "ChatGPT Enterprise launched official Custom GPTs for Notion, streamlining team workflows and content creation."
          }
        ]
      }
    }
  ]
};
