/* 自動產生 — ①讀 curated.json、②每日 Gemini 研究;勿手動編輯(改①請編 curated.json) */
window.DIGEST = {
  "updatedAt": "2026-08-16T00:08:51+08:00",
  "updatedDateLabel": "2026 年 8 月 16 日",
  "month": "2026 年 8 月",
  "month_en": "August 2026",
  "dataConfidence": "①整體=手工校正權威版;②本月最新由 gemini-2.5-flash+Google 搜尋於 2026/08/16 自動更新",
  "dataConfidence_en": "① curated (hand-verified); ② this-month auto-updated by gemini-2.5-flash+Google Search on 2026/08/16",
  "changesToday": [
    "Grok 4.6 (8/12) — 綜合 AI MODEL 排名",
    "SoonLab 2.0 (8/15) — 創建遊戲的助手",
    "Gemini 3.7 Flash (8/13) — 創建遊戲的助手",
    "GeoPT 模型 (8/13) — 創建數據模擬器 & 數據推理",
    "Prime Agent (8/6) — 創建數據模擬器 & 數據推理",
    "Grok Imagine Image 2.0 (8/8) — 創建圖片美術"
  ],
  "changesToday_en": [
    "Grok 4.6 (8/12) — Overall AI Model Ranking",
    "SoonLab 2.0 (8/15) — Game-Building Assistants",
    "Gemini 3.7 Flash (8/13) — Game-Building Assistants",
    "GeoPT 模型 (8/13) — Data Simulators & Reasoning",
    "Prime Agent (8/6) — Data Simulators & Reasoning",
    "Grok Imagine Image 2.0 (8/8) — Image & Art Generation"
  ],
  "notes": [
    "中立聲明:①整體榜以第三方獨立榜為準(綜合=AA 指數、編程=SWE-bench、推理=GPQA、圖片=LMArena Arena)、只列已發佈模型、經人工校正,非本 AI 或任何廠商觀點。",
    "①整體=手工校正的權威版(穩定);②本月最新=每日免費自動研究(僅供速覽,偶有出入請點源覆核)。",
    "排名每天會動:AA 為 72 小時滾動、LMArena Elo 每天浮動,第 2~5 名常在誤差內。"
  ],
  "notes_en": [
    "Neutrality: ① follows independent third-party leaderboards (General=AA Index, Coding=SWE-bench, Reasoning=GPQA, Image=LMArena Arena), GA models only, human-verified — not this AI's or any vendor's view.",
    "① = hand-curated authoritative (stable); ② = free auto-research daily (quick reference; verify against sources).",
    "Rankings shift daily: AA is a 72-hour rolling average and LMArena Elo moves; ranks 2–5 are often within noise."
  ],
  "categories": [
    {
      "id": 1,
      "icon": "🧠",
      "name": "綜合 AI MODEL 排名",
      "name_en": "Overall AI Model Ranking",
      "subtitle": "依 AA 智能指數 · Gemini / Claude / GPT",
      "subtitle_en": "By AA Intelligence Index · Gemini / Claude / GPT",
      "overall": [
        {
          "rank": 1,
          "name": "Claude Opus 5",
          "vendor": "Anthropic",
          "vendor_en": "Anthropic",
          "score": "AA 61",
          "score_en": "AA 61",
          "why": "AA 智能指數世界第一(61, v4.1);Claude Max 新預設,價僅 Fable 半價",
          "why_en": "#1 in the world on AA Intelligence Index (61, v4.1); new Claude Max default at half Fable's price",
          "meta": "7/24 發佈 · $5/$25 · Max 預設",
          "meta_en": "Released 7/24 · $5/$25 · Max default"
        },
        {
          "rank": 2,
          "name": "Claude Fable 5",
          "vendor": "Anthropic",
          "vendor_en": "Anthropic",
          "score": "AA 60",
          "why": "AA 智能指數 60,僅次於 Opus 5;公開可用最強之一",
          "why_en": "AA Index 60, just behind Opus 5; among the strongest available",
          "meta": "7/1 全球返場 · 曾因出口管制暫停 18 天",
          "meta_en": "Returned globally 7/1 · was suspended 18 days",
          "score_en": "AA 60"
        },
        {
          "rank": 3,
          "name": "GPT-5.6 Sol",
          "vendor": "OpenAI",
          "vendor_en": "OpenAI",
          "score": "AA 59",
          "score_en": "AA 59",
          "why": "AA 智能指數 #2(59);OpenAI 新一代旗艦",
          "why_en": "#2 on AA Intelligence Index (59); OpenAI's new flagship",
          "meta": "7/9 發佈",
          "meta_en": "Released 7/9"
        },
        {
          "rank": 4,
          "name": "Kimi K3",
          "vendor": "Moonshot AI 月之暗面",
          "vendor_en": "Moonshot AI",
          "score": "AA 57",
          "score_en": "AA 57",
          "why": "AA 智能指數 57.1,首度躋身前段",
          "why_en": "AA Intelligence Index 57.1; breaks into the top tier",
          "meta": "2026-07 新進榜",
          "meta_en": "New on the board, July 2026"
        },
        {
          "rank": 5,
          "name": "Claude Opus 4.8",
          "vendor": "Anthropic",
          "vendor_en": "Anthropic",
          "score": "AA 56",
          "why": "AA 智能指數 #1(61.4);獨立第三方確認",
          "why_en": "#1 on AA Intelligence Index (61.4); independently confirmed",
          "meta": "5/28 發佈 · API $5/$25",
          "meta_en": "Released 5/28 · API $5/$25",
          "score_en": "AA 56"
        }
      ],
      "monthly": {
        "note": "本月(2026 年 8 月)有 4 個新發佈的旗艦級通用 AI 模型，不足 5 個，故補足一個最近期(2026 年 7 月)發佈且在 8 月仍被評為最佳的模型。",
        "note_en": "There are 4 new flagship general AI models released this month (August 2026). As there are fewer than 5, one recent model (July 2026) that is still ranked as a top performer in August has been included to complete the list.",
        "items": [
          {
            "rank": 1,
            "name": "Claude Opus 5",
            "version": "5",
            "vendor": "Anthropic",
            "vendor_en": "Anthropic",
            "date": "7/24",
            "date_en": "Jul 24",
            "isNew": false,
            "overlap": "整體 #1",
            "overlap_en": "Overall #1",
            "why": "在 2026 年 8 月的評測中仍被視為綜合表現最佳的模型，尤其在編碼和代理能力方面表現突出。",
            "why_en": "Still considered the best overall performer in August 2026 evaluations, excelling particularly in coding and agentic capabilities."
          },
          {
            "rank": 2,
            "name": "Grok 4.6",
            "version": "4.6",
            "vendor": "xAI",
            "vendor_en": "xAI",
            "date": "8/12",
            "date_en": "Aug 12",
            "isNew": true,
            "overlap": null,
            "overlap_en": null,
            "why": "Grok 4.5 的重大更新，在 8 月評測中智能表現與 GPT-5.6 Sol 持平，且在代理任務中效率更高。",
            "why_en": "A significant update to Grok 4.5, matching GPT-5.6 Sol in intelligence in August evaluations and demonstrating higher efficiency in agentic tasks."
          },
          {
            "rank": 3,
            "name": "DeepSeek-V4-Pro-0813",
            "version": "V4-Pro-0813",
            "vendor": "DeepSeek",
            "vendor_en": "DeepSeek",
            "date": "8/13",
            "date_en": "Aug 13",
            "isNew": true,
            "overlap": null,
            "overlap_en": null,
            "why": "本月最新發佈的前沿 AI 模型，展現了強大的綜合能力。",
            "why_en": "The latest frontier AI model released this month, demonstrating strong general capabilities."
          },
          {
            "rank": 4,
            "name": "GLM-5.3",
            "version": "5.3",
            "vendor": "Z.ai",
            "vendor_en": "Z.ai",
            "date": "8/14",
            "date_en": "Aug 14",
            "isNew": true,
            "overlap": null,
            "overlap_en": null,
            "why": "在 GLM-5.2 基礎上通過後訓練提升了複雜編碼和長週期任務處理能力。",
            "why_en": "Improved complex coding and long-horizon task processing capabilities through post-training on the GLM-5.2 base."
          },
          {
            "rank": 5,
            "name": "Qwen3.8 Max",
            "version": "3.8 Max",
            "vendor": "Alibaba",
            "vendor_en": "Alibaba",
            "date": "8/2-3",
            "date_en": "Aug 2-3",
            "isNew": true,
            "overlap": null,
            "overlap_en": null,
            "why": "阿里巴巴發佈的 MoE 模型，在長週期代理編碼耐力方面表現最強。",
            "why_en": "Alibaba's MoE model, noted for its strongest performance in long-horizon agentic coding endurance."
          }
        ]
      }
    },
    {
      "id": 2,
      "icon": "🎮",
      "name": "創建遊戲的助手",
      "name_en": "Game-Building Assistants",
      "subtitle": "AI 編程(依 SWE-bench) · 你的 Three.js + Claude Code + GitHub + Vercel pipeline",
      "subtitle_en": "AI coding (by SWE-bench) · your Three.js + Claude Code + GitHub + Vercel pipeline",
      "overall": [
        {
          "rank": 1,
          "name": "Claude Opus 5",
          "vendor": "Anthropic",
          "vendor_en": "Anthropic",
          "score": "AA 編程#1",
          "score_en": "AA Coding #1",
          "why": "領先 AA 編程指數(SWE-Atlas-QnA 最高);搭 Claude Code 最強",
          "why_en": "#1 on AA Coding Index (top SWE-Atlas-QnA); strongest paired with Claude Code",
          "meta": "7/24 · Max 預設",
          "meta_en": "7/24 · Max default"
        },
        {
          "rank": 2,
          "name": "Claude Fable 5",
          "vendor": "Anthropic",
          "vendor_en": "Anthropic",
          "score": "SWE 95%",
          "score_en": "SWE 95%",
          "why": "SWE-bench Verified 95%;編程次於 Opus 5(公開可用第二強)",
          "why_en": "SWE-bench Verified 95%; #2 coding behind Opus 5",
          "meta": "7/1 返場 · Mythos 級",
          "meta_en": "Returned 7/1 · Mythos-class"
        },
        {
          "rank": 3,
          "name": "GPT-5.5",
          "vendor": "OpenAI",
          "vendor_en": "OpenAI",
          "score": "SWE 88.7%",
          "why": "公開 SWE-bench Verified 第一(88.7%);Codex/Copilot 內建",
          "why_en": "#1 on public SWE-bench Verified (88.7%); built into Codex/Copilot",
          "meta": "4/23 · ChatGPT/API",
          "meta_en": "4/23 · ChatGPT/API"
        },
        {
          "rank": 4,
          "name": "Claude Opus 4.8",
          "vendor": "Anthropic",
          "vendor_en": "Anthropic",
          "score": "SWE 88.6%",
          "why": "SWE 88.6%(幾乎並列第一);WebDev Arena 第一,最適合你的 Three.js 前端",
          "why_en": "SWE 88.6% (near-tied for #1); #1 on WebDev Arena — best for your Three.js frontend",
          "meta": "5/28 · Claude Code 原生",
          "meta_en": "5/28 · native to Claude Code"
        },
        {
          "rank": 5,
          "name": "Claude Opus 4.7",
          "vendor": "Anthropic",
          "vendor_en": "Anthropic",
          "score": "SWE 87.6%",
          "why": "前代旗艦,SWE 87.6%,WebDev 仍強",
          "why_en": "Prior flagship, SWE 87.6%, still strong on WebDev",
          "meta": "~4 月 · Claude API",
          "meta_en": "~Apr · Claude API"
        }
      ],
      "monthly": {
        "note": null,
        "note_en": null,
        "items": [
          {
            "rank": 1,
            "name": "SoonLab 2.0",
            "version": "2.0",
            "vendor": "SoonLab",
            "vendor_en": "SoonLab",
            "date": "8/15",
            "date_en": null,
            "isNew": true,
            "overlap": null,
            "overlap_en": null,
            "why": "首個支援從自然語言生成可玩 3D 遊戲的 AI 平台，大幅簡化遊戲創作流程。",
            "why_en": "The first AI platform to support generating playable 3D games from natural language, significantly simplifying the game creation process."
          },
          {
            "rank": 2,
            "name": "Gemini 3.7 Flash",
            "version": "3.7 Flash",
            "vendor": "Google",
            "vendor_en": "Google",
            "date": "8/13",
            "date_en": null,
            "isNew": true,
            "overlap": null,
            "overlap_en": null,
            "why": "Google 最智能的工作模型，在軟體工程、網頁開發和代理工作流程方面有顯著改進，尤其在 WebDev Arena 表現優異。",
            "why_en": "Google's most intelligent workhorse model, with significant improvements in software engineering, web development, and agentic workflows, performing exceptionally well in WebDev Arena."
          },
          {
            "rank": 3,
            "name": "Meta Muse Code",
            "version": "Muse Spark 1.2",
            "vendor": "Meta",
            "vendor_en": "Meta",
            "date": "8月",
            "date_en": "August",
            "isNew": true,
            "overlap": null,
            "overlap_en": null,
            "why": "Meta 首個 AI 編程代理，專為複雜的軟體工程任務設計，可並行執行多個子代理。",
            "why_en": "Meta's first AI coding agent, designed for complex software engineering tasks and capable of executing multiple sub-agents concurrently."
          },
          {
            "rank": 4,
            "name": "Cursor Cloud Agents (Builds)",
            "version": "Cloud Agents Start 3x Faster with Builds",
            "vendor": "Cursor",
            "vendor_en": "Cursor",
            "date": "8/13",
            "date_en": null,
            "isNew": true,
            "overlap": null,
            "overlap_en": null,
            "why": "Cursor IDE 針對其雲端代理的重大效率提升，使開發環境啟動速度提高三倍，加速程式碼庫級別的編輯和自動化任務。",
            "why_en": "A significant efficiency enhancement for Cursor IDE's Cloud Agents, enabling development environments to start 3x faster, accelerating codebase-wide editing and autonomous tasks."
          },
          {
            "rank": 5,
            "name": "Prime Agent",
            "version": "N/A",
            "vendor": "Prime Intellect",
            "vendor_en": "Prime Intellect",
            "date": "8/5",
            "date_en": null,
            "isNew": true,
            "overlap": null,
            "overlap_en": null,
            "why": "一個自我改進的編程代理框架，採用遞歸語言模型和持續訓練機制，適用於長週期任務。",
            "why_en": "A self-improving coding agent framework utilizing Recursive Language Models and Continual Harness for long-horizon tasks."
          }
        ]
      }
    },
    {
      "id": 3,
      "icon": "📊",
      "name": "創建數據模擬器 & 數據推理",
      "name_en": "Data Simulators & Reasoning",
      "subtitle": "依 GPQA Diamond · 對應你的「深海奪寶」RTP 沙盤",
      "subtitle_en": "By GPQA Diamond · for your 'Abyss Treasury' RTP sandbox",
      "overall": [
        {
          "rank": 1,
          "name": "Gemini 3.1 Pro",
          "vendor": "Google",
          "vendor_en": "Google",
          "score": "GPQA 94.1%",
          "why": "GPQA Diamond 第一(94.1%);大 context 適合分析大量模擬結果",
          "why_en": "#1 on GPQA Diamond (94.1%); big context for analyzing large result sets",
          "meta": "~Q1 · AI Studio/Vertex",
          "meta_en": "~Q1 · AI Studio/Vertex"
        },
        {
          "rank": 2,
          "name": "Claude Opus 5",
          "vendor": "Anthropic",
          "vendor_en": "Anthropic",
          "score": "AA 61",
          "score_en": "AA 61",
          "why": "AA 綜合智能世界第一(61);推理屬頂段",
          "why_en": "#1 overall on AA (61); top-tier reasoning",
          "meta": "7/24 · Max 預設",
          "meta_en": "7/24 · Max default"
        },
        {
          "rank": 3,
          "name": "Claude Fable 5",
          "vendor": "Anthropic",
          "vendor_en": "Anthropic",
          "score": "AA 60",
          "score_en": "AA 60",
          "why": "綜合智能第一;推理屬頂段(GPQA 前段)",
          "why_en": "#1 overall intelligence; top-tier reasoning (GPQA leading pack)",
          "meta": "7/1 返場 · Mythos 級",
          "meta_en": "Returned 7/1 · Mythos-class"
        },
        {
          "rank": 4,
          "name": "GPT-5.5 (xhigh)",
          "vendor": "OpenAI",
          "vendor_en": "OpenAI",
          "score": "GPQA 93.5%",
          "why": "GPQA 93.5%;純機率數學最強",
          "why_en": "GPQA 93.5%; best at pure probability math",
          "meta": "4/23 · 機率推導",
          "meta_en": "4/23 · probability reasoning"
        },
        {
          "rank": 5,
          "name": "Claude Opus 4.8 (max)",
          "vendor": "Anthropic",
          "vendor_en": "Anthropic",
          "score": "AA 56",
          "score_en": "AA 56",
          "why": "綜合智能 AA #1;最會寫+跑模擬程式碼(GPQA 屬飽和帶,差距極小)",
          "why_en": "#1 on AA overall; best at writing+running simulation code (GPQA saturated, tiny gaps)",
          "meta": "5/28 · 寫/跑模擬",
          "meta_en": "5/28 · build/run simulations"
        }
      ],
      "monthly": {
        "note": null,
        "note_en": null,
        "items": [
          {
            "rank": 1,
            "name": "GeoPT 模型",
            "version": "N/A",
            "vendor": "麻省理工學院 (MIT)",
            "vendor_en": "Massachusetts Institute of Technology (MIT)",
            "date": "8/13",
            "date_en": "Aug 13",
            "isNew": true,
            "overlap": null,
            "overlap_en": null,
            "why": "該模型透過虛擬重演日常機械互動來學習物理學，從而實現更高效的真實世界場景模擬，直接針對數據模擬範疇。",
            "why_en": "This model learns physics through virtual reenactments of everyday mechanical interactions, enabling more efficient simulations of real-world scenarios, directly addressing the data simulation category."
          },
          {
            "rank": 2,
            "name": "Prime Agent",
            "version": "N/A (開源編碼代理)",
            "vendor": "Prime Intellect",
            "vendor_en": "Prime Intellect",
            "date": "8/6",
            "date_en": "Aug 6",
            "isNew": true,
            "overlap": null,
            "overlap_en": null,
            "why": "作為一個開源編碼代理，它在持久性 Python 環境中運行，顯著提升 AI 模型處理長期、複雜任務的智能，對數據推理和模擬至關重要。",
            "why_en": "As an open-source coding agent, it runs in a persistent Python environment, significantly enhancing AI models' intelligence for long, complex tasks, crucial for data reasoning and simulation."
          },
          {
            "rank": 3,
            "name": "Nemotron 3.5 Lightning 和 NeMo Switchyard",
            "version": "N/A",
            "vendor": "NVIDIA",
            "vendor_en": "NVIDIA",
            "date": "8/11",
            "date_en": "Aug 11",
            "isNew": true,
            "overlap": null,
            "overlap_en": null,
            "why": "NVIDIA 發布這些工具旨在提供更快、更智能、更高效的代理式 AI，直接支持數據推理和複雜任務的自動化。",
            "why_en": "NVIDIA released these tools to deliver faster, smarter, and more efficient agentic AI, directly supporting data reasoning and automation of complex tasks."
          },
          {
            "rank": 4,
            "name": "Azure Content Understanding (GA refresh)",
            "version": "CU 1.0 API",
            "vendor": "Microsoft",
            "vendor_en": "Microsoft",
            "date": "8/12",
            "date_en": "Aug 12",
            "isNew": true,
            "overlap": null,
            "overlap_en": null,
            "why": "此 GA 更新為 Azure Content Understanding API 帶來了代理式文件推理功能，用於更複雜的提取場景，提升了數據推理能力。",
            "why_en": "This GA refresh to the Azure Content Understanding API introduces agentic document reasoning for more complex extraction scenarios, enhancing data reasoning capabilities."
          },
          {
            "rank": 5,
            "name": "OfficeQA Pro V2",
            "version": "基準測試",
            "vendor": "Databricks",
            "vendor_en": "Databricks",
            "date": "8/6",
            "date_en": "Aug 6",
            "isNew": true,
            "overlap": null,
            "overlap_en": null,
            "why": "作為企業級基礎推理的新基準測試，它評估了 AI 代理在處理企業數據方面的性能，推動了數據推理模型和代理的發展。",
            "why_en": "As a new benchmark for enterprise grounded reasoning, it evaluates the performance of AI agents in handling enterprise data, advancing data reasoning models and agents."
          }
        ]
      }
    },
    {
      "id": 4,
      "icon": "🖼️",
      "name": "創建圖片美術",
      "name_en": "Image & Art Generation",
      "subtitle": "文生圖質量 · 依 LMArena 文生圖 Arena",
      "subtitle_en": "Text-to-image quality · by LMArena T2I Arena",
      "overall": [
        {
          "rank": 1,
          "name": "GPT Image 2",
          "vendor": "OpenAI",
          "vendor_en": "OpenAI",
          "score": "Arena #1",
          "why": "LMArena 文生圖 Arena 第一,分數大幅領先",
          "why_en": "#1 on LMArena text-to-image Arena by a wide margin",
          "meta": "OpenAI 現役旗艦圖像",
          "meta_en": "OpenAI current flagship image model"
        },
        {
          "rank": 2,
          "name": "Muse Image",
          "vendor": "Meta",
          "vendor_en": "Meta",
          "score": "Arena #2",
          "why": "Meta 官方稱 Arena #2(文生圖+編修);人像/場景強",
          "why_en": "Meta claims #2 on Arena (t2i + editing); strong portraits/scenes",
          "meta": "7/8 發佈 · Meta Superintelligence Labs",
          "meta_en": "Launched 7/8 · Meta Superintelligence Labs"
        },
        {
          "rank": 3,
          "name": "Reve 2.0",
          "vendor": "Reve AI",
          "vendor_en": "Reve AI",
          "score": "Arena #3",
          "why": "版面優先、4K 高解析;獨立 Reve AI(Palo Alto)",
          "why_en": "Layout-first 4K; from indie Reve AI (Palo Alto)",
          "meta": "6/3 發佈",
          "meta_en": "Released 6/3"
        },
        {
          "rank": 4,
          "name": "Gemini 3.1 Flash Image",
          "vendor": "Google",
          "vendor_en": "Google",
          "score": "Arena #4",
          "why": "Google 快速高質圖像(Nano-Banana 後繼)",
          "why_en": "Google fast high-quality image (Nano-Banana successor)",
          "meta": "preview",
          "meta_en": "preview"
        },
        {
          "rank": 5,
          "name": "MAI-Image 2.5",
          "vendor": "Microsoft",
          "vendor_en": "Microsoft",
          "score": "Arena #5",
          "why": "微軟 MAI 自研圖像模型",
          "why_en": "Microsoft's in-house MAI image model",
          "meta": "preview · 5/26 入榜",
          "meta_en": "preview · on leaderboard since 5/26"
        }
      ],
      "monthly": {
        "note": "本月(2026 年 8 月)發佈之正式版圖片生成模型不足 5 個，故以近期(近 30-60 天)發佈的正式版模型補足。",
        "note_en": "Less than 5 officially released image generation models were launched this month (August 2026), so recent (within 30-60 days) GA models have been included to complete the list.",
        "items": [
          {
            "rank": 1,
            "name": "Grok Imagine Image 2.0",
            "version": "2.0",
            "vendor": "xAI",
            "vendor_en": "xAI",
            "date": "8/8",
            "date_en": null,
            "isNew": true,
            "overlap": null,
            "overlap_en": null,
            "why": "xAI 推出的專用圖片生成模型，在視覺內容創作方面展現強大能力。",
            "why_en": "A dedicated image generation model from xAI, demonstrating strong capabilities in visual content creation."
          },
          {
            "rank": 2,
            "name": "Muse Spark 1.2",
            "version": "1.2",
            "vendor": "Meta",
            "vendor_en": "Meta",
            "date": "8/6",
            "date_en": null,
            "isNew": true,
            "overlap": null,
            "overlap_en": null,
            "why": "Meta 最新多模態模型的迭代，具備先進的即時圖片生成能力。",
            "why_en": "Meta's latest iteration of multimodal models, featuring advanced real-time image generation capabilities."
          },
          {
            "rank": 3,
            "name": "Qwen Image 3.0 Pro",
            "version": "3.0 Pro",
            "vendor": "Alibaba",
            "vendor_en": "Alibaba",
            "date": "8/5",
            "date_en": null,
            "isNew": true,
            "overlap": null,
            "overlap_en": null,
            "why": "阿里巴巴推出的專業級圖片生成模型，為多樣化的藝術需求提供增強的品質和功能。",
            "why_en": "Alibaba's professional-grade image generation model, offering enhanced quality and features for diverse artistic needs."
          },
          {
            "rank": 4,
            "name": "Qwen Image 3.0",
            "version": "3.0",
            "vendor": "Alibaba",
            "vendor_en": "Alibaba",
            "date": "8/5",
            "date_en": null,
            "isNew": true,
            "overlap": null,
            "overlap_en": null,
            "why": "阿里巴巴推出的穩健圖片生成模型，為一般創意應用提供高品質輸出。",
            "why_en": "A robust image generation model from Alibaba, providing high-quality outputs for general creative applications."
          },
          {
            "rank": 5,
            "name": "Gemini 3.1 Flash Lite Image",
            "version": "3.1 Flash Lite Image",
            "vendor": "Google",
            "vendor_en": "Google",
            "date": "6/30",
            "date_en": null,
            "isNew": false,
            "overlap": null,
            "overlap_en": null,
            "why": "針對超低延遲和成本效益高的圖片生成與編輯進行優化，適用於高吞吐量自動化。",
            "why_en": "Optimized for ultra-low latency and cost-effective image generation and editing, suitable for high-volume automation."
          }
        ]
      }
    },
    {
      "id": 5,
      "icon": "🎬",
      "name": "創建遊戲影片",
      "name_en": "Game / Stylized Video",
      "subtitle": "風格化 / 動畫向 Video",
      "subtitle_en": "Stylized / animated video",
      "overall": [
        {
          "rank": 1,
          "name": "Kling 3.0 / 3.0 Omni",
          "vendor": "快手 Kuaishou",
          "vendor_en": "Kuaishou",
          "score": "運鏡標竿",
          "score_en": "motion benchmark",
          "why": "電影級運鏡,東亞/動漫風訓練深,多角色對嘴",
          "why_en": "Cinematic motion; deep East-Asian/anime training; multi-character lip-sync",
          "meta": "2/4 · 付費 ~$0.10/s",
          "meta_en": "2/4 · paid ~$0.10/s"
        },
        {
          "rank": 2,
          "name": "Dreamina Seedance 2.0",
          "vendor": "ByteDance",
          "vendor_en": "ByteDance",
          "score": "多鏡頭敘事",
          "score_en": "multi-shot story",
          "why": "多鏡頭風格化敘事,動漫 I2V 強,原生音訊",
          "why_en": "Multi-shot stylized storytelling, strong anime I2V, native audio",
          "meta": "2/12 · CapCut/fal",
          "meta_en": "2/12 · CapCut/fal"
        },
        {
          "rank": 3,
          "name": "HappyHorse-1.0",
          "vendor": "Alibaba",
          "vendor_en": "Alibaba",
          "score": "50+ 風格",
          "score_en": "50+ styles",
          "why": "盲測 Arena 第一,50+ 風格,音訊同步",
          "why_en": "#1 in blind-test Arena, 50+ styles, audio sync",
          "meta": "4/27 · fal API",
          "meta_en": "4/27 · fal API"
        },
        {
          "rank": 4,
          "name": "PixVerse V6",
          "vendor": "PixVerse",
          "vendor_en": "PixVerse",
          "score": "動漫專精",
          "score_en": "anime-tuned",
          "why": "專為動漫/遊戲風格打造,20+ 運鏡控制",
          "why_en": "Built for anime/game styles, 20+ camera controls",
          "meta": "3/30 · 免費增值+API",
          "meta_en": "3/30 · freemium + API"
        },
        {
          "rank": 5,
          "name": "Pika 2.x",
          "vendor": "Pika",
          "vendor_en": "Pika",
          "score": "社群快剪",
          "score_en": "fast social",
          "why": "Pikaffects/Pikaswaps,快速社群/動漫短片",
          "why_en": "Pikaffects/Pikaswaps; quick social/anime clips",
          "meta": "2025–26 · 免費增值",
          "meta_en": "2025–26 · freemium"
        }
      ],
      "monthly": {
        "note": "本月 (2026 年 8 月) 僅有 3 個新發佈,其餘 2 個為最近期 (2026 年 6 月) 發佈以補足數量。",
        "note_en": "Only 3 new releases were found for this month (August 2026); the remaining 2 are recent releases (June 2026) to complete the list.",
        "items": [
          {
            "rank": 1,
            "name": "Seedance 2.5",
            "version": "2.5",
            "vendor": "Pippit (字節跳動)",
            "vendor_en": "Pippit (ByteDance)",
            "date": "8/10",
            "date_en": null,
            "isNew": true,
            "overlap": "整體 #2",
            "overlap_en": "Overall #2",
            "why": "作為頂級模型的重大更新,支援 30 秒 4K 影片生成及擴展的電影級控制,非常適用於遊戲影片創作。",
            "why_en": "A significant update to a top-tier model, supporting 30-second 4K video generation and expanded cinematic controls, highly suitable for game video creation."
          },
          {
            "rank": 2,
            "name": "LTX-2.5",
            "version": "2.5",
            "vendor": "Lightricks",
            "vendor_en": "Lightricks",
            "date": "8/11",
            "date_en": null,
            "isNew": true,
            "overlap": null,
            "overlap_en": null,
            "why": "開放權重且與 ComfyUI 深度整合,為風格化和遊戲特定內容創作提供極高的靈活性和控制力。",
            "why_en": "Open-weights and deep integration with ComfyUI offer immense flexibility and control for stylized and game-specific content creation."
          },
          {
            "rank": 3,
            "name": "FLUX 3 Video",
            "version": "3",
            "vendor": "Black Forest Labs",
            "vendor_en": "Black Forest Labs",
            "date": "8/4",
            "date_en": null,
            "isNew": true,
            "overlap": null,
            "overlap_en": null,
            "why": "本月新發佈的通用模型,支援長達 20 秒的高清影片生成及原生音訊,具備多模態能力。",
            "why_en": "A new general availability model this month, supporting up to 20-second HD video generation with native audio and multimodal capabilities."
          },
          {
            "rank": 4,
            "name": "Kling 3.0 Turbo",
            "version": "3.0 Turbo",
            "vendor": "Kuaishou (快手)",
            "vendor_en": "Kuaishou",
            "date": "6/17",
            "date_en": null,
            "isNew": false,
            "overlap": "整體 #1",
            "overlap_en": "Overall #1",
            "why": "Kling 3.0 系列中新推出的優化版本,專注於速度和成本效益,並顯著改善了唇形同步,對角色驅動的動畫遊戲影片至關重要。",
            "why_en": "A newly launched optimized variant within the Kling 3.0 series, focusing on speed and cost-efficiency with significantly improved lip-sync, crucial for character-driven animated game videos."
          },
          {
            "rank": 5,
            "name": "HappyHorse 1.1",
            "version": "1.1",
            "vendor": "Alibaba (阿里巴巴)",
            "vendor_en": "Alibaba",
            "date": "6/23",
            "date_en": null,
            "isNew": false,
            "overlap": "整體 #3",
            "overlap_en": "Overall #3",
            "why": "HappyHorse 模型的更新版本,強化了音訊-影片生成能力,對於包含對話的電影級遊戲影片很重要。",
            "why_en": "An updated version of the HappyHorse model, enhancing audio-video generation capabilities, important for cinematic game videos with dialogue."
          }
        ]
      }
    },
    {
      "id": 6,
      "icon": "🎥",
      "name": "創建真人影片",
      "name_en": "Live-Action Video",
      "subtitle": "寫實 / 真人向 Video",
      "subtitle_en": "Realistic / live-action video",
      "overall": [
        {
          "rank": 1,
          "name": "Kling 3.0 Pro (1080p)",
          "vendor": "快手 Kuaishou",
          "vendor_en": "Kuaishou",
          "score": "原生 4K",
          "score_en": "native 4K",
          "why": "原生 4K,對白/寫實強",
          "why_en": "Native 4K; strong dialogue/realism",
          "meta": "2 月 · 付費",
          "meta_en": "Feb · paid"
        },
        {
          "rank": 2,
          "name": "Dreamina Seedance 2.0 (720p)",
          "vendor": "ByteDance",
          "vendor_en": "ByteDance",
          "score": "含音訊·敘事強",
          "score_en": "Audio + strong narrative",
          "why": "Arena 榜首級(T2V & I2V),寫實 + 同步音訊",
          "why_en": "Top of Arena (T2V & I2V); realism + synced audio",
          "meta": "2/12 · CapCut/fal",
          "meta_en": "2/12 · CapCut/fal"
        },
        {
          "rank": 3,
          "name": "Google Veo 3.1 (+Fast)",
          "vendor": "Google",
          "vendor_en": "Google",
          "score": "提示遵從佳",
          "score_en": "best adherence",
          "why": "提示遵從最佳,原生音訊,4K,最穩",
          "why_en": "Best prompt adherence, native audio, 4K; most reliable",
          "meta": "~1 月 · Flow/Gemini",
          "meta_en": "~Jan · Flow/Gemini"
        },
        {
          "rank": 4,
          "name": "HappyHorse-1.0",
          "vendor": "Alibaba",
          "vendor_en": "Alibaba",
          "score": "盲測前段",
          "score_en": "Top blind-test tier",
          "why": "無音訊 Arena #1,1080p 寫實,低 WER 對嘴",
          "why_en": "#1 no-audio Arena; 1080p realism, low-WER lip-sync",
          "meta": "4/27 · fal API",
          "meta_en": "4/27 · fal API"
        },
        {
          "rank": 5,
          "name": "Runway Gen-4.5",
          "vendor": "Runway",
          "vendor_en": "Runway",
          "score": "專業運鏡",
          "score_en": "Pro control",
          "why": "專業製片首選:運鏡、結構化提示、可控性與後製銜接強",
          "why_en": "Pro film choice: camera moves, structured prompting, editability",
          "meta": "2026 · 專業工作流首選",
          "meta_en": "2026 · go-to pro workflow"
        }
      ],
      "monthly": {
        "note": "本月(2026 年 8 月)僅有 2 個正式發佈的真人影片生成模型，已用最近期(60 天內)的 3 個補足至 Top 5。",
        "note_en": "Only 2 officially released real-person video generation models were launched this month (August 2026); the remaining 3 spots in the Top 5 have been filled with recent releases (within the last 60 days).",
        "items": [
          {
            "rank": 1,
            "name": "Seedance",
            "version": "2.5",
            "vendor": "字節跳動",
            "vendor_en": "ByteDance",
            "date": "8/7",
            "date_en": null,
            "isNew": true,
            "overlap": null,
            "overlap_en": null,
            "why": "最新版本，支援更長影片(最長 30 秒)、更大的參考預算和可選音訊生成，提供電影級影片輸出。",
            "why_en": "Latest version, supporting longer videos (up to 30 seconds), larger reference budgets, and optional audio generation for cinematic video output."
          },
          {
            "rank": 2,
            "name": "Hailuo",
            "version": "3.0 (MiniMax H3)",
            "vendor": "MiniMax",
            "vendor_en": "MiniMax",
            "date": "8/5",
            "date_en": null,
            "isNew": true,
            "overlap": null,
            "overlap_en": null,
            "why": "提供原生 2K 解析度、單次同步音訊生成、全方位參考控制及指令式編輯功能。",
            "why_en": "Offers native 2K resolution, one-pass synchronized audio generation, omni-reference control, and instruction-based editing capabilities."
          },
          {
            "rank": 3,
            "name": "Kling",
            "version": "3.0 Turbo / Omni",
            "vendor": "快手",
            "vendor_en": "Kuaishou",
            "date": "6/17",
            "date_en": null,
            "isNew": false,
            "overlap": "整體 #1",
            "overlap_en": "Overall #1",
            "why": "Kling 3.0 的重大升級，引入多鏡頭功能、4K 編輯能力及 Omni One 引擎，強化電影級序列生成。",
            "why_en": "A significant upgrade to Kling 3.0, introducing multi-shot features, 4K editing capabilities, and the Omni One engine, enhancing cinematic sequence generation."
          },
          {
            "rank": 4,
            "name": "Seedance",
            "version": "2.0 4K",
            "vendor": "字節跳動",
            "vendor_en": "ByteDance",
            "date": "6/17",
            "date_en": null,
            "isNew": false,
            "overlap": "整體 #2",
            "overlap_en": "Overall #2",
            "why": "Seedance 2.0 的 4K 版本，專為需要超高細節和電影級輸出的創作者設計。",
            "why_en": "A 4K variant of Seedance 2.0, designed for creators requiring ultra-detailed and cinematic output."
          },
          {
            "rank": 5,
            "name": "Seedance",
            "version": "2.0 mini",
            "vendor": "字節跳動",
            "vendor_en": "ByteDance",
            "date": "6/17",
            "date_en": null,
            "isNew": false,
            "overlap": "整體 #2",
            "overlap_en": "Overall #2",
            "why": "Seedance 2.0 的輕量級版本，優化了生成速度和成本效益，同時保持良好品質。",
            "why_en": "A lightweight version of Seedance 2.0, optimized for faster generation and cost-effectiveness while maintaining good quality."
          }
        ]
      }
    },
    {
      "id": 7,
      "icon": "🧊",
      "name": "創建遊戲模組",
      "name_en": "3D Asset Generation",
      "subtitle": "3D 模型生成 · 例如 Meshy",
      "subtitle_en": "3D model generation · e.g. Meshy",
      "overall": [
        {
          "rank": 1,
          "name": "Meshy-6",
          "vendor": "Meshy",
          "vendor_en": "Meshy",
          "score": "盲測勝出",
          "score_en": "won blind test",
          "why": "最均衡全流程(text/img→3D、PBR、低面數、匯出);盲測勝 Tripo",
          "why_en": "Most balanced full pipeline (text/img→3D, PBR, low-poly, export); beat Tripo in blind tests",
          "meta": "1/18 · 免費增值 ~$20/mo",
          "meta_en": "1/18 · freemium ~$20/mo"
        },
        {
          "rank": 2,
          "name": "Tripo P1.0 (+H3.1)",
          "vendor": "Tripo AI",
          "vendor_en": "Tripo AI",
          "score": "~2 秒出模",
          "score_en": "~2s mesh",
          "why": "原生 3D 擴散,~2 秒出引擎可用網格",
          "why_en": "Native 3D diffusion; engine-ready meshes in ~2s",
          "meta": "3/9 GDC · ~$12/mo",
          "meta_en": "3/9 GDC · ~$12/mo"
        },
        {
          "rank": 3,
          "name": "Rodin Gen-2",
          "vendor": "Hyper3D",
          "vendor_en": "Hyper3D",
          "score": "寫實最高",
          "score_en": "top realism",
          "why": "表面寫實度最高,四邊面 + 3D 修補",
          "why_en": "Highest surface realism; quad mesh + 3D inpainting",
          "meta": "2/9 · ~$30/mo",
          "meta_en": "2/9 · ~$30/mo"
        },
        {
          "rank": 4,
          "name": "Hunyuan3D 3.0",
          "vendor": "騰訊 Tencent",
          "vendor_en": "Tencent",
          "score": "開源自架",
          "score_en": "open-source",
          "why": "免費/可自架,開源線,1536³ 解析度",
          "why_en": "Free/self-hostable, open-source line, 1536³ resolution",
          "meta": "2025/9 · 免費自架",
          "meta_en": "2025/9 · free self-host"
        },
        {
          "rank": 5,
          "name": "TRELLIS 2",
          "vendor": "Microsoft(開源)",
          "vendor_en": "Microsoft (open-source)",
          "score": "開源材質佳",
          "score_en": "open texture",
          "why": "開源材質品質最佳(Gaussian-splat)",
          "why_en": "Best open-source texture quality (Gaussian-splat)",
          "meta": "2025–26 · 開源免費",
          "meta_en": "2025–26 · open-source, free"
        }
      ],
      "monthly": {
        "note": "本月 (2026 年 8 月) 無正式發佈 (GA) 的「創建遊戲模組」類別新模型。此列表包含最近 30-60 天內廣受討論且已正式發佈的最佳模型。",
        "note_en": "No new General Availability (GA) models for 'game module creation' were officially released in August 2026. This list comprises the best and most discussed GA models from the past 30-60 days.",
        "items": [
          {
            "rank": 1,
            "name": "Meshy 6",
            "version": "6",
            "vendor": "Meshy",
            "vendor_en": "Meshy",
            "date": "2026 年 1 月",
            "date_en": "Jan 2026",
            "isNew": false,
            "overlap": "整體 #1",
            "overlap_en": "Overall #1",
            "why": "提供全面的管道、自動綁定和遊戲資產生成，是市場上最全面的工具之一。",
            "why_en": "Offers a comprehensive pipeline, auto-rigging, and game asset generation, making it one of the most all-round tools in the market."
          },
          {
            "rank": 2,
            "name": "Tripo P1.0 / H3.1",
            "version": "P1.0 / H3.1",
            "vendor": "Tripo AI",
            "vendor_en": "Tripo AI",
            "date": "2026 年 3 月",
            "date_en": "Mar 2026",
            "isNew": false,
            "overlap": "整體 #2",
            "overlap_en": "Overall #2",
            "why": "以其卓越的速度、快速迭代能力和生成乾淨拓撲結構的能力而聞名，特別適合遊戲開發流程。",
            "why_en": "Known for its exceptional speed, rapid iteration capabilities, and ability to generate clean topology, especially suitable for game development pipelines."
          },
          {
            "rank": 3,
            "name": "Rodin Gen-2.5",
            "version": "Gen-2.5",
            "vendor": "Hyper3D",
            "vendor_en": "Hyper3D",
            "date": "2026 年 7 月",
            "date_en": "Jul 2026",
            "isNew": false,
            "overlap": "整體 #3",
            "overlap_en": "Overall #3",
            "why": "在英雄資產質量和幾何細節方面表現出色，是 Rodin Gen-2 的最新迭代，在 7 月的評測中獲得高分。",
            "why_en": "Excels in hero-asset quality and geometric detail, an updated iteration of Rodin Gen-2, scoring highly in July reviews."
          },
          {
            "rank": 4,
            "name": "Hunyuan 3D Pro",
            "version": "Pro",
            "vendor": "Tencent",
            "vendor_en": "Tencent",
            "date": "2026 年 7 月",
            "date_en": "Jul 2026",
            "isNew": false,
            "overlap": "整體 #4",
            "overlap_en": "Overall #4",
            "why": "在 2026 年 7 月的排行榜中名列前茅，以其高品質的資產生成和嚴謹的幾何理解而受到認可。",
            "why_en": "Ranked highly in July 2026 leaderboards, recognized for its high-quality asset production and rigorous geometric understanding."
          },
          {
            "rank": 5,
            "name": "TRELLIS.2",
            "version": "2",
            "vendor": "Microsoft",
            "vendor_en": "Microsoft",
            "date": "2026",
            "date_en": "2026",
            "isNew": false,
            "overlap": "整體 #5",
            "overlap_en": "Overall #5",
            "why": "作為一個開源模型，它提供了生產級的質量，並支持原生 PBR，是自託管解決方案中的最佳選擇。",
            "why_en": "As an open-source model, it offers production-grade quality and native PBR support, making it the best choice for self-hosted solutions."
          }
        ]
      }
    },
    {
      "id": 8,
      "icon": "🦴",
      "name": "遊戲模組 Rigging",
      "name_en": "Game Asset Rigging",
      "subtitle": "綁骨 / 可動 · 例如 Anything World",
      "subtitle_en": "Rigging / animation-ready · e.g. Anything World",
      "overall": [
        {
          "rank": 1,
          "name": "Meshy-6 Auto-Rig + Animate",
          "vendor": "Meshy",
          "vendor_en": "Meshy",
          "score": "<30s·500+動作",
          "score_en": "<30s · 500+ anims",
          "why": "一站式,<30 秒自動綁人形/四足,500+ 預設動作",
          "why_en": "One-stop; auto-rigs humanoids/quadrupeds in <30s, 500+ preset animations",
          "meta": "2025–26 · ~$20/mo",
          "meta_en": "2025–26 · ~$20/mo"
        },
        {
          "rank": 2,
          "name": "Autodesk Flow Studio AI Rigging",
          "vendor": "Autodesk",
          "vendor_en": "Autodesk",
          "score": "免費綁骨",
          "score_en": "free rigging",
          "why": "AI 自動關節 + AI 動捕,匯出 Maya/Blender/UE",
          "why_en": "AI auto-joints + AI mocap; export to Maya/Blender/UE",
          "meta": "4/28 · 全層免費預覽",
          "meta_en": "4/28 · free preview, all tiers"
        },
        {
          "rank": 3,
          "name": "Tripo Auto-Rigging (Uni-Rig)",
          "vendor": "Tripo AI",
          "vendor_en": "Tripo AI",
          "score": "骨架+動畫",
          "score_en": "rig + anim",
          "why": "自動骨架 + 權重 + 自動動畫,風格化佳",
          "why_en": "Auto-skeleton + weights + auto-animation; great for stylized",
          "meta": "2025–26 · ~$12/mo",
          "meta_en": "2025–26 · ~$12/mo"
        },
        {
          "rank": 4,
          "name": "Cascadeur 2026.1",
          "vendor": "Nekki",
          "vendor_en": "Nekki",
          "score": "AI 物理動作",
          "score_en": "AI physics",
          "why": "AI AutoPosing/Physics + AI Root Motion,UE Live Link",
          "why_en": "AI AutoPosing/Physics + AI Root Motion; UE Live Link",
          "meta": "4/9 · 免費層+訂閱",
          "meta_en": "4/9 · free tier + subscription"
        },
        {
          "rank": 5,
          "name": "Anything World — Animate Anything",
          "vendor": "Anything World",
          "vendor_en": "Anything World",
          "score": "任意網格",
          "score_en": "any mesh",
          "why": "任意靜態網格 AI 綁定(尤其動物/生物)",
          "why_en": "AI-rig any static mesh (esp. animals/creatures)",
          "meta": "Live · 免費起步+API",
          "meta_en": "Live · free start + API"
        }
      ],
      "monthly": {
        "note": "本月發佈不足 5 個，此為近期(近 30-60 天)補足項目。",
        "note_en": "Less than 5 new releases this month, this item is included from the recent (last 30-60 days) period.",
        "items": [
          {
            "rank": 1,
            "name": "Cascadeur",
            "version": "2026.2",
            "vendor": "Nekki",
            "vendor_en": "Nekki",
            "date": "8/6",
            "date_en": "Aug 6",
            "isNew": true,
            "overlap": "整體 #4",
            "overlap_en": "Overall #4",
            "why": "推出 2026.2 版，改進 AutoPosing、新增動畫圖層（Alpha）及 FBX 材質導入，強化物理基礎動畫工作流程。",
            "why_en": "Released 2026.2, improving AutoPosing, adding animation layers (Alpha), and FBX material import, enhancing physics-based animation workflows."
          },
          {
            "rank": 2,
            "name": "Autodesk Flow Studio",
            "version": "3D Editor + Canvas",
            "vendor": "Autodesk",
            "vendor_en": "Autodesk",
            "date": "8/4",
            "date_en": "Aug 4",
            "isNew": true,
            "overlap": "整體 #2",
            "overlap_en": "Overall #2",
            "why": "推出 3D Editor + Canvas，大幅強化 AI 輔助的 3D 場景編輯與動畫指導工作流程，提供更精確的控制。",
            "why_en": "Launched 3D Editor + Canvas, significantly enhancing AI-assisted 3D scene editing and animation direction workflows, offering more precise control."
          },
          {
            "rank": 3,
            "name": "Tripo AI",
            "version": "Siggraph 2026 Showcase",
            "vendor": "Tripo AI",
            "vendor_en": "Tripo AI",
            "date": "8/14",
            "date_en": "Aug 14",
            "isNew": true,
            "overlap": "整體 #3",
            "overlap_en": "Overall #3",
            "why": "在 Siggraph 2026 展現其整合式 3D 生成生態系統，包括綁骨與動畫功能，並因其快速生成帶綁骨與動畫的 3D 資產而獲獎肯定。",
            "why_en": "Showcased its integrated 3D generation ecosystem, including rigging and animation features, at Siggraph 2026, receiving awards for its fast generation of rigged and animated 3D assets."
          },
          {
            "rank": 4,
            "name": "Character Control Rig",
            "version": "0.3.1",
            "vendor": "Poly Hammer",
            "vendor_en": "Poly Hammer",
            "date": "8/9",
            "date_en": "Aug 9",
            "isNew": true,
            "overlap": null,
            "overlap_en": null,
            "why": "Blender 附加元件更新，支援 Auto-Rig Pro 框架與新的 MetaHuman 動畫重定向引擎，提升角色動畫工作效率。",
            "why_en": "Blender add-on update, supporting Auto-Rig Pro framework and a new MetaHuman animation retargeting engine, improving character animation efficiency."
          },
          {
            "rank": 5,
            "name": "Meshy",
            "version": "Auto-rigging & Animation API",
            "vendor": "Meshy",
            "vendor_en": "Meshy",
            "date": "7/22",
            "date_en": "Jul 22",
            "isNew": false,
            "overlap": "整體 #1",
            "overlap_en": "Overall #1",
            "why": "於上月正式發佈自動綁骨與動畫 API，提供快速角色可動化解決方案，支援多種 3D 模型格式。",
            "why_en": "Officially released Auto-rigging & Animation API last month, offering a fast character animation solution with support for various 3D model formats."
          }
        ]
      }
    },
    {
      "id": 9,
      "icon": "🔊",
      "name": "創建聲音特效",
      "name_en": "Sound Effects & Audio",
      "subtitle": "SFX / 語音 / 音樂 · 例如 ElevenLabs",
      "subtitle_en": "SFX / voice / music · e.g. ElevenLabs",
      "overall": [
        {
          "rank": 1,
          "name": "ElevenLabs SFX v2 + v3 voice",
          "vendor": "ElevenLabs",
          "vendor_en": "ElevenLabs",
          "score": "SFX 龍頭",
          "score_en": "SFX leader",
          "why": "遊戲音訊最全:文字轉 SFX(30s、可無縫循環)+ 頂級語音",
          "why_en": "Most complete game-audio stack: text-to-SFX (30s, seamless loops) + top-tier voice",
          "meta": "SFX 2025/9 · v3 2 月",
          "meta_en": "SFX 2025/9 · v3 Feb"
        },
        {
          "rank": 2,
          "name": "Suno v5",
          "vendor": "Suno",
          "vendor_en": "Suno",
          "score": "音樂 ELO 1293",
          "score_en": "Music ELO 1293",
          "why": "音樂盲測第一(ELO 1293);全曲+人聲質量標竿",
          "why_en": "#1 in music blind tests (ELO 1293); full-song + vocal benchmark",
          "meta": "3/27 · 訂閱制",
          "meta_en": "3/27 · subscription"
        },
        {
          "rank": 3,
          "name": "ElevenLabs Music v2",
          "vendor": "ElevenLabs",
          "vendor_en": "ElevenLabs",
          "score": "商用授權",
          "score_en": "licensed",
          "why": "商用授權清晰,可在曲中嵌 SFX、中途換曲風",
          "why_en": "Clear commercial licensing; embed SFX in tracks, mid-track genre switch",
          "meta": "5/26 · 降價 40–50%",
          "meta_en": "5/26 · 40–50% cheaper"
        },
        {
          "rank": 4,
          "name": "Stable Audio 3",
          "vendor": "Stability AI",
          "vendor_en": "Stability AI",
          "score": "開源·SFX",
          "score_en": "open-source SFX",
          "why": "開源,音樂 + SFX/foley 統一,適合自架 pipeline",
          "why_en": "Open-source; unified music + SFX/foley; great for self-hosted pipelines",
          "meta": "5/20 · 開源權重",
          "meta_en": "5/20 · open weights"
        },
        {
          "rank": 5,
          "name": "Lyria 3 Pro",
          "vendor": "Google DeepMind",
          "vendor_en": "Google DeepMind",
          "score": "3 分鐘長曲",
          "score_en": "3-min tracks",
          "why": "最長 3 分鐘結構化曲目,SynthID 浮水印",
          "why_en": "Up to 3-min structured tracks; SynthID watermark",
          "meta": "3/25 · Gemini/Vertex",
          "meta_en": "3/25 · Gemini/Vertex"
        }
      ],
      "monthly": {
        "note": "本月不足 5 個,故補足近期發佈。",
        "note_en": "Fewer than 5 new releases this month, so supplemented with a recent release.",
        "items": [
          {
            "rank": 1,
            "name": "Suno Studio 2.0",
            "version": "Studio 2.0",
            "vendor": "Suno",
            "vendor_en": "Suno",
            "date": "8/13",
            "date_en": null,
            "isNew": true,
            "overlap": null,
            "overlap_en": null,
            "why": "大幅升級其網頁版 DAW,新增 MIDI、音訊效果、內建合成器及進階音軌分離功能,顯著提升音樂創作控制力。",
            "why_en": "Significantly upgrades its web-based DAW, adding MIDI, audio effects, built-in synths, and advanced stem separation, greatly enhancing music creation control."
          },
          {
            "rank": 2,
            "name": "ElevenLabs Music Finetunes API",
            "version": "API",
            "vendor": "ElevenLabs",
            "vendor_en": "ElevenLabs",
            "date": "8/5",
            "date_en": null,
            "isNew": true,
            "overlap": "整體 #3",
            "overlap_en": "Overall #3",
            "why": "為開發者提供管理音樂微調的 API 支援,實現更精細的音樂生成控制與整合。",
            "why_en": "Provides API support for developers to manage music finetunes, enabling more granular control and integration for music generation."
          },
          {
            "rank": 3,
            "name": "ElevenLabs 平台控制擴展",
            "version": "N/A (platform update)",
            "vendor": "ElevenLabs",
            "vendor_en": "ElevenLabs",
            "date": "8/3",
            "date_en": null,
            "isNew": true,
            "overlap": "整體 #1",
            "overlap_en": "Overall #1",
            "why": "擴展了代理模擬、工作流程翻譯、語音複製等平台控制功能,提升整體 AI 語音與代理服務。",
            "why_en": "Expands platform controls for agent simulations, workflow translations, voice replication, and more, enhancing overall AI voice and agent services."
          },
          {
            "rank": 4,
            "name": "Suno Voices on Mobile",
            "version": "N/A (mobile feature)",
            "vendor": "Suno",
            "vendor_en": "Suno",
            "date": "8/7",
            "date_en": null,
            "isNew": true,
            "overlap": "整體 #2",
            "overlap_en": "Overall #2",
            "why": "將語音複製功能帶到 iOS 和 Android 平台,用戶可錄製一次聲音並在任何歌曲中使用,大幅提升便利性。",
            "why_en": "Brings voice cloning to iOS and Android platforms, allowing users to record their voice once and use it in any song, significantly improving convenience."
          },
          {
            "rank": 5,
            "name": "ElevenLabs Music: Sounds Audio Reference",
            "version": "Feature",
            "vendor": "ElevenLabs",
            "vendor_en": "ElevenLabs",
            "date": "7/2026",
            "date_en": null,
            "isNew": false,
            "overlap": "整體 #3",
            "overlap_en": "Overall #3",
            "why": "推出音訊參考功能,允許用戶透過參考音訊指導音樂生成風格,提升創作精確度。",
            "why_en": "Introduces an Audio Reference feature, allowing users to guide music generation style with reference audio, enhancing creative precision."
          }
        ]
      }
    },
    {
      "id": 10,
      "icon": "🧩",
      "name": "AI 工具組合 Combo",
      "name_en": "AI Tool Combos",
      "subtitle": "依社群熱度 Top10 · 例如 Claude + Obsidian",
      "subtitle_en": "By popularity, Top 10 · e.g. Claude + Obsidian",
      "overall": [
        {
          "rank": 1,
          "name": "Cursor + Claude Code + GitHub Copilot",
          "vendor": "Anysphere + Anthropic + OpenAI/GitHub",
          "vendor_en": "Anysphere + Anthropic + OpenAI/GitHub",
          "score": "巨量採用",
          "score_en": "huge adoption",
          "why": "主流「出貨」編程組合:IDE agent + 終端 agent 並用;1.8M Copilot 開發者、~半數財星500用 Cursor",
          "why_en": "The dominant 'ship software' coding stack; 1.8M Copilot devs, ~half of Fortune 500 on Cursor",
          "meta": "媒體高曝光",
          "meta_en": "heavy media coverage"
        },
        {
          "rank": 2,
          "name": "Claude Code + GitHub + Vercel",
          "vendor": "Anthropic + GitHub + Vercel",
          "vendor_en": "Anthropic + GitHub + Vercel",
          "score": "廣傳·官方",
          "score_en": "viral · official",
          "why": "prompt→push→自動部署上線;官方 Vercel 外掛(你正在用的)",
          "why_en": "prompt→push→auto-deploy live; official Vercel plugin (the one you use)",
          "meta": "YouTube/媒體廣傳",
          "meta_en": "widely shared"
        },
        {
          "rank": 3,
          "name": "n8n + LLM (OpenAI/Claude) + MCP",
          "vendor": "n8n",
          "vendor_en": "n8n",
          "score": "GitHub 191k★",
          "score_en": "GitHub 191k★",
          "why": "可自架的視覺化 AI agent/工作流自動化;191k stars、$2.5B 估值",
          "why_en": "Self-hosted visual AI-agent/workflow automation; 191k stars, $2.5B valuation",
          "meta": "230k+ users",
          "meta_en": "230k+ users"
        },
        {
          "rank": 4,
          "name": "ComfyUI + Flux / Suno / ElevenLabs",
          "vendor": "ComfyUI + community",
          "vendor_en": "ComfyUI + community",
          "score": "GitHub ~110k★",
          "score_en": "GitHub ~110k★",
          "why": "節點式創作流水線:圖→影→語音/音樂同一畫布;ElevenLabs 官方節點",
          "why_en": "Node-graph creative pipeline: image→video→voice/music; official ElevenLabs node",
          "meta": "~106k+ stars",
          "meta_en": "~106k+ stars"
        },
        {
          "rank": 5,
          "name": "ChatGPT / Claude + Notion",
          "vendor": "OpenAI/Anthropic + Notion",
          "vendor_en": "OpenAI/Anthropic + Notion",
          "score": "高討論",
          "score_en": "highly discussed",
          "why": "LLM 在你的團隊 wiki/筆記上推理;最常被搜的生產力配對",
          "why_en": "LLM reasoning over your team wiki/notes; most-searched productivity pairing",
          "meta": "Reddit/媒體高討論",
          "meta_en": "Reddit/media buzz"
        },
        {
          "rank": 6,
          "name": "Microsoft Copilot (Agent 365) + Claude + GPT",
          "vendor": "Microsoft + Anthropic + OpenAI",
          "vendor_en": "Microsoft + Anthropic + OpenAI",
          "score": "企業高曝光",
          "score_en": "enterprise buzz",
          "why": "企業多模型調度:「GPT 起草、Claude 審查」",
          "why_en": "Enterprise multi-model orchestration: 'GPT drafts, Claude reviews'",
          "meta": "Agent 365 GA 5/1",
          "meta_en": "Agent 365 GA May 1"
        },
        {
          "rank": 7,
          "name": "Claude + Obsidian",
          "vendor": "Anthropic + Obsidian",
          "vendor_en": "Anthropic + Obsidian",
          "score": "YouTube 廣傳",
          "score_en": "viral on YouTube",
          "why": "AI 第二大腦:Claude 讀寫你的本地筆記(你同事推的那個)",
          "why_en": "AI second brain: Claude reads/builds on your local notes (your colleague's pick)",
          "meta": "XDA/多篇教學",
          "meta_en": "XDA + many guides"
        },
        {
          "rank": 8,
          "name": "Perplexity + NotebookLM + Claude",
          "vendor": "Perplexity + Google + Anthropic",
          "vendor_en": "Perplexity + Google + Anthropic",
          "score": "研究熱門",
          "score_en": "popular research",
          "why": "研究組合:有來源的網搜 → 來源紮根 → 深入推理",
          "why_en": "Research stack: cited web search → source grounding → deep reasoning",
          "meta": "媒體高討論",
          "meta_en": "heavy coverage"
        },
        {
          "rank": 9,
          "name": "Midjourney + Runway/Veo + ElevenLabs + Suno + Descript",
          "vendor": "多家 multi-vendor",
          "vendor_en": "multi-vendor",
          "score": "製片廣傳",
          "score_en": "popular for video",
          "why": "端到端 AI 影片:腳本→分鏡→畫面→配音→配樂→剪輯",
          "why_en": "End-to-end AI video: script→storyboard→footage→VO→music→edit",
          "meta": "標準製片流程",
          "meta_en": "standard production stack"
        },
        {
          "rank": 10,
          "name": "Raycast AI + Claude / Perplexity / NotebookLM",
          "vendor": "Raycast + 多家",
          "vendor_en": "Raycast + multi-vendor",
          "score": "中討論",
          "score_en": "modest buzz",
          "why": "Mac 啟動器當各 AI 工具的黏合層(剪貼簿、片語、MCP)",
          "why_en": "Mac launcher as the glue across AI tools (clipboard, snippets, MCP)",
          "meta": "Substack 報導",
          "meta_en": "Substack feature"
        }
      ],
      "monthly": {
        "note": null,
        "note_en": null,
        "items": [
          {
            "rank": 1,
            "name": "Cursor + Claude Fable 5 + GitHub Copilot",
            "version": "Claude Fable 5",
            "vendor": "Cursor, Anthropic, GitHub",
            "vendor_en": "Cursor, Anthropic, GitHub",
            "date": "7/上旬",
            "date_en": "Early July",
            "isNew": true,
            "overlap": "整體 #1",
            "overlap_en": "Overall #1",
            "why": "Claude Fable 5 的卓越程式碼理解與生成能力,結合 Cursor 的 AI 原生 IDE 和 GitHub Copilot,為開發者提供無與倫比的編碼體驗。",
            "why_en": "Claude Fable 5's superior code comprehension and generation, combined with Cursor's AI-native IDE and GitHub Copilot, offers developers an unparalleled coding experience."
          },
          {
            "rank": 2,
            "name": "Microsoft Copilot (Agent 365) v2.0 + Claude Fable 5 + GPT-5",
            "version": "Agent 365 v2.0, Claude Fable 5, GPT-5",
            "vendor": "Microsoft, Anthropic, OpenAI",
            "vendor_en": "Microsoft, Anthropic, OpenAI",
            "date": "7/中旬",
            "date_en": "Mid-July",
            "isNew": true,
            "overlap": "整體 #6",
            "overlap_en": "Overall #6",
            "why": "Microsoft Copilot Agent 365 v2.0 強化了其代理框架,並深度整合最新的 Claude Fable 5 和 GPT-5 模型,為企業提供更強大的自動化與決策支援。",
            "why_en": "Microsoft Copilot Agent 365 v2.0 enhances its agentic framework with deep integration of the latest Claude Fable 5 and GPT-5 models, offering superior enterprise automation and decision support."
          },
          {
            "rank": 3,
            "name": "n8n v3.0 + Claude Fable 5 + MCP (Microsoft Copilot Platform)",
            "version": "n8n v3.0, Claude Fable 5",
            "vendor": "n8n, Anthropic, Microsoft",
            "vendor_en": "n8n, Anthropic, Microsoft",
            "date": "7/上旬",
            "date_en": "Early July",
            "isNew": true,
            "overlap": "整體 #3",
            "overlap_en": "Overall #3",
            "why": "n8n v3.0 推出新的連接器和模板,將 Claude Fable 5 的先進智能與 Microsoft Copilot Platform 的企業級整合能力無縫結合,實現強大的自動化工作流。",
            "why_en": "n8n v3.0 introduces new connectors and templates, seamlessly integrating Claude Fable 5's advanced intelligence with Microsoft Copilot Platform's enterprise-grade capabilities for powerful automation workflows."
          },
          {
            "rank": 4,
            "name": "Claude Fable 5 + GitHub + Vercel",
            "version": "Claude Fable 5",
            "vendor": "Anthropic, GitHub, Vercel",
            "vendor_en": "Anthropic, GitHub, Vercel",
            "date": "7/上旬",
            "date_en": "Early July",
            "isNew": true,
            "overlap": "整體 #2",
            "overlap_en": "Overall #2",
            "why": "利用 Claude Fable 5 進行進階程式碼生成與審查,結合 GitHub 的版本控制和 Vercel 的 AI 驅動部署,大幅簡化了整個開發生命週期。",
            "why_en": "Leveraging Claude Fable 5 for advanced code generation and review, integrated with GitHub for version control and Vercel for AI-driven deployment, significantly streamlines the entire development lifecycle."
          },
          {
            "rank": 5,
            "name": "Perplexity AI Pro (Enhanced) + NotebookLM + Claude Fable 5",
            "version": "Perplexity AI Pro (Enhanced), Claude Fable 5",
            "vendor": "Perplexity AI, Google, Anthropic",
            "vendor_en": "Perplexity AI, Google, Anthropic",
            "date": "7/上旬",
            "date_en": "Early July",
            "isNew": true,
            "overlap": "整體 #8",
            "overlap_en": "Overall #8",
            "why": "Perplexity Pro 的增強型研究功能,結合 NotebookLM 的組織能力和 Claude Fable 5 的深度分析,共同打造頂級的研究與知識管理堆疊。",
            "why_en": "Perplexity Pro's enhanced research capabilities, combined with NotebookLM's organization and Claude Fable 5's deep analytical power, create a leading research and knowledge management stack."
          },
          {
            "rank": 6,
            "name": "ComfyUI Workflow Hub + Flux / Suno / ElevenLabs",
            "version": "ComfyUI Workflow Hub",
            "vendor": "ComfyUI Community, Flux, Suno, ElevenLabs",
            "vendor_en": "ComfyUI Community, Flux, Suno, ElevenLabs",
            "date": "7/中旬",
            "date_en": "Mid-July",
            "isNew": true,
            "overlap": "整體 #4",
            "overlap_en": "Overall #4",
            "why": "ComfyUI Workflow Hub 的推出簡化了複雜多模態生成式 AI 工作流的創建與分享,整合了先進模型用於圖像、音樂和語音生成。",
            "why_en": "The launch of ComfyUI Workflow Hub simplifies the creation and sharing of complex multimodal generative AI workflows, integrating advanced models for image, music, and voice generation."
          },
          {
            "rank": 7,
            "name": "Claude Fable 5 + Obsidian",
            "version": "Claude Fable 5",
            "vendor": "Anthropic, Obsidian",
            "vendor_en": "Anthropic, Obsidian",
            "date": "7/上旬",
            "date_en": "Early July",
            "isNew": true,
            "overlap": "整體 #7",
            "overlap_en": "Overall #7",
            "why": "Claude Fable 5 卓越的推理和摘要能力,與 Obsidian 強大的知識圖譜整合,提供無與倫比的個人知識管理和洞察生成。",
            "why_en": "Claude Fable 5's superior reasoning and summarization capabilities, integrated with Obsidian's robust knowledge graph, offer unparalleled personal knowledge management and insight generation."
          },
          {
            "rank": 8,
            "name": "Midjourney v7 + Runway/Veo + ElevenLabs + Suno + Descript",
            "version": "Midjourney v7",
            "vendor": "Midjourney, Runway, Google, ElevenLabs, Suno, Descript",
            "vendor_en": "Midjourney, Runway, Google, ElevenLabs, Suno, Descript",
            "date": "7/中旬",
            "date_en": "Mid-July",
            "isNew": true,
            "overlap": "整體 #9",
            "overlap_en": "Overall #9",
            "why": "Midjourney v7 的發佈,結合先進的影片、音訊和編輯工具,創造了一個強大且端到端的創意媒體製作流程。",
            "why_en": "The release of Midjourney v7, combined with advanced video, audio, and editing tools, creates a powerful, end-to-end creative media production pipeline."
          },
          {
            "rank": 9,
            "name": "ChatGPT Enterprise (Advanced Agentic Features) + Notion",
            "version": "ChatGPT Enterprise (Advanced Agentic Features)",
            "vendor": "OpenAI, Notion",
            "vendor_en": "OpenAI, Notion",
            "date": "7/下旬",
            "date_en": "Late July",
            "isNew": true,
            "overlap": "整體 #5",
            "overlap_en": "Overall #5",
            "why": "ChatGPT Enterprise 推出的新代理功能,提供與 Notion 工作區更深層次的整合和自動化能力,提升團隊協作和內容創作效率。",
            "why_en": "New advanced agentic features in ChatGPT Enterprise offer deeper integration and automation capabilities within Notion workspaces, enhancing team collaboration and content creation efficiency."
          },
          {
            "rank": 10,
            "name": "Raycast AI (Expanded LLM Support) + Claude Fable 5 / Perplexity / NotebookLM",
            "version": "Raycast AI (Expanded LLM Support), Claude Fable 5",
            "vendor": "Raycast, Anthropic, Perplexity AI, Google",
            "vendor_en": "Raycast, Anthropic, Perplexity AI, Google",
            "date": "7/中旬",
            "date_en": "Mid-July",
            "isNew": true,
            "overlap": "整體 #10",
            "overlap_en": "Overall #10",
            "why": "Raycast AI 擴展了對最新 LLM (包括 Claude Fable 5) 的支援,並引入新功能,實現桌面工作流中不同 AI 工具的無縫切換和整合,大幅提升生產力。",
            "why_en": "Raycast AI's expanded support for the latest LLMs (including Claude Fable 5) and new features enable seamless switching and integration between different AI tools within desktop workflows, significantly boosting productivity."
          }
        ]
      }
    }
  ]
};
