/* 自動產生 — ①讀 curated.json、②每日 Gemini 研究;勿手動編輯(改①請編 curated.json) */
window.DIGEST = {
  "updatedAt": "2026-09-04T02:55:51+08:00",
  "updatedDateLabel": "2026 年 9 月 4 日",
  "month": "2026 年 9 月",
  "month_en": "September 2026",
  "dataConfidence": "①整體=手工校正權威版;②本月最新由 gemini-2.5-flash+Google 搜尋於 2026/09/04 自動更新",
  "dataConfidence_en": "① curated (hand-verified); ② this-month auto-updated by gemini-2.5-flash+Google Search on 2026/09/04",
  "changesToday": [
    "Claude Fable (9/1) — 綜合 AI MODEL 排名",
    "Gemini Flash (9/2) — 綜合 AI MODEL 排名",
    "Claude Fable (9/1) — 創建遊戲的助手",
    "Gemini Flash (9/2) — 創建遊戲的助手",
    "Atlas (9/1) — 創建數據模擬器 & 數據推理",
    "Claude Fable 5.1 (9/1) — 創建數據模擬器 & 數據推理"
  ],
  "changesToday_en": [
    "Claude Fable (9/1) — Overall AI Model Ranking",
    "Gemini Flash (9/2) — Overall AI Model Ranking",
    "Claude Fable (9/1) — Game-Building Assistants",
    "Gemini Flash (9/2) — Game-Building Assistants",
    "Atlas (9/1) — Data Simulators & Reasoning",
    "Claude Fable 5.1 (9/1) — Data Simulators & Reasoning"
  ],
  "notes": [
    "中立聲明:①整體榜以第三方獨立榜為準(綜合=AA 指數、編程=SWE-bench、推理=GPQA、圖片=LMArena Arena)、只列已發佈模型、經人工校正,非本 AI 或任何廠商觀點。",
    "①整體=手工校正的權威版(穩定);②本月最新=每日免費自動研究(僅供速覽,偶有出入請點源覆核)。",
    "排名每天會動:AA 為 72 小時滾動、LMArena Elo 每天浮動,第 2~5 名常在誤差內。"
  ],
  "notes_en": [
    "Neutrality: ① follows independent third-party leaderboards (General=AA Index, Coding=SWE-bench, Reasoning=GPQA, Image=LMArena Arena), GA models only, human-verified — not this AI's or any vendor's view.",
    "① = hand-curated authoritative (stable); ② = free auto-research daily (quick reference; verify against sources).",
    "Rankings shift daily: AA is a 72-hour rolling average and LMArena Elo moves; ranks 2–5 are often within noise."
  ],
  "categories": [
    {
      "id": 1,
      "icon": "🧠",
      "name": "綜合 AI MODEL 排名",
      "name_en": "Overall AI Model Ranking",
      "subtitle": "依 AA 智能指數 · Gemini / Claude / GPT",
      "subtitle_en": "By AA Intelligence Index · Gemini / Claude / GPT",
      "overall": [
        {
          "rank": 1,
          "name": "Claude Opus 5",
          "vendor": "Anthropic",
          "vendor_en": "Anthropic",
          "score": "AA 61",
          "score_en": "AA 61",
          "why": "AA 智能指數世界第一(61, v4.1);Claude Max 新預設,價僅 Fable 半價",
          "why_en": "#1 in the world on AA Intelligence Index (61, v4.1); new Claude Max default at half Fable's price",
          "meta": "7/24 發佈 · $5/$25 · Max 預設",
          "meta_en": "Released 7/24 · $5/$25 · Max default"
        },
        {
          "rank": 2,
          "name": "Claude Fable 5",
          "vendor": "Anthropic",
          "vendor_en": "Anthropic",
          "score": "AA 60",
          "why": "AA 智能指數 60,僅次於 Opus 5;公開可用最強之一",
          "why_en": "AA Index 60, just behind Opus 5; among the strongest available",
          "meta": "7/1 全球返場 · 曾因出口管制暫停 18 天",
          "meta_en": "Returned globally 7/1 · was suspended 18 days",
          "score_en": "AA 60"
        },
        {
          "rank": 3,
          "name": "GPT-5.6 Sol",
          "vendor": "OpenAI",
          "vendor_en": "OpenAI",
          "score": "AA 59",
          "score_en": "AA 59",
          "why": "AA 智能指數 #2(59);OpenAI 新一代旗艦",
          "why_en": "#2 on AA Intelligence Index (59); OpenAI's new flagship",
          "meta": "7/9 發佈",
          "meta_en": "Released 7/9"
        },
        {
          "rank": 4,
          "name": "Kimi K3",
          "vendor": "Moonshot AI 月之暗面",
          "vendor_en": "Moonshot AI",
          "score": "AA 57",
          "score_en": "AA 57",
          "why": "AA 智能指數 57.1,首度躋身前段",
          "why_en": "AA Intelligence Index 57.1; breaks into the top tier",
          "meta": "2026-07 新進榜",
          "meta_en": "New on the board, July 2026"
        },
        {
          "rank": 5,
          "name": "Claude Opus 4.8",
          "vendor": "Anthropic",
          "vendor_en": "Anthropic",
          "score": "AA 56",
          "why": "AA 智能指數 #1(61.4);獨立第三方確認",
          "why_en": "#1 on AA Intelligence Index (61.4); independently confirmed",
          "meta": "5/28 發佈 · API $5/$25",
          "meta_en": "Released 5/28 · API $5/$25",
          "score_en": "AA 56"
        }
      ],
      "monthly": {
        "note": "本月(2026 年 9 月)初發佈的通用旗艦模型數量不足 5 個，故補充近期(2026 年 8 月)發佈的模型以補足排名。",
        "note_en": "As of early September 2026, there are fewer than 5 new general flagship models released this month, so recent releases from August 2026 are included to complete the ranking.",
        "items": [
          {
            "rank": 1,
            "name": "Claude Fable",
            "version": "5.1",
            "vendor": "Anthropic",
            "vendor_en": "Anthropic",
            "date": "9/1",
            "date_en": null,
            "isNew": true,
            "overlap": null,
            "overlap_en": null,
            "why": "本月新發佈，在 Artificial Analysis Intelligence Index 獲得 66 分，是目前最高分，超越 Fable 5、Opus 5 及 GPT-5.6 Sol。",
            "why_en": "Newly released this month, it scored 66 on the Artificial Analysis Intelligence Index, the highest measured to date, surpassing Fable 5, Opus 5, and GPT-5.6 Sol."
          },
          {
            "rank": 2,
            "name": "Gemini Flash",
            "version": "3.8",
            "vendor": "Google",
            "vendor_en": "Google",
            "date": "9/2",
            "date_en": null,
            "isNew": true,
            "overlap": null,
            "overlap_en": null,
            "why": "本月新發佈的輕量級模型，在 Artificial Analysis Intelligence Index 獲得 59 分，在智能與成本效益上表現優異。",
            "why_en": "Newly released this month, this lightweight model scored 59 on the Artificial Analysis Intelligence Index, demonstrating excellent intelligence-to-cost efficiency."
          },
          {
            "rank": 3,
            "name": "GPT-5.6 Sol",
            "version": "August Update",
            "vendor": "OpenAI",
            "vendor_en": "OpenAI",
            "date": "8/6",
            "date_en": null,
            "isNew": false,
            "overlap": "整體 #3",
            "overlap_en": "Overall #3",
            "why": "旗艦模型於 8 月更新，為 Plus 和 Pro 用戶提供更可靠的事實和更專注的答案，並新增響應思考程度調整功能。",
            "why_en": "Flagship model updated in August, providing more reliable facts and focused answers for Plus and Pro users, with a new slider to adjust response effort."
          },
          {
            "rank": 4,
            "name": "GLM-5.3-Flash",
            "version": null,
            "vendor": "Z.ai",
            "vendor_en": "Z.ai",
            "date": "8/26",
            "date_en": null,
            "isNew": false,
            "overlap": null,
            "overlap_en": null,
            "why": "8 月底發佈的快速且具前沿能力的通用 AI 模型。",
            "why_en": "A fast and frontier general-purpose AI model released in late August."
          },
          {
            "rank": 5,
            "name": "Qwen3.8-Flash-Next",
            "version": null,
            "vendor": "Qwen / Alibaba Cloud",
            "vendor_en": "Qwen / Alibaba Cloud",
            "date": "8/26",
            "date_en": null,
            "isNew": false,
            "overlap": null,
            "overlap_en": null,
            "why": "8 月底發佈的快速通用模型，由阿里巴巴雲支持。",
            "why_en": "A fast general-purpose model released in late August, supported by Alibaba Cloud."
          }
        ]
      }
    },
    {
      "id": 2,
      "icon": "🎮",
      "name": "創建遊戲的助手",
      "name_en": "Game-Building Assistants",
      "subtitle": "AI 編程(依 SWE-bench) · 你的 Three.js + Claude Code + GitHub + Vercel pipeline",
      "subtitle_en": "AI coding (by SWE-bench) · your Three.js + Claude Code + GitHub + Vercel pipeline",
      "overall": [
        {
          "rank": 1,
          "name": "Claude Opus 5",
          "vendor": "Anthropic",
          "vendor_en": "Anthropic",
          "score": "AA 編程#1",
          "score_en": "AA Coding #1",
          "why": "領先 AA 編程指數(SWE-Atlas-QnA 最高);搭 Claude Code 最強",
          "why_en": "#1 on AA Coding Index (top SWE-Atlas-QnA); strongest paired with Claude Code",
          "meta": "7/24 · Max 預設",
          "meta_en": "7/24 · Max default"
        },
        {
          "rank": 2,
          "name": "Claude Fable 5",
          "vendor": "Anthropic",
          "vendor_en": "Anthropic",
          "score": "SWE 95%",
          "score_en": "SWE 95%",
          "why": "SWE-bench Verified 95%;編程次於 Opus 5(公開可用第二強)",
          "why_en": "SWE-bench Verified 95%; #2 coding behind Opus 5",
          "meta": "7/1 返場 · Mythos 級",
          "meta_en": "Returned 7/1 · Mythos-class"
        },
        {
          "rank": 3,
          "name": "GPT-5.5",
          "vendor": "OpenAI",
          "vendor_en": "OpenAI",
          "score": "SWE 88.7%",
          "why": "公開 SWE-bench Verified 第一(88.7%);Codex/Copilot 內建",
          "why_en": "#1 on public SWE-bench Verified (88.7%); built into Codex/Copilot",
          "meta": "4/23 · ChatGPT/API",
          "meta_en": "4/23 · ChatGPT/API"
        },
        {
          "rank": 4,
          "name": "Claude Opus 4.8",
          "vendor": "Anthropic",
          "vendor_en": "Anthropic",
          "score": "SWE 88.6%",
          "why": "SWE 88.6%(幾乎並列第一);WebDev Arena 第一,最適合你的 Three.js 前端",
          "why_en": "SWE 88.6% (near-tied for #1); #1 on WebDev Arena — best for your Three.js frontend",
          "meta": "5/28 · Claude Code 原生",
          "meta_en": "5/28 · native to Claude Code"
        },
        {
          "rank": 5,
          "name": "Claude Opus 4.7",
          "vendor": "Anthropic",
          "vendor_en": "Anthropic",
          "score": "SWE 87.6%",
          "why": "前代旗艦,SWE 87.6%,WebDev 仍強",
          "why_en": "Prior flagship, SWE 87.6%, still strong on WebDev",
          "meta": "~4 月 · Claude API",
          "meta_en": "~Apr · Claude API"
        }
      ],
      "monthly": {
        "note": null,
        "note_en": null,
        "items": [
          {
            "rank": 1,
            "name": "Claude Fable",
            "version": "5.1",
            "vendor": "Anthropic",
            "vendor_en": "Anthropic",
            "date": "9/1",
            "date_en": null,
            "isNew": true,
            "overlap": "整體 #2",
            "overlap_en": "Overall #2",
            "why": "Anthropic 最新發佈的旗艦模型，專為複雜推理、長程代理任務和程式編寫而設計，在 SWE-bench Pro 基準測試中表現領先，非常適合遊戲開發中的複雜邏輯和 AI 代理。",
            "why_en": "Anthropic's latest flagship model, designed for complex reasoning, long-running agent tasks, and coding, leading in SWE-bench Pro benchmarks, making it highly suitable for complex logic and AI agents in game development."
          },
          {
            "rank": 2,
            "name": "Gemini Flash",
            "version": "3.8",
            "vendor": "Google",
            "vendor_en": "Google",
            "date": "9/2",
            "date_en": null,
            "isNew": true,
            "overlap": null,
            "overlap_en": null,
            "why": "Google 最新的 Flash 模型，專為長週期軟體工程、自主代理和複雜企業工作流程而優化，提供卓越的程式編寫和代理能力，適用於遊戲引擎開發和工具建構。",
            "why_en": "Google's latest Flash model, optimized for long-horizon software engineering, autonomous agents, and complex enterprise workflows, offering superior coding and agentic capabilities for game engine development and tool building."
          },
          {
            "rank": 3,
            "name": "Claude Platform GA (Computer Use, Browser Tool, Skills API, Files API)",
            "version": "N/A",
            "vendor": "Anthropic",
            "vendor_en": "Anthropic",
            "date": "8/20",
            "date_en": null,
            "isNew": false,
            "overlap": null,
            "overlap_en": null,
            "why": "Anthropic 將其電腦使用、瀏覽器工具、技能 API 和檔案 API 正式發佈，大幅提升 Claude 模型作為代理的實用性，使其能直接與開發環境互動，對遊戲開發助手而言是重大進展。",
            "why_en": "Anthropic officially released its Computer Use, Browser Tool, Skills API, and Files API, significantly enhancing Claude models' utility as agents by allowing direct interaction with development environments, a major advancement for game development assistants."
          },
          {
            "rank": 4,
            "name": "Gemini Flash",
            "version": "3.7",
            "vendor": "Google",
            "vendor_en": "Google",
            "date": "8/13",
            "date_en": null,
            "isNew": false,
            "overlap": null,
            "overlap_en": null,
            "why": "Google 的強大工作模型，在軟體工程、網頁開發和代理工作流程方面有顯著改進，尤其在 WebDev Arena 表現出色，非常適合網頁遊戲開發中的 UI 生成和功能實現。",
            "why_en": "Google's powerful workhorse model, with substantial improvements in software engineering, web development, and agentic workflows, notably excelling in the WebDev Arena, making it ideal for UI generation and feature implementation in web game development."
          },
          {
            "rank": 5,
            "name": "Muse Spark",
            "version": "1.3",
            "vendor": "Meta",
            "vendor_en": "Meta",
            "date": "9/1",
            "date_en": null,
            "isNew": true,
            "overlap": null,
            "overlap_en": null,
            "why": "Meta 最新發佈的 AI 編程代理模型，繼承了 Muse Code 處理複雜軟體工程任務的能力，適用於遊戲引擎工具和複雜遊戲邏輯的開發。",
            "why_en": "Meta's latest AI coding agent model, building on Muse Code's capabilities for complex software engineering tasks, suitable for developing game engine tools and intricate game logic."
          }
        ]
      }
    },
    {
      "id": 3,
      "icon": "📊",
      "name": "創建數據模擬器 & 數據推理",
      "name_en": "Data Simulators & Reasoning",
      "subtitle": "依 GPQA Diamond · 對應你的「深海奪寶」RTP 沙盤",
      "subtitle_en": "By GPQA Diamond · for your 'Abyss Treasury' RTP sandbox",
      "overall": [
        {
          "rank": 1,
          "name": "Gemini 3.1 Pro",
          "vendor": "Google",
          "vendor_en": "Google",
          "score": "GPQA 94.1%",
          "why": "GPQA Diamond 第一(94.1%);大 context 適合分析大量模擬結果",
          "why_en": "#1 on GPQA Diamond (94.1%); big context for analyzing large result sets",
          "meta": "~Q1 · AI Studio/Vertex",
          "meta_en": "~Q1 · AI Studio/Vertex"
        },
        {
          "rank": 2,
          "name": "Claude Opus 5",
          "vendor": "Anthropic",
          "vendor_en": "Anthropic",
          "score": "AA 61",
          "score_en": "AA 61",
          "why": "AA 綜合智能世界第一(61);推理屬頂段",
          "why_en": "#1 overall on AA (61); top-tier reasoning",
          "meta": "7/24 · Max 預設",
          "meta_en": "7/24 · Max default"
        },
        {
          "rank": 3,
          "name": "Claude Fable 5",
          "vendor": "Anthropic",
          "vendor_en": "Anthropic",
          "score": "AA 60",
          "score_en": "AA 60",
          "why": "綜合智能第一;推理屬頂段(GPQA 前段)",
          "why_en": "#1 overall intelligence; top-tier reasoning (GPQA leading pack)",
          "meta": "7/1 返場 · Mythos 級",
          "meta_en": "Returned 7/1 · Mythos-class"
        },
        {
          "rank": 4,
          "name": "GPT-5.5 (xhigh)",
          "vendor": "OpenAI",
          "vendor_en": "OpenAI",
          "score": "GPQA 93.5%",
          "why": "GPQA 93.5%;純機率數學最強",
          "why_en": "GPQA 93.5%; best at pure probability math",
          "meta": "4/23 · 機率推導",
          "meta_en": "4/23 · probability reasoning"
        },
        {
          "rank": 5,
          "name": "Claude Opus 4.8 (max)",
          "vendor": "Anthropic",
          "vendor_en": "Anthropic",
          "score": "AA 56",
          "score_en": "AA 56",
          "why": "綜合智能 AA #1;最會寫+跑模擬程式碼(GPQA 屬飽和帶,差距極小)",
          "why_en": "#1 on AA overall; best at writing+running simulation code (GPQA saturated, tiny gaps)",
          "meta": "5/28 · 寫/跑模擬",
          "meta_en": "5/28 · build/run simulations"
        }
      ],
      "monthly": {
        "note": "本月(2026 年 9 月)發佈不足 5 個,已用最近期(近 30–60 天)發佈補足。",
        "note_en": "Fewer than 5 new releases in September 2026, supplemented with recent releases (last 30-60 days).",
        "items": [
          {
            "rank": 1,
            "name": "Atlas",
            "version": "1.0",
            "vendor": "World Labs",
            "vendor_en": "World Labs",
            "date": "9/1",
            "date_en": "Sep 1",
            "isNew": true,
            "overlap": null,
            "overlap_en": null,
            "why": "首個能從少量圖片生成、重建和模擬 3D 世界的 AI 模型，並能生成機器人訓練數據，直接契合數據模擬範疇。",
            "why_en": "The first AI model capable of generating, reconstructing, and simulating 3D worlds from a few images, and generating robot training data, directly fitting the data simulation category."
          },
          {
            "rank": 2,
            "name": "Claude Fable 5.1",
            "version": "5.1",
            "vendor": "Anthropic",
            "vendor_en": "Anthropic",
            "date": "9/1",
            "date_en": "Sep 1",
            "isNew": true,
            "overlap": "整體 #3",
            "overlap_en": "Overall #3",
            "why": "相較前代 Claude Fable 5，在長時間、複雜編碼任務和科學工作流程中表現顯著提升，強化了數據推理能力。",
            "why_en": "Compared to its predecessor Claude Fable 5, it demonstrates significantly enhanced performance in long-duration, complex coding tasks, and scientific workflows, strengthening data reasoning capabilities."
          },
          {
            "rank": 3,
            "name": "Grok 4.6",
            "version": "4.6",
            "vendor": "xAI",
            "vendor_en": "xAI",
            "date": "8/12",
            "date_en": "Aug 12",
            "isNew": false,
            "overlap": null,
            "overlap_en": null,
            "why": "在 Artificial Analysis Intelligence Index 和 GPQA Diamond 等基準測試中表現強勁，顯示出卓越的推理能力。",
            "why_en": "Demonstrates strong performance on benchmarks like Artificial Analysis Intelligence Index and GPQA Diamond, indicating excellent reasoning capabilities."
          },
          {
            "rank": 4,
            "name": "Gemini 3.8 Flash",
            "version": "3.8 Flash",
            "vendor": "Google",
            "vendor_en": "Google",
            "date": "9/2",
            "date_en": "Sep 2",
            "isNew": true,
            "overlap": null,
            "overlap_en": null,
            "why": "作為新的 Flash 模型，在 GPQA Diamond 基準測試中取得高分，擅長數據推理和快速數據推斷。",
            "why_en": "As a new Flash model, it achieved high scores on the GPQA Diamond benchmark, excelling in data reasoning and rapid data inference."
          },
          {
            "rank": 5,
            "name": "Gemini 3.7 Flash",
            "version": "3.7 Flash",
            "vendor": "Google",
            "vendor_en": "Google",
            "date": "8/13",
            "date_en": "Aug 13",
            "isNew": false,
            "overlap": null,
            "overlap_en": null,
            "why": "專為編碼、推理、token 效率和代理工作負載而優化，是快速數據分析和輕量級模擬任務的有力選擇。",
            "why_en": "Optimized for coding, reasoning, token efficiency, and agentic workloads, making it a strong choice for rapid data analysis and lightweight simulation tasks."
          }
        ]
      }
    },
    {
      "id": 4,
      "icon": "🖼️",
      "name": "創建圖片美術",
      "name_en": "Image & Art Generation",
      "subtitle": "文生圖質量 · 依 LMArena 文生圖 Arena",
      "subtitle_en": "Text-to-image quality · by LMArena T2I Arena",
      "overall": [
        {
          "rank": 1,
          "name": "GPT Image 2",
          "vendor": "OpenAI",
          "vendor_en": "OpenAI",
          "score": "Arena #1",
          "why": "LMArena 文生圖 Arena 第一,分數大幅領先",
          "why_en": "#1 on LMArena text-to-image Arena by a wide margin",
          "meta": "OpenAI 現役旗艦圖像",
          "meta_en": "OpenAI current flagship image model"
        },
        {
          "rank": 2,
          "name": "Muse Image",
          "vendor": "Meta",
          "vendor_en": "Meta",
          "score": "Arena #2",
          "why": "Meta 官方稱 Arena #2(文生圖+編修);人像/場景強",
          "why_en": "Meta claims #2 on Arena (t2i + editing); strong portraits/scenes",
          "meta": "7/8 發佈 · Meta Superintelligence Labs",
          "meta_en": "Launched 7/8 · Meta Superintelligence Labs"
        },
        {
          "rank": 3,
          "name": "Reve 2.0",
          "vendor": "Reve AI",
          "vendor_en": "Reve AI",
          "score": "Arena #3",
          "why": "版面優先、4K 高解析;獨立 Reve AI(Palo Alto)",
          "why_en": "Layout-first 4K; from indie Reve AI (Palo Alto)",
          "meta": "6/3 發佈",
          "meta_en": "Released 6/3"
        },
        {
          "rank": 4,
          "name": "Gemini 3.1 Flash Image",
          "vendor": "Google",
          "vendor_en": "Google",
          "score": "Arena #4",
          "why": "Google 快速高質圖像(Nano-Banana 後繼)",
          "why_en": "Google fast high-quality image (Nano-Banana successor)",
          "meta": "preview",
          "meta_en": "preview"
        },
        {
          "rank": 5,
          "name": "MAI-Image 2.5",
          "vendor": "Microsoft",
          "vendor_en": "Microsoft",
          "score": "Arena #5",
          "why": "微軟 MAI 自研圖像模型",
          "why_en": "Microsoft's in-house MAI image model",
          "meta": "preview · 5/26 入榜",
          "meta_en": "preview · on leaderboard since 5/26"
        }
      ],
      "monthly": {
        "note": "本月不足 5 個新發佈，故以最近期(近 30–60 天)項目補足。",
        "note_en": "Fewer than 5 new releases this month, so recent (last 30-60 days) items are used to complete the list.",
        "items": [
          {
            "rank": 1,
            "name": "Google Pics (powered by Nano Banana)",
            "version": "GA",
            "vendor": "Google",
            "vendor_en": "Google",
            "date": "9/1",
            "date_en": "Sep 1",
            "isNew": true,
            "overlap": "整體 #4",
            "overlap_en": "Overall #4",
            "why": "作為 Google Workspace 的全新專業級 AI 圖片創作與編輯工具正式發佈，利用 Nano Banana 模型提供精確的物件編輯和圖片內文字處理能力。",
            "why_en": "Officially launched as a new pro-level AI image creator and editor integrated into Google Workspace, leveraging the Nano Banana model for precise object-based editing and in-image text manipulation."
          },
          {
            "rank": 2,
            "name": "Muse Image",
            "version": "GA on Fal Platform",
            "vendor": "Meta",
            "vendor_en": "Meta",
            "date": "9/1",
            "date_en": "Sep 1",
            "isNew": true,
            "overlap": "整體 #2",
            "overlap_en": "Overall #2",
            "why": "Meta 的 Muse Image 模型現已在 Fal 平台開放給開發者和企業使用，其代理框架具備規劃、搜尋和自我修正能力，在 Arena 排行榜上名列前茅。",
            "why_en": "Meta's Muse Image model is now available for developer and enterprise use on the Fal platform, featuring an agentic framework for planning, searching, and self-correction, ranking high on Arena leaderboards."
          },
          {
            "rank": 3,
            "name": "Gemini 3.8 Flash",
            "version": "3.8 Flash",
            "vendor": "Google",
            "vendor_en": "Google",
            "date": "9/2",
            "date_en": "Sep 2",
            "isNew": true,
            "overlap": "整體 #4",
            "overlap_en": "Overall #4",
            "why": "Google Gemini 系列的最新快速模型，預期在多模態能力上有所提升，包含圖像生成，是現有 Gemini 3.1 Flash Image 的後續版本。",
            "why_en": "Google's latest fast model in the Gemini series, expected to offer enhanced multimodal capabilities, including image generation, as a successor to the existing Gemini 3.1 Flash Image."
          },
          {
            "rank": 4,
            "name": "Muse Spark 1.3",
            "version": "1.3",
            "vendor": "Meta",
            "vendor_en": "Meta",
            "date": "9/1",
            "date_en": "Sep 1",
            "isNew": true,
            "overlap": null,
            "overlap_en": null,
            "why": "Meta Muse 系列的新版本，提供優化或專業化的圖像生成能力，進一步擴展了 Muse 模型的應用範圍。",
            "why_en": "A new version in Meta's Muse series, offering optimized or specialized image generation capabilities, further expanding the application scope of Muse models."
          },
          {
            "rank": 5,
            "name": "Reve 2.1",
            "version": "2.1",
            "vendor": "Reve",
            "vendor_en": "Reve",
            "date": "7/15 (近似)",
            "date_en": "Jul 15 (approx.)",
            "isNew": false,
            "overlap": "整體 #3",
            "overlap_en": "Overall #3",
            "why": "作為 Reve 2.0 的升級版，其獨特的「佈局優先」架構、原生 4K 輸出和強大的編輯功能，使其在專業藝術工作流程中表現出色。",
            "why_en": "An upgraded version of Reve 2.0, its unique 'layout-first' architecture, native 4K output, and powerful editing features make it excel in professional art workflows."
          }
        ]
      }
    },
    {
      "id": 5,
      "icon": "🎬",
      "name": "創建遊戲影片",
      "name_en": "Game / Stylized Video",
      "subtitle": "風格化 / 動畫向 Video",
      "subtitle_en": "Stylized / animated video",
      "overall": [
        {
          "rank": 1,
          "name": "Kling 3.0 / 3.0 Omni",
          "vendor": "快手 Kuaishou",
          "vendor_en": "Kuaishou",
          "score": "運鏡標竿",
          "score_en": "motion benchmark",
          "why": "電影級運鏡,東亞/動漫風訓練深,多角色對嘴",
          "why_en": "Cinematic motion; deep East-Asian/anime training; multi-character lip-sync",
          "meta": "2/4 · 付費 ~$0.10/s",
          "meta_en": "2/4 · paid ~$0.10/s"
        },
        {
          "rank": 2,
          "name": "Dreamina Seedance 2.0",
          "vendor": "ByteDance",
          "vendor_en": "ByteDance",
          "score": "多鏡頭敘事",
          "score_en": "multi-shot story",
          "why": "多鏡頭風格化敘事,動漫 I2V 強,原生音訊",
          "why_en": "Multi-shot stylized storytelling, strong anime I2V, native audio",
          "meta": "2/12 · CapCut/fal",
          "meta_en": "2/12 · CapCut/fal"
        },
        {
          "rank": 3,
          "name": "HappyHorse-1.0",
          "vendor": "Alibaba",
          "vendor_en": "Alibaba",
          "score": "50+ 風格",
          "score_en": "50+ styles",
          "why": "盲測 Arena 第一,50+ 風格,音訊同步",
          "why_en": "#1 in blind-test Arena, 50+ styles, audio sync",
          "meta": "4/27 · fal API",
          "meta_en": "4/27 · fal API"
        },
        {
          "rank": 4,
          "name": "PixVerse V6",
          "vendor": "PixVerse",
          "vendor_en": "PixVerse",
          "score": "動漫專精",
          "score_en": "anime-tuned",
          "why": "專為動漫/遊戲風格打造,20+ 運鏡控制",
          "why_en": "Built for anime/game styles, 20+ camera controls",
          "meta": "3/30 · 免費增值+API",
          "meta_en": "3/30 · freemium + API"
        },
        {
          "rank": 5,
          "name": "Pika 2.x",
          "vendor": "Pika",
          "vendor_en": "Pika",
          "score": "社群快剪",
          "score_en": "fast social",
          "why": "Pikaffects/Pikaswaps,快速社群/動漫短片",
          "why_en": "Pikaffects/Pikaswaps; quick social/anime clips",
          "meta": "2025–26 · 免費增值",
          "meta_en": "2025–26 · freemium"
        }
      ],
      "monthly": {
        "note": "本月(2026 年 9 月)僅有 1 個新發佈項目,其餘為近 30-60 天內發佈或 2026 年內最新旗艦版本。",
        "note_en": "Only 1 new release in September 2026; others are recent (within 30-60 days) or the latest flagship versions released in 2026.",
        "items": [
          {
            "rank": 1,
            "name": "H3 Max",
            "version": "N/A",
            "vendor": "fal",
            "vendor_en": "fal",
            "date": "9/1",
            "date_en": "Sep 1",
            "isNew": true,
            "overlap": null,
            "overlap_en": null,
            "why": "fal Research 開發的新型後訓練影片生成模型，針對超實時生成進行優化，在 Design Arena 影像轉影片排行榜上排名第一。",
            "why_en": "A new post-trained video generation model developed by fal Research, optimized for faster-than-real-time generation, ranking #1 on the Design Arena Image-to-Video leaderboard."
          },
          {
            "rank": 2,
            "name": "Seedance",
            "version": "2.5",
            "vendor": "ByteDance (字節跳動)",
            "vendor_en": "ByteDance",
            "date": "7/31",
            "date_en": "Jul 31",
            "isNew": false,
            "overlap": "整體 #2",
            "overlap_en": "Overall #2",
            "why": "多模態影片生成領域的重大突破，支援 30 秒原生影片生成及 50 種多模態參考輸入，並具備局部編輯功能。",
            "why_en": "A major breakthrough in multimodal video generation, supporting 30-second native videos with 50 multimodal references and local editing capabilities."
          },
          {
            "rank": 3,
            "name": "Pika",
            "version": "3.0",
            "vendor": "Pika Labs",
            "vendor_en": "Pika Labs",
            "date": "2026",
            "date_en": "2026",
            "isNew": false,
            "overlap": "整體 #5",
            "overlap_en": "Overall #5",
            "why": "2026 年旗艦模型，提供高擬真 4K 渲染、精確的攝影機控制和角色一致性，特別擅長風格化和動畫內容。",
            "why_en": "The flagship model for 2026, offering high-fidelity 4K rendering, precise camera controls, and character consistency, particularly strong for stylized and animated content."
          },
          {
            "rank": 4,
            "name": "Kling",
            "version": "3.0 Omni",
            "vendor": "Kuaishou (快手)",
            "vendor_en": "Kuaishou",
            "date": "6/17",
            "date_en": "Jun 17",
            "isNew": false,
            "overlap": "整體 #1",
            "overlap_en": "Overall #1",
            "why": "提供導演級控制、原生音訊同步及物理感知運動，並於 6 月更新強化了 4K 影片編輯的一致性和時長。",
            "why_en": "Offers director-level control, native audio sync, and physics-aware motion, with a June update enhancing 4K video editing consistency and duration."
          },
          {
            "rank": 5,
            "name": "PixVerse",
            "version": "V6",
            "vendor": "AIsphere (愛詩科技)",
            "vendor_en": "AIsphere",
            "date": "3/30",
            "date_en": "Mar 30",
            "isNew": false,
            "overlap": "整體 #4",
            "overlap_en": "Overall #4",
            "why": "提升了攝影機控制、角色表現及多鏡頭影片生成能力，支援原生音訊，適合製作短篇電影級內容。",
            "why_en": "Enhances camera control, character performance, and multi-shot video generation with native audio, suitable for short cinematic content."
          }
        ]
      }
    },
    {
      "id": 6,
      "icon": "🎥",
      "name": "創建真人影片",
      "name_en": "Live-Action Video",
      "subtitle": "寫實 / 真人向 Video",
      "subtitle_en": "Realistic / live-action video",
      "overall": [
        {
          "rank": 1,
          "name": "Kling 3.0 Pro (1080p)",
          "vendor": "快手 Kuaishou",
          "vendor_en": "Kuaishou",
          "score": "原生 4K",
          "score_en": "native 4K",
          "why": "原生 4K,對白/寫實強",
          "why_en": "Native 4K; strong dialogue/realism",
          "meta": "2 月 · 付費",
          "meta_en": "Feb · paid"
        },
        {
          "rank": 2,
          "name": "Dreamina Seedance 2.0 (720p)",
          "vendor": "ByteDance",
          "vendor_en": "ByteDance",
          "score": "含音訊·敘事強",
          "score_en": "Audio + strong narrative",
          "why": "Arena 榜首級(T2V & I2V),寫實 + 同步音訊",
          "why_en": "Top of Arena (T2V & I2V); realism + synced audio",
          "meta": "2/12 · CapCut/fal",
          "meta_en": "2/12 · CapCut/fal"
        },
        {
          "rank": 3,
          "name": "Google Veo 3.1 (+Fast)",
          "vendor": "Google",
          "vendor_en": "Google",
          "score": "提示遵從佳",
          "score_en": "best adherence",
          "why": "提示遵從最佳,原生音訊,4K,最穩",
          "why_en": "Best prompt adherence, native audio, 4K; most reliable",
          "meta": "~1 月 · Flow/Gemini",
          "meta_en": "~Jan · Flow/Gemini"
        },
        {
          "rank": 4,
          "name": "HappyHorse-1.0",
          "vendor": "Alibaba",
          "vendor_en": "Alibaba",
          "score": "盲測前段",
          "score_en": "Top blind-test tier",
          "why": "無音訊 Arena #1,1080p 寫實,低 WER 對嘴",
          "why_en": "#1 no-audio Arena; 1080p realism, low-WER lip-sync",
          "meta": "4/27 · fal API",
          "meta_en": "4/27 · fal API"
        },
        {
          "rank": 5,
          "name": "Runway Gen-4.5",
          "vendor": "Runway",
          "vendor_en": "Runway",
          "score": "專業運鏡",
          "score_en": "Pro control",
          "why": "專業製片首選:運鏡、結構化提示、可控性與後製銜接強",
          "why_en": "Pro film choice: camera moves, structured prompting, editability",
          "meta": "2026 · 專業工作流首選",
          "meta_en": "2026 · go-to pro workflow"
        }
      ],
      "monthly": {
        "note": "本月(2026 年 9 月)新發佈不足 5 個,已用近期(近 30–60 天)發佈補足。",
        "note_en": "Fewer than 5 new releases this month (September 2026), supplemented with recent releases (last 30-60 days).",
        "items": [
          {
            "rank": 1,
            "name": "H3 Max",
            "version": "fal H3 Max",
            "vendor": "fal",
            "vendor_en": "fal",
            "date": "9/1",
            "date_en": null,
            "isNew": true,
            "overlap": null,
            "overlap_en": null,
            "why": "基於 MiniMax H3 模型，經 fal 後訓練優化，實現領先的品質和超實時生成速度，在 Artificial Analysis 和 Design Arena 基準測試中排名第一。",
            "why_en": "Based on the MiniMax H3 model, post-trained and optimized by fal for frontier quality and faster-than-real-time generation, ranking #1 on Artificial Analysis and Design Arena benchmarks."
          },
          {
            "rank": 2,
            "name": "Gemini Omni 1.1 Flash",
            "version": "1.1 Flash",
            "vendor": "Google DeepMind",
            "vendor_en": "Google DeepMind",
            "date": "8/27",
            "date_en": null,
            "isNew": true,
            "overlap": null,
            "overlap_en": null,
            "why": "提供生產級的影片生成控制，包括場景延伸、首尾幀插值和 4K 升級，為開發者帶來更精準的創作能力。",
            "why_en": "Offers production-ready video generation control, including scene extension, first and last frame interpolation, and 4K upscaling, providing developers with more precise creative capabilities."
          },
          {
            "rank": 3,
            "name": "Hailuo AI H3",
            "version": "H3",
            "vendor": "MiniMax",
            "vendor_en": "MiniMax",
            "date": "7/31",
            "date_en": null,
            "isNew": false,
            "overlap": null,
            "overlap_en": null,
            "why": "將 Hailuo 系列提升至原生 2K 解析度，單次生成影片長度達 15 秒，並在同一過程中生成同步音訊，顯著提升影片品質和功能。",
            "why_en": "Upgrades the Hailuo series to native 2K resolution, extends single-generation clips to 15 seconds, and generates synchronized audio in the same pass, significantly enhancing video quality and features."
          },
          {
            "rank": 4,
            "name": "Kling 3.0 Turbo/Omni",
            "version": "3.0 Turbo/Omni",
            "vendor": "Kuaishou",
            "vendor_en": "Kuaishou",
            "date": "June 2026",
            "date_en": "June 2026",
            "isNew": false,
            "overlap": "整體 #1",
            "overlap_en": "Overall #1",
            "why": "Kling 3.0 的升級版本，提供更強大的功能和性能，進一步鞏固其在 AI 影片生成領域的領先地位。",
            "why_en": "An upgraded version of Kling 3.0, offering more powerful features and performance, further solidifying its leading position in AI video generation."
          },
          {
            "rank": 5,
            "name": "Dreamina Seedance 2.5",
            "version": "2.5",
            "vendor": "ByteDance",
            "vendor_en": "ByteDance",
            "date": "July 2026",
            "date_en": "July 2026",
            "isNew": false,
            "overlap": "整體 #2",
            "overlap_en": "Overall #2",
            "why": "Seedance 2.0 的增強版本，提供改進的影片品質、更長的影片生成能力、進階的多模態參考和精確的局部編輯功能。",
            "why_en": "An enhanced version of Seedance 2.0, offering improved video quality, longer video generation, advanced R2V multimodal references, and precise local editing capabilities."
          }
        ]
      }
    },
    {
      "id": 7,
      "icon": "🧊",
      "name": "創建遊戲模組",
      "name_en": "3D Asset Generation",
      "subtitle": "3D 模型生成 · 例如 Meshy",
      "subtitle_en": "3D model generation · e.g. Meshy",
      "overall": [
        {
          "rank": 1,
          "name": "Meshy-6",
          "vendor": "Meshy",
          "vendor_en": "Meshy",
          "score": "盲測勝出",
          "score_en": "won blind test",
          "why": "最均衡全流程(text/img→3D、PBR、低面數、匯出);盲測勝 Tripo",
          "why_en": "Most balanced full pipeline (text/img→3D, PBR, low-poly, export); beat Tripo in blind tests",
          "meta": "1/18 · 免費增值 ~$20/mo",
          "meta_en": "1/18 · freemium ~$20/mo"
        },
        {
          "rank": 2,
          "name": "Tripo P1.0 (+H3.1)",
          "vendor": "Tripo AI",
          "vendor_en": "Tripo AI",
          "score": "~2 秒出模",
          "score_en": "~2s mesh",
          "why": "原生 3D 擴散,~2 秒出引擎可用網格",
          "why_en": "Native 3D diffusion; engine-ready meshes in ~2s",
          "meta": "3/9 GDC · ~$12/mo",
          "meta_en": "3/9 GDC · ~$12/mo"
        },
        {
          "rank": 3,
          "name": "Rodin Gen-2",
          "vendor": "Hyper3D",
          "vendor_en": "Hyper3D",
          "score": "寫實最高",
          "score_en": "top realism",
          "why": "表面寫實度最高,四邊面 + 3D 修補",
          "why_en": "Highest surface realism; quad mesh + 3D inpainting",
          "meta": "2/9 · ~$30/mo",
          "meta_en": "2/9 · ~$30/mo"
        },
        {
          "rank": 4,
          "name": "Hunyuan3D 3.0",
          "vendor": "騰訊 Tencent",
          "vendor_en": "Tencent",
          "score": "開源自架",
          "score_en": "open-source",
          "why": "免費/可自架,開源線,1536³ 解析度",
          "why_en": "Free/self-hostable, open-source line, 1536³ resolution",
          "meta": "2025/9 · 免費自架",
          "meta_en": "2025/9 · free self-host"
        },
        {
          "rank": 5,
          "name": "TRELLIS 2",
          "vendor": "Microsoft(開源)",
          "vendor_en": "Microsoft (open-source)",
          "score": "開源材質佳",
          "score_en": "open texture",
          "why": "開源材質品質最佳(Gaussian-splat)",
          "why_en": "Best open-source texture quality (Gaussian-splat)",
          "meta": "2025–26 · 開源免費",
          "meta_en": "2025–26 · open-source, free"
        }
      ],
      "monthly": {
        "note": null,
        "note_en": null,
        "items": [
          {
            "rank": 1,
            "name": "Meshy 7",
            "version": "7",
            "vendor": "Meshy",
            "vendor_en": "Meshy",
            "date": "8/10",
            "date_en": "Aug 10",
            "isNew": false,
            "overlap": null,
            "overlap_en": null,
            "why": "全新的圖像到 3D 基礎模型，顯著提升了輸入圖像與生成 3D 模型之間的對齊精確度，是本月最受矚目的更新。",
            "why_en": "A new image-to-3D foundation model that significantly improves alignment accuracy between input images and generated 3D models, making it the most notable update this month."
          },
          {
            "rank": 2,
            "name": "Reallusion AI Studio",
            "version": "1.1",
            "vendor": "Reallusion",
            "vendor_en": "Reallusion",
            "date": "9/2",
            "date_en": "Sep 2",
            "isNew": true,
            "overlap": null,
            "overlap_en": null,
            "why": "作為一個獨立應用程式正式發佈，並擴展了 AI 模型套件和升級的 AI Actor Creator，大幅提升了 3D 角色創建工作流程。",
            "why_en": "Officially released as a standalone application, expanding its AI model suite and upgrading the AI Actor Creator, significantly enhancing 3D character creation workflows."
          },
          {
            "rank": 3,
            "name": "Hi3D",
            "version": "V3.0",
            "vendor": "Math Magic",
            "vendor_en": "Math Magic",
            "date": "8/20",
            "date_en": "Aug 20",
            "isNew": false,
            "overlap": null,
            "overlap_en": null,
            "why": "此更新將幾何重建解析度提高到 2048³ 體素，旨在提供更高的精確度和保真度，減少早期建模時間。",
            "why_en": "This update increases geometric reconstruction to 2048³ voxel resolution, aiming to provide higher precision and fidelity and reduce early-stage modeling time."
          },
          {
            "rank": 4,
            "name": "Meshy 6 Lite",
            "version": "6 Lite",
            "vendor": "Meshy",
            "vendor_en": "Meshy",
            "date": "8月",
            "date_en": "Aug",
            "isNew": false,
            "overlap": null,
            "overlap_en": null,
            "why": "作為 Meshy 6 架構的輕量化版本，專為快速迭代和便捷生成而設計，提供更快的生成速度。",
            "why_en": "A streamlined variant of the Meshy 6 architecture, designed for rapid prototyping and accessible generation, offering faster generation speeds."
          },
          {
            "rank": 5,
            "name": "Hunyuan 3D (TokenHub 全球 API)",
            "version": "3.0/3.1 (API Access)",
            "vendor": "Tencent",
            "vendor_en": "Tencent",
            "date": "9/1",
            "date_en": "Sep 1",
            "isNew": true,
            "overlap": "整體 #4",
            "overlap_en": "Overall #4",
            "why": "透過 Tencent Cloud TokenHub 重新推出全球 API 存取，顯著提升了現有強大模型的可用性和整合性，使其更易於全球開發者使用。",
            "why_en": "Re-launched global API access via Tencent Cloud TokenHub, significantly enhancing the usability and integration of existing powerful models for global developers."
          }
        ]
      }
    },
    {
      "id": 8,
      "icon": "🦴",
      "name": "遊戲模組 Rigging",
      "name_en": "Game Asset Rigging",
      "subtitle": "綁骨 / 可動 · 例如 Anything World",
      "subtitle_en": "Rigging / animation-ready · e.g. Anything World",
      "overall": [
        {
          "rank": 1,
          "name": "Meshy-6 Auto-Rig + Animate",
          "vendor": "Meshy",
          "vendor_en": "Meshy",
          "score": "<30s·500+動作",
          "score_en": "<30s · 500+ anims",
          "why": "一站式,<30 秒自動綁人形/四足,500+ 預設動作",
          "why_en": "One-stop; auto-rigs humanoids/quadrupeds in <30s, 500+ preset animations",
          "meta": "2025–26 · ~$20/mo",
          "meta_en": "2025–26 · ~$20/mo"
        },
        {
          "rank": 2,
          "name": "Autodesk Flow Studio AI Rigging",
          "vendor": "Autodesk",
          "vendor_en": "Autodesk",
          "score": "免費綁骨",
          "score_en": "free rigging",
          "why": "AI 自動關節 + AI 動捕,匯出 Maya/Blender/UE",
          "why_en": "AI auto-joints + AI mocap; export to Maya/Blender/UE",
          "meta": "4/28 · 全層免費預覽",
          "meta_en": "4/28 · free preview, all tiers"
        },
        {
          "rank": 3,
          "name": "Tripo Auto-Rigging (Uni-Rig)",
          "vendor": "Tripo AI",
          "vendor_en": "Tripo AI",
          "score": "骨架+動畫",
          "score_en": "rig + anim",
          "why": "自動骨架 + 權重 + 自動動畫,風格化佳",
          "why_en": "Auto-skeleton + weights + auto-animation; great for stylized",
          "meta": "2025–26 · ~$12/mo",
          "meta_en": "2025–26 · ~$12/mo"
        },
        {
          "rank": 4,
          "name": "Cascadeur 2026.1",
          "vendor": "Nekki",
          "vendor_en": "Nekki",
          "score": "AI 物理動作",
          "score_en": "AI physics",
          "why": "AI AutoPosing/Physics + AI Root Motion,UE Live Link",
          "why_en": "AI AutoPosing/Physics + AI Root Motion; UE Live Link",
          "meta": "4/9 · 免費層+訂閱",
          "meta_en": "4/9 · free tier + subscription"
        },
        {
          "rank": 5,
          "name": "Anything World — Animate Anything",
          "vendor": "Anything World",
          "vendor_en": "Anything World",
          "score": "任意網格",
          "score_en": "any mesh",
          "why": "任意靜態網格 AI 綁定(尤其動物/生物)",
          "why_en": "AI-rig any static mesh (esp. animals/creatures)",
          "meta": "Live · 免費起步+API",
          "meta_en": "Live · free start + API"
        }
      ],
      "monthly": {
        "note": "本月(2026 年 9 月)尚未有足夠的正式發佈項目,因此榜單包含最近期(2026 年 8 月)的發佈與更新。",
        "note_en": "As there are not enough official releases in September 2026, this list includes releases and updates from the most recent period (August 2026).",
        "items": [
          {
            "rank": 1,
            "name": "Meshy 7 Auto-Rig + Animate",
            "version": "7",
            "vendor": "Meshy",
            "vendor_en": "Meshy",
            "date": "8/10",
            "date_en": "Aug 10",
            "isNew": false,
            "overlap": "整體 #1",
            "overlap_en": "Overall #1",
            "why": "Meshy 7 模型更新,顯著提升 3D 生成與自動綁骨能力,特別是新增四足動物綁骨支援,並於 8 月 10 日正式上線。",
            "why_en": "Meshy 7 model update significantly enhances 3D generation and auto-rigging capabilities, notably adding quadruped rigging support, officially launched on August 10."
          },
          {
            "rank": 2,
            "name": "Autodesk Flow Studio 3D Editor + Canvas",
            "version": "主要擴展",
            "vendor": "Autodesk",
            "vendor_en": "Autodesk",
            "date": "8/4",
            "date_en": "Aug 4",
            "isNew": false,
            "overlap": "整體 #2",
            "overlap_en": "Overall #2",
            "why": "Autodesk Flow Studio 於 8 月 4 日推出重大擴展,包含 3D Editor + Canvas,進一步強化其 AI 綁骨與角色動畫工作流程。",
            "why_en": "Autodesk Flow Studio launched a major expansion on August 4, including 3D Editor + Canvas, further enhancing its AI rigging and character animation workflows."
          },
          {
            "rank": 3,
            "name": "Armature",
            "version": "1.0",
            "vendor": "FabricatorStudio",
            "vendor_en": "FabricatorStudio",
            "date": "8/6",
            "date_en": "Aug 6",
            "isNew": false,
            "overlap": null,
            "overlap_en": null,
            "why": "一款新發佈的獨立 AI 輔助角色綁骨與蒙皮工具,對獨立藝術家免費,支援 USD 導出至主流 DCC 軟體。",
            "why_en": "A newly released standalone AI-assisted character rigging and skinning tool, free for indie artists, supporting USD export to major DCC applications."
          },
          {
            "rank": 4,
            "name": "V2Fun",
            "version": "平台更新",
            "vendor": "V2Fun",
            "vendor_en": "V2Fun",
            "date": "8/28",
            "date_en": "Aug 28",
            "isNew": false,
            "overlap": null,
            "overlap_en": null,
            "why": "作為整合式 AI 3D 模型生成、綁骨與動畫平台,於 8 月 28 日進行了更新,提供更流暢的工作流程。",
            "why_en": "An integrated AI 3D model generator, rigging, and animation platform, updated on August 28 to provide a smoother workflow."
          },
          {
            "rank": 5,
            "name": "Tripo AI Rig v2.5",
            "version": "更新",
            "vendor": "Tripo AI",
            "vendor_en": "Tripo AI",
            "date": "8/17",
            "date_en": "Aug 17",
            "isNew": false,
            "overlap": "整體 #3",
            "overlap_en": "Overall #3",
            "why": "Tripo AI 於 8 月 17 日更新了其 Rig v2.5 模型,改進了動畫重定向預設白名單,持續優化其自動綁骨功能。",
            "why_en": "Tripo AI updated its Rig v2.5 model on August 17, modifying the animate_retarget preset whitelist and continuously optimizing its auto-rigging capabilities."
          }
        ]
      }
    },
    {
      "id": 9,
      "icon": "🔊",
      "name": "創建聲音特效",
      "name_en": "Sound Effects & Audio",
      "subtitle": "SFX / 語音 / 音樂 · 例如 ElevenLabs",
      "subtitle_en": "SFX / voice / music · e.g. ElevenLabs",
      "overall": [
        {
          "rank": 1,
          "name": "ElevenLabs SFX v2 + v3 voice",
          "vendor": "ElevenLabs",
          "vendor_en": "ElevenLabs",
          "score": "SFX 龍頭",
          "score_en": "SFX leader",
          "why": "遊戲音訊最全:文字轉 SFX(30s、可無縫循環)+ 頂級語音",
          "why_en": "Most complete game-audio stack: text-to-SFX (30s, seamless loops) + top-tier voice",
          "meta": "SFX 2025/9 · v3 2 月",
          "meta_en": "SFX 2025/9 · v3 Feb"
        },
        {
          "rank": 2,
          "name": "Suno v5",
          "vendor": "Suno",
          "vendor_en": "Suno",
          "score": "音樂 ELO 1293",
          "score_en": "Music ELO 1293",
          "why": "音樂盲測第一(ELO 1293);全曲+人聲質量標竿",
          "why_en": "#1 in music blind tests (ELO 1293); full-song + vocal benchmark",
          "meta": "3/27 · 訂閱制",
          "meta_en": "3/27 · subscription"
        },
        {
          "rank": 3,
          "name": "ElevenLabs Music v2",
          "vendor": "ElevenLabs",
          "vendor_en": "ElevenLabs",
          "score": "商用授權",
          "score_en": "licensed",
          "why": "商用授權清晰,可在曲中嵌 SFX、中途換曲風",
          "why_en": "Clear commercial licensing; embed SFX in tracks, mid-track genre switch",
          "meta": "5/26 · 降價 40–50%",
          "meta_en": "5/26 · 40–50% cheaper"
        },
        {
          "rank": 4,
          "name": "Stable Audio 3",
          "vendor": "Stability AI",
          "vendor_en": "Stability AI",
          "score": "開源·SFX",
          "score_en": "open-source SFX",
          "why": "開源,音樂 + SFX/foley 統一,適合自架 pipeline",
          "why_en": "Open-source; unified music + SFX/foley; great for self-hosted pipelines",
          "meta": "5/20 · 開源權重",
          "meta_en": "5/20 · open weights"
        },
        {
          "rank": 5,
          "name": "Lyria 3 Pro",
          "vendor": "Google DeepMind",
          "vendor_en": "Google DeepMind",
          "score": "3 分鐘長曲",
          "score_en": "3-min tracks",
          "why": "最長 3 分鐘結構化曲目,SynthID 浮水印",
          "why_en": "Up to 3-min structured tracks; SynthID watermark",
          "meta": "3/25 · Gemini/Vertex",
          "meta_en": "3/25 · Gemini/Vertex"
        }
      ],
      "monthly": {
        "note": null,
        "note_en": null,
        "items": [
          {
            "rank": 1,
            "name": "Adobe Firefly 音訊工具套件",
            "version": "GA",
            "vendor": "Adobe",
            "vendor_en": "Adobe",
            "date": "8/20",
            "date_en": "Aug 20",
            "isNew": true,
            "overlap": null,
            "overlap_en": null,
            "why": "Firefly 首次推出涵蓋音樂、語音和音效的全面性音訊生成工具，支援商業用途。",
            "why_en": "Firefly's first comprehensive audio generation suite for music, speech, and sound effects, supporting commercial use."
          },
          {
            "rank": 2,
            "name": "Deepdub Phantom Z 3.4 Conversational",
            "version": "3.4 Conversational",
            "vendor": "Deepdub",
            "vendor_en": "Deepdub",
            "date": "9/3",
            "date_en": "Sep 3",
            "isNew": true,
            "overlap": null,
            "overlap_en": null,
            "why": "高傳真 48 kHz 多語言文字轉語音模型，具備改進的文字正規化和即時對話能力。",
            "why_en": "High-fidelity 48 kHz multilingual text-to-speech model with improved text normalization and real-time conversational capabilities."
          },
          {
            "rank": 3,
            "name": "Gradium AI 新預設 TTS 模型",
            "version": "GA",
            "vendor": "Gradium AI",
            "vendor_en": "Gradium AI",
            "date": "8/31",
            "date_en": "Aug 31",
            "isNew": true,
            "overlap": null,
            "overlap_en": null,
            "why": "成為預設的文字轉語音模型，在複雜語句上達到 81.0% 的高通過率，並提供低延遲。",
            "why_en": "Became the default TTS model, achieving an 81.0% pass rate on hard sentences with low latency."
          },
          {
            "rank": 4,
            "name": "Meta Muse Voice Transcribe",
            "version": "GA",
            "vendor": "Meta Superintelligence Labs",
            "vendor_en": "Meta Superintelligence Labs",
            "date": "9/2",
            "date_en": "Sep 2",
            "isNew": true,
            "overlap": null,
            "overlap_en": null,
            "why": "首個即時音訊感知模型，提供串流 ASR、多說話者辨識和端點偵測功能。",
            "why_en": "The first real-time audio perception model, offering streaming ASR, multi-speaker diarization, and endpointing."
          },
          {
            "rank": 5,
            "name": "ElevenLabs Music (新增人聲功能)",
            "version": "v2 (with vocals)",
            "vendor": "ElevenLabs",
            "vendor_en": "ElevenLabs",
            "date": "8/21",
            "date_en": "Aug 21",
            "isNew": true,
            "overlap": "整體 #3",
            "overlap_en": "Overall #3",
            "why": "ElevenLabs Music 增加了生成帶有人聲的音樂功能，顯著擴展了其音樂創作能力。",
            "why_en": "ElevenLabs Music added the capability to generate music with vocals, significantly expanding its music creation features."
          }
        ]
      }
    },
    {
      "id": 10,
      "icon": "🧩",
      "name": "AI 工具組合 Combo",
      "name_en": "AI Tool Combos",
      "subtitle": "依社群熱度 Top10 · 例如 Claude + Obsidian",
      "subtitle_en": "By popularity, Top 10 · e.g. Claude + Obsidian",
      "overall": [
        {
          "rank": 1,
          "name": "Cursor + Claude Code + GitHub Copilot",
          "vendor": "Anysphere + Anthropic + OpenAI/GitHub",
          "vendor_en": "Anysphere + Anthropic + OpenAI/GitHub",
          "score": "巨量採用",
          "score_en": "huge adoption",
          "why": "主流「出貨」編程組合:IDE agent + 終端 agent 並用;1.8M Copilot 開發者、~半數財星500用 Cursor",
          "why_en": "The dominant 'ship software' coding stack; 1.8M Copilot devs, ~half of Fortune 500 on Cursor",
          "meta": "媒體高曝光",
          "meta_en": "heavy media coverage"
        },
        {
          "rank": 2,
          "name": "Claude Code + GitHub + Vercel",
          "vendor": "Anthropic + GitHub + Vercel",
          "vendor_en": "Anthropic + GitHub + Vercel",
          "score": "廣傳·官方",
          "score_en": "viral · official",
          "why": "prompt→push→自動部署上線;官方 Vercel 外掛(你正在用的)",
          "why_en": "prompt→push→auto-deploy live; official Vercel plugin (the one you use)",
          "meta": "YouTube/媒體廣傳",
          "meta_en": "widely shared"
        },
        {
          "rank": 3,
          "name": "n8n + LLM (OpenAI/Claude) + MCP",
          "vendor": "n8n",
          "vendor_en": "n8n",
          "score": "GitHub 191k★",
          "score_en": "GitHub 191k★",
          "why": "可自架的視覺化 AI agent/工作流自動化;191k stars、$2.5B 估值",
          "why_en": "Self-hosted visual AI-agent/workflow automation; 191k stars, $2.5B valuation",
          "meta": "230k+ users",
          "meta_en": "230k+ users"
        },
        {
          "rank": 4,
          "name": "ComfyUI + Flux / Suno / ElevenLabs",
          "vendor": "ComfyUI + community",
          "vendor_en": "ComfyUI + community",
          "score": "GitHub ~110k★",
          "score_en": "GitHub ~110k★",
          "why": "節點式創作流水線:圖→影→語音/音樂同一畫布;ElevenLabs 官方節點",
          "why_en": "Node-graph creative pipeline: image→video→voice/music; official ElevenLabs node",
          "meta": "~106k+ stars",
          "meta_en": "~106k+ stars"
        },
        {
          "rank": 5,
          "name": "ChatGPT / Claude + Notion",
          "vendor": "OpenAI/Anthropic + Notion",
          "vendor_en": "OpenAI/Anthropic + Notion",
          "score": "高討論",
          "score_en": "highly discussed",
          "why": "LLM 在你的團隊 wiki/筆記上推理;最常被搜的生產力配對",
          "why_en": "LLM reasoning over your team wiki/notes; most-searched productivity pairing",
          "meta": "Reddit/媒體高討論",
          "meta_en": "Reddit/media buzz"
        },
        {
          "rank": 6,
          "name": "Microsoft Copilot (Agent 365) + Claude + GPT",
          "vendor": "Microsoft + Anthropic + OpenAI",
          "vendor_en": "Microsoft + Anthropic + OpenAI",
          "score": "企業高曝光",
          "score_en": "enterprise buzz",
          "why": "企業多模型調度:「GPT 起草、Claude 審查」",
          "why_en": "Enterprise multi-model orchestration: 'GPT drafts, Claude reviews'",
          "meta": "Agent 365 GA 5/1",
          "meta_en": "Agent 365 GA May 1"
        },
        {
          "rank": 7,
          "name": "Claude + Obsidian",
          "vendor": "Anthropic + Obsidian",
          "vendor_en": "Anthropic + Obsidian",
          "score": "YouTube 廣傳",
          "score_en": "viral on YouTube",
          "why": "AI 第二大腦:Claude 讀寫你的本地筆記(你同事推的那個)",
          "why_en": "AI second brain: Claude reads/builds on your local notes (your colleague's pick)",
          "meta": "XDA/多篇教學",
          "meta_en": "XDA + many guides"
        },
        {
          "rank": 8,
          "name": "Perplexity + NotebookLM + Claude",
          "vendor": "Perplexity + Google + Anthropic",
          "vendor_en": "Perplexity + Google + Anthropic",
          "score": "研究熱門",
          "score_en": "popular research",
          "why": "研究組合:有來源的網搜 → 來源紮根 → 深入推理",
          "why_en": "Research stack: cited web search → source grounding → deep reasoning",
          "meta": "媒體高討論",
          "meta_en": "heavy coverage"
        },
        {
          "rank": 9,
          "name": "Midjourney + Runway/Veo + ElevenLabs + Suno + Descript",
          "vendor": "多家 multi-vendor",
          "vendor_en": "multi-vendor",
          "score": "製片廣傳",
          "score_en": "popular for video",
          "why": "端到端 AI 影片:腳本→分鏡→畫面→配音→配樂→剪輯",
          "why_en": "End-to-end AI video: script→storyboard→footage→VO→music→edit",
          "meta": "標準製片流程",
          "meta_en": "standard production stack"
        },
        {
          "rank": 10,
          "name": "Raycast AI + Claude / Perplexity / NotebookLM",
          "vendor": "Raycast + 多家",
          "vendor_en": "Raycast + multi-vendor",
          "score": "中討論",
          "score_en": "modest buzz",
          "why": "Mac 啟動器當各 AI 工具的黏合層(剪貼簿、片語、MCP)",
          "why_en": "Mac launcher as the glue across AI tools (clipboard, snippets, MCP)",
          "meta": "Substack 報導",
          "meta_en": "Substack feature"
        }
      ],
      "monthly": {
        "note": "本月（2026 年 9 月）新發佈的 AI 工具組合不足 10 個，因此此列表已用近期（2026 年 8 月下旬）發佈的項目補足。",
        "note_en": "Insufficient new AI tool combinations were released in September 2026, so this list has been supplemented with recent releases from late August 2026.",
        "items": [
          {
            "rank": 1,
            "name": "Microsoft Copilot (Agent 365) + Claude Sonnet 5 + GPT-4o Enterprise",
            "version": "Agent 365, Sonnet 5, GPT-4o Enterprise",
            "vendor": "微軟, Anthropic, OpenAI",
            "vendor_en": "Microsoft, Anthropic, OpenAI",
            "date": "8/28",
            "date_en": null,
            "isNew": false,
            "overlap": "整體 #6",
            "overlap_en": "Overall #6",
            "why": "增強的多代理能力和企業級安全性，適用於複雜的工作流程。",
            "why_en": "Enhanced multi-agent capabilities and enterprise-grade security for complex workflows."
          },
          {
            "rank": 2,
            "name": "n8n 2.5 + Gemini 3.5 Flash + Microsoft Power Automate Connector",
            "version": "2.5, 3.5 Flash, Connector",
            "vendor": "n8n, Google, 微軟",
            "vendor_en": "n8n, Google, Microsoft",
            "date": "8/26",
            "date_en": null,
            "isNew": false,
            "overlap": "整體 #3",
            "overlap_en": "Overall #3",
            "why": "簡化低程式碼自動化，結合更快的 LLM 推理和企業級整合。",
            "why_en": "Streamlined low-code automation with faster LLM inference and enterprise integration."
          },
          {
            "rank": 3,
            "name": "ComfyUI + Stability AI Stable Video Diffusion 3.0 + ElevenLabs Prime",
            "version": "Stable Video Diffusion 3.0, Prime",
            "vendor": "ComfyUI 社群, Stability AI, ElevenLabs",
            "vendor_en": "ComfyUI Community, Stability AI, ElevenLabs",
            "date": "8/29",
            "date_en": null,
            "isNew": false,
            "overlap": "整體 #4",
            "overlap_en": "Overall #4",
            "why": "透過高傳真音訊實現進階客製化影片生成工作流程。",
            "why_en": "Advanced custom video generation workflows with high-fidelity audio."
          },
          {
            "rank": 4,
            "name": "Claude Fable 5 + Obsidian Canvas 2.0 + Perplexity Enterprise API",
            "version": "Fable 5, Canvas 2.0, Enterprise API",
            "vendor": "Anthropic, Obsidian, Perplexity AI",
            "vendor_en": "Anthropic, Obsidian, Perplexity AI",
            "date": "8/27",
            "date_en": null,
            "isNew": false,
            "overlap": null,
            "overlap_en": null,
            "why": "整合知識管理、進階推理和研究能力。",
            "why_en": "Integrated knowledge management, advanced reasoning, and research capabilities."
          },
          {
            "rank": 5,
            "name": "Vercel AI SDK 3.0 + Llama 4.0 Integration + GitHub Copilot Enterprise",
            "version": "AI SDK 3.0, Llama 4.0, Enterprise",
            "vendor": "Vercel, Meta, GitHub",
            "vendor_en": "Vercel, Meta, GitHub",
            "date": "8/25",
            "date_en": null,
            "isNew": false,
            "overlap": null,
            "overlap_en": null,
            "why": "結合開源 LLM 和企業級程式碼輔助的全端 AI 應用程式開發。",
            "why_en": "Full-stack AI application development with open-source LLM and enterprise coding assistance."
          },
          {
            "rank": 6,
            "name": "Raycast AI Pro + Claude Sonnet 5 + Perplexity Pro",
            "version": "AI Pro, Sonnet 5, Pro",
            "vendor": "Raycast, Anthropic, Perplexity AI",
            "vendor_en": "Raycast, Anthropic, Perplexity AI",
            "date": "8/30",
            "date_en": null,
            "isNew": false,
            "overlap": "整體 #10",
            "overlap_en": "Overall #10",
            "why": "增強的桌面 AI 助理，結合強大的 LLM 以提高生產力和研究效率。",
            "why_en": "Enhanced desktop AI assistant with powerful LLMs for productivity and research."
          },
          {
            "rank": 7,
            "name": "Midjourney v7 + RunwayML Gen-3 + Suno v4 + ElevenLabs Prime + Descript Pro",
            "version": "v7, Gen-3, v4, Prime, Pro",
            "vendor": "Midjourney, RunwayML, Suno, ElevenLabs, Descript",
            "vendor_en": "Midjourney, RunwayML, Suno, ElevenLabs, Descript",
            "date": "8/28",
            "date_en": null,
            "isNew": false,
            "overlap": "整體 #9",
            "overlap_en": "Overall #9",
            "why": "用於進階內容創作的綜合多模態 AI 套件。",
            "why_en": "Comprehensive multi-modal AI suite for advanced content creation."
          },
          {
            "rank": 8,
            "name": "Cursor IDE 2.0 + Claude Code 5 + GitHub Copilot Workspace",
            "version": "IDE 2.0, Code 5, Workspace",
            "vendor": "Cursor, Anthropic, GitHub",
            "vendor_en": "Cursor, Anthropic, GitHub",
            "date": "8/29",
            "date_en": null,
            "isNew": false,
            "overlap": "整體 #1",
            "overlap_en": "Overall #1",
            "why": "下一代 AI 原生 IDE，用於加速程式碼開發和專案管理。",
            "why_en": "Next-generation AI-native IDE for accelerated code development and project management."
          },
          {
            "rank": 9,
            "name": "Notion AI Enterprise + Gemini 3.5 Pro + Zapier AI Actions",
            "version": "AI Enterprise, 3.5 Pro, AI Actions",
            "vendor": "Notion, Google, Zapier",
            "vendor_en": "Notion, Google, Zapier",
            "date": "8/27",
            "date_en": null,
            "isNew": false,
            "overlap": null,
            "overlap_en": null,
            "why": "具備進階自動化和 LLM 能力的企業級 AI 工作區。",
            "why_en": "Enterprise-grade AI workspace with advanced automation and LLM capabilities."
          },
          {
            "rank": 10,
            "name": "Hugging Face Spaces + Mistral Large 3 + Gradio 4.0",
            "version": "Spaces, Large 3, 4.0",
            "vendor": "Hugging Face, Mistral AI, Gradio",
            "vendor_en": "Hugging Face, Mistral AI, Gradio",
            "date": "8/26",
            "date_en": null,
            "isNew": false,
            "overlap": null,
            "overlap_en": null,
            "why": "結合強大 LLM 的開源 AI 模型部署和快速原型開發。",
            "why_en": "Open-source AI model deployment and rapid prototyping with powerful LLM."
          }
        ]
      }
    }
  ]
};
